def two(en, fr): return {"en": en, "fr": fr}
BLOCKS = [
    # ------------------------------------------------------------------ Origins
    {"h3": two("Origins", "Origines")},
    {"p": two(
        "John Marston was born in 1873, the year carved on his gravestone. In 1907, he tells Hamish Sinclair that he was born \"further north\" and spent a lot of time out west. His mother, a prostitute, died giving birth to him. In Red Dead Redemption, he describes his father to [[bonnie-macfarlane|Bonnie MacFarlane]] as \"an illiterate Scot, born on the boat into New York\". The father never saw Scotland but talked about it constantly. He also hated the English for what had been done to his great-grandparents. To his son Jack, John later says his father drank heavily and that he barely knew him.",
        "John Marston naît en 1873, l'année gravée sur sa tombe. En 1907, il explique à Hamish Sinclair qu'il est né \"plus au nord\" et qu'il a passé beaucoup de temps dans l'Ouest. Sa mère, une prostituée, meurt en le mettant au monde. Dans Red Dead Redemption, il décrit son père à [[bonnie-macfarlane|Bonnie MacFarlane]] comme un Écossais illettré, né sur le bateau qui arrivait à New York. Cet homme n'a jamais vu l'Écosse, mais en parlait sans cesse. Il détestait aussi les Anglais pour ce qu'ils avaient fait subir à ses arrière-grands-parents. Des années plus tard, John confie à son fils Jack que son père buvait beaucoup et qu'il l'a à peine connu.")},
    {"p": two(
        "His father died in 1881, when John was eight. John gives two accounts of what happened to him. To Bonnie, he says his father was blinded in a bar fight south of Chicago. To Jack, he says his father died in a bar fight, adding \"at least, that's what they told me\". The boy was then placed in an orphanage, which he ran away from to live on the streets. In an optional camp conversation in Red Dead Redemption 2, John says he was eleven the first time he shot a man.",
        "Son père meurt en 1881, quand John a huit ans. John raconte sa fin de deux façons. À Bonnie, il dit que son père a perdu la vue dans une bagarre de bar au sud de Chicago. À Jack, il explique qu'il est mort dans une bagarre de bar, en précisant que \"c'est ce qu'on lui a dit\". L'enfant est ensuite placé dans un orphelinat, dont il s'enfuit pour vivre dans la rue. Dans une conversation facultative au camp de Red Dead Redemption 2, John raconte qu'il avait onze ans la première fois qu'il a tiré sur un homme.")},
    {"p": two(
        "According to the official guide to Red Dead Redemption 2, John was twelve, in 1885, when he was caught stealing and about to be hanged. [[dutch-van-der-linde|Dutch van der Linde]] intervened and took him in. Dutch already rode with [[hosea-matthews|Hosea Matthews]] and [[arthur-morgan|Arthur Morgan]]. The gang raised John. Dutch taught him to read, to shoot and to hunt. John tells Bonnie in 1911 that the leader of his gang taught him \"to see all that was good in the world\". In his 1907 journal, he calls the writer Evelyn Miller \"the writer I grew up with, Dutch's favorite\". John also tells Jack that [[uncle|Uncle]] \"was old when I was a kid\"; the wiki only dates Uncle's arrival in the gang to before 1894.",
        "D'après le guide officiel de Red Dead Redemption 2, John a douze ans, en 1885, quand il est pris en train de voler et sur le point d'être pendu. [[dutch-van-der-linde|Dutch van der Linde]] intervient et le prend sous son aile. Dutch fait déjà équipe avec [[hosea-matthews|Hosea Matthews]] et [[arthur-morgan|Arthur Morgan]]. Le gang élève John. Dutch lui apprend à lire, à tirer et à chasser. En 1911, John dit à Bonnie que le chef de son gang lui a appris à voir ce qu'il y avait de bon dans le monde. Dans son journal de 1907, il présente l'écrivain Evelyn Miller comme l'auteur avec lequel il a grandi, le préféré de Dutch. John raconte aussi à Jack qu'[[uncle|Uncle]] était déjà vieux quand lui était gamin ; le wiki situe seulement son arrivée dans le gang avant 1894.")},
    {"p": two(
        "John grew up as one of the gang's outlaws, taking part in robberies across the West alongside Dutch, Hosea, Arthur and later [[bill-williamson|Bill Williamson]] and [[javier-escuella|Javier Escuella]]. Rockstar's character description for Red Dead Redemption 2 calls him an orphaned street kid who has \"always had to live by his wits\", and names him and Arthur as Dutch's \"proudest protégés\". In 1911, when Bonnie asks whether he killed people in those years, John answers: \"Sure, and I've suffered for it.\" The official guide describes him in 1899 as Abigail's husband \"in all but lawful status\".",
        "John devient l'un des hors-la-loi du gang et participe à des braquages dans tout l'Ouest, aux côtés de Dutch, Hosea, Arthur, puis de [[bill-williamson|Bill Williamson]] et de [[javier-escuella|Javier Escuella]]. La fiche de présentation de Rockstar pour Red Dead Redemption 2 le décrit comme un orphelin des rues qui a toujours dû se débrouiller seul, et fait de lui et d'Arthur les deux protégés dont Dutch est le plus fier. En 1911, quand Bonnie lui demande s'il a tué des gens à cette époque, John répond que oui, et qu'il en a souffert. Le guide officiel le présente en 1899 comme le mari d'Abigail, sans l'être légalement.")},
    {"p": two(
        "[[abigail-marston|Abigail Roberts]] joined the gang in 1894, according to the official guide. She and John became a couple, and their son [[jack-marston|Jack]] was born around 1895. The gang members became aunts and uncles to the boy. When Jack was still a baby, John left the gang for about a year, then came back. Dutch and Hosea welcomed him back; Arthur held the departure against him. In 1899, when John goes missing in the snow, Arthur suggests he may have kept riding north and adds: \"wouldn't be the first time\". Throughout 1899, John is uneasy as a father, and Abigail reproaches him for it.",
        "[[abigail-marston|Abigail Roberts]] rejoint le gang en 1894, selon le guide officiel. Elle et John se mettent ensemble, et leur fils [[jack-marston|Jack]] naît vers 1895. Les membres du gang deviennent pour l'enfant des oncles et des tantes. Alors que Jack n'est encore qu'un bébé, John quitte le gang pendant près d'un an, puis revient. Dutch et Hosea l'accueillent à bras ouverts ; Arthur, lui, ne lui pardonne pas ce départ. En 1899, quand John disparaît dans la neige, Arthur suppose qu'il a peut-être filé vers le nord, et ajoute que ce ne serait pas la première fois. Tout au long de 1899, John peine à trouver sa place de père, ce qu'Abigail lui reproche.")},
    {"p": two(
        "By 1899, the gang had taken in newer members such as [[micah-bell|Micah Bell]] and [[charles-smith|Charles Smith]], and had settled for a time in Blackwater, a port town in West Elizabeth. John was part of the crew on the ferry robbery there, weeks before the start of Red Dead Redemption 2. Pinkerton agents arrived while the gang held the money, and the job ended in a shootout. During the robbery, Dutch killed a young woman, Heidi McCourt. Davey Callander, Mac Callander and John were all shot, according to Javier. Jenny Kirk was killed and [[sean-macguire|Sean MacGuire]] went missing. The gang hid the money in Blackwater and fled north into the mountains.",
        "En 1899, le gang compte de nouvelles recrues, dont [[micah-bell|Micah Bell]] et [[charles-smith|Charles Smith]], et s'est installé un temps à Blackwater, une ville portuaire de West Elizabeth. John fait partie de l'équipe qui braque un ferry dans le port, quelques semaines avant le début de Red Dead Redemption 2. Les agents de la Pinkerton surgissent alors que le gang tient l'argent, et le coup tourne à la fusillade. Pendant le braquage, Dutch tue une jeune femme, Heidi McCourt. Selon Javier, Davey Callander, Mac Callander et John sont tous les trois touchés par balle. Jenny Kirk est tuée et [[sean-macguire|Sean MacGuire]] porté disparu. Le gang cache l'argent à Blackwater et fuit vers le nord, dans les montagnes.")},

    # ------------------------------------------------------------------ RDR2
    {"h3": two("Red Dead Redemption 2 (1899)", "Red Dead Redemption 2 (1899)")},

    {"h4": two("Chapter 1: Colter", "Chapitre 1 : Colter"), "chapter": 1},
    {"p": two(
        "The gang reaches the abandoned mining town of Colter, in Ambarino, during a snowstorm. Davey Callander dies of his wounds on arrival. In \"Outlaws from the West\", Dutch and Arthur go looking for supplies and for Micah and John, who had both been sent out to scout. They find Micah, but not John. In \"Enter, Pursued by a Memory\", John has been missing for two days, and Abigail asks Arthur to look for him. Arthur is reluctant. Hosea insists and sends Javier with him. Javier says John was last seen heading up the river, and that John would do the same for him.",
        "Le gang atteint Colter, une ville minière abandonnée de l'Ambarino, en pleine tempête de neige. Davey Callander y meurt de ses blessures dès l'arrivée. Dans \"Outlaws from the West\", Dutch et Arthur partent chercher des vivres, ainsi que Micah et John, envoyés tous les deux en éclaireurs. Ils retrouvent Micah, mais pas John. Dans \"Enter, Pursued by a Memory\", cela fait deux jours que John n'a pas reparu, et Abigail demande à Arthur de partir à sa recherche. Arthur traîne des pieds. Hosea insiste et lui adjoint Javier. Celui-ci rappelle que John a été vu pour la dernière fois en train de remonter la rivière, et assure que John en ferait autant pour lui.")},
    {"p": two(
        "Arthur and Javier follow tracks past an abandoned campfire and across a river, then find John's horse dead in the snow. Javier fires a shot into the air and John answers with calls for help. They find him lying on a ledge, his face freshly torn by wolves. \"Never thought I'd say this, but... it's good to see you, Arthur Morgan\", he says. Arthur carries him on his shoulder. When the wolves return, Arthur hands John to Javier and holds the pack off. On the ride down, Javier mentions the bullet John took in Blackwater, and Arthur jokes that they will need \"a better story for that scar\".",
        "Arthur et Javier suivent des traces, passent devant un feu de camp abandonné et traversent une rivière, puis trouvent le cheval de John mort dans la neige. Javier tire en l'air, et John répond en appelant à l'aide. Ils le découvrent allongé sur une corniche, le visage tout juste lacéré par des loups. \"J'aurais jamais cru dire ça, mais ça fait plaisir de te voir, Arthur Morgan\", lance-t-il. Arthur le porte sur son épaule. Quand les loups reviennent, il confie John à Javier et tient la meute à distance. Pendant la descente, Javier rappelle la balle que John a reçue à Blackwater, et Arthur plaisante : il faudra trouver une meilleure histoire pour expliquer cette cicatrice.")},
    {"p": two(
        "Back in Colter, [[bill-williamson|Bill]] and [[lenny-summers|Lenny Summers]] carry John inside. Abigail thanks his rescuers, then tells John that this is \"a new low, even by your standards\". At the start of \"Who the Hell is Leviticus Cornwall?\", John lies in bed with [[orville-swanson|Reverend Swanson]] beside him. He tells Arthur \"I owe you\". When Dutch announces the train job, John asks to come and tries to get up: \"I was always ugly, Dutch... it's just a scratch.\" Dutch tells him to lie still. Abigail brings Jack to see him, and the couple trade insults in front of the boy. In \"Eastward Bound\", the injured John is helped into the back of a wagon for the move to Horseshoe Overlook.",
        "De retour à Colter, [[bill-williamson|Bill]] et [[lenny-summers|Lenny Summers]] portent John à l'intérieur. Abigail remercie ses sauveteurs, puis lance à John qu'il a touché le fond, même pour lui. Au début de \"Who the Hell is Leviticus Cornwall?\", John est alité, veillé par [[orville-swanson|le révérend Swanson]]. Il dit à Arthur qu'il lui doit une fière chandelle. Quand Dutch annonce l'attaque du train, John demande à venir et tente de se lever : \"J'ai toujours été moche, Dutch... c'est qu'une égratignure.\" Dutch lui ordonne de rester couché. Abigail amène Jack voir son père, et le couple échange des piques devant l'enfant. Dans \"Eastward Bound\", John, toujours blessé, est installé à l'arrière d'un chariot pour le départ vers Horseshoe Overlook.")},

    {"h4": two("Chapter 2: Horseshoe Overlook", "Chapitre 2 : Horseshoe Overlook"), "chapter": 2},
    {"p": two(
        "In \"Paying a Social Call\", [[kieran-duffy|Kieran Duffy]], a captured O'Driscoll, gives up a hideout at Six Point Cabin under threat of torture. Arthur rides there with Bill and John, Kieran leading the way. When Kieran compares the O'Driscolls to the Van der Linde gang, John tells him the two have nothing in common. The three men take out the lookouts quietly before a shootout breaks out. Inside the cabin, Kieran shoots an O'Driscoll who has jumped Arthur. [[colm-odriscoll|Colm O'Driscoll]] is not there. Arthur lets Kieran stay with the gang, and sends Bill and John back to camp with him.",
        "Dans \"Paying a Social Call\", [[kieran-duffy|Kieran Duffy]], un O'Driscoll fait prisonnier, livre sous la menace de la torture une planque à Six Point Cabin. Arthur s'y rend avec Bill et John, Kieran en guide. Quand Kieran compare les O'Driscoll au gang Van der Linde, John lui rétorque que les deux bandes n'ont rien en commun. Les trois hommes éliminent les sentinelles en silence, puis une fusillade éclate. Dans la cabane, Kieran abat un O'Driscoll qui s'est jeté sur Arthur. [[colm-odriscoll|Colm O'Driscoll]] n'est pas là. Arthur accepte que Kieran reste avec le gang, et charge Bill et John de le ramener au camp.")},
    {"p": two(
        "Sean MacGuire is brought back to the gang during this chapter, and a party is held at camp for his return. John gets drunk and argues with Abigail. The player, as Arthur, may also see him make drunken advances to [[karen-jones|Karen Jones]], who says no because of Abigail. In \"Pouring Forth Oil I\", John brings Arthur a lead that came from [[mary-beth-gaskill|Mary-Beth Gaskill]] through Uncle: a train full of wealthy passengers crossing Scarlett Meadows, south of the state line. Arthur hesitates, because stopping a train is difficult.",
        "Sean MacGuire est ramené au gang pendant ce chapitre, et une fête est organisée au camp pour son retour. John s'enivre et se dispute avec Abigail. Le joueur, dans la peau d'Arthur, peut aussi le voir faire des avances éméchées à [[karen-jones|Karen Jones]], qui refuse à cause d'Abigail. Dans \"Pouring Forth Oil I\", John apporte à Arthur un tuyau de [[mary-beth-gaskill|Mary-Beth Gaskill]], transmis par Uncle : un train rempli de passagers fortunés traverse Scarlett Meadows, juste au sud de la frontière de l'État. Arthur hésite, car arrêter un train n'a rien de simple.")},
    {"p": two(
        "John has a solution: park a wagon full of oil across the tracks, so that the driver must stop or burn. Arthur calls the idea \"kinda brilliant\", then teases him about the wolf eating half his brain. John goes to Valentine for supplies (and on an errand for Abigail), while Arthur steals an oil wagon from Cornwall Kerosene & Tar in \"Pouring Forth Oil II\". They hide it near a burnt-out shack north of Dewberry Creek. If the player skips that mission, John gets the wagon himself. In \"Pouring Forth Oil III\", Arthur suggests a third man, and John goes to fetch Charles.",
        "John a une solution : garer en travers des voies un chariot rempli de pétrole, pour que le conducteur soit forcé de s'arrêter ou de brûler. Arthur trouve l'idée \"presque géniale\", avant de le chambrer sur le loup qui lui aurait mangé la moitié du cerveau. John part à Valentine chercher le matériel (et faire une course pour Abigail), pendant qu'Arthur vole un chariot-citerne chez Cornwall Kerosene & Tar dans \"Pouring Forth Oil II\". Ils le cachent près d'une cabane brûlée, au nord de Dewberry Creek. Si le joueur laisse de côté cette mission, c'est John qui récupère lui-même le chariot. Dans \"Pouring Forth Oil III\", Arthur propose de prendre un troisième homme, et John va chercher Charles.")},
    {"p": two(
        "In \"Pouring Forth Oil IV\", Sean has joined Arthur at the wagon despite John telling him he was not coming. Sean mocks John for lying in bed \"playing sick\" and fondling his new scar. That night, the four men park the wagon on a crossing at the border between New Hanover and Lemoyne. John reminds the others that the passengers are innocent and that nobody needs to die. Charles knocks out the engineer. John works the passenger cars with a loot bag while Arthur backs him up, then sends Arthur ahead to help Sean in the baggage car. Lawmen arrive quickly. After the escape, John asks whether it was a setup, then says he will head to Valentine to \"get something started\".",
        "Dans \"Pouring Forth Oil IV\", Sean a rejoint Arthur près du chariot, alors que John lui avait dit qu'il ne viendrait pas. Sean se moque de John, resté au lit à \"jouer les malades\" en caressant sa nouvelle cicatrice. À la nuit tombée, les quatre hommes garent le chariot sur un passage à niveau, à la limite entre le New Hanover et le Lemoyne. John rappelle aux autres que les passagers sont innocents et que personne n'a besoin de mourir. Charles assomme le mécanicien. John fait le tour des voitures de passagers avec un sac à butin, Arthur en soutien, puis envoie Arthur aider Sean dans le fourgon à bagages. Les forces de l'ordre arrivent très vite. Une fois à l'abri, John se demande s'ils ne sont pas tombés dans un piège, puis annonce qu'il part à Valentine monter un autre coup.")},
    {"p": two(
        "That plan is \"The Sheep and the Goats\". John meets Arthur near the Valentine auction yard. Arthur buys a rifle at the gun store because John is not on good terms with the gunsmith. On the ride, Arthur tells John he cannot \"be two people at once\" with Jack. John's plan is to scatter the hands driving a flock from Emerald Ranch, then sell the sheep at auction. Arthur fires at the ground from a cliff, and the two men herd the animals into town. When the auctioneer, Morris Peyton, becomes suspicious, John talks his cut down from 25 to 18 percent.",
        "Ce coup, c'est \"The Sheep and the Goats\". John retrouve Arthur près du parc aux enchères de Valentine. Arthur achète un fusil à l'armurerie, John étant en froid avec l'armurier. En chemin, Arthur lui reproche de vouloir être deux hommes à la fois avec Jack. Le plan de John consiste à disperser les ouvriers qui convoient un troupeau d'Emerald Ranch, puis à vendre les moutons aux enchères. Depuis une falaise, Arthur tire dans le sol, et les deux hommes mènent les bêtes jusqu'en ville. Quand le commissaire-priseur, Morris Peyton, commence à se méfier, John négocie et fait baisser sa commission de 25 à 18 %.")},
    {"p": two(
        "John and Arthur then join Dutch and [[leopold-strauss|Leopold Strauss]] at Keane's Saloon. Dutch sends John and Strauss to collect the money for the sheep. [[leviticus-cornwall|Leviticus Cornwall]] arrives with armed men, has John and Strauss held at gunpoint outside, and calls for Dutch. While Dutch talks, Arthur draws and frees the two hostages. The gang shoots its way out of Valentine, and Dutch decides to move camp again.",
        "John et Arthur rejoignent ensuite Dutch et [[leopold-strauss|Leopold Strauss]] au Keane's Saloon. Dutch envoie John et Strauss récupérer l'argent des moutons. [[leviticus-cornwall|Leviticus Cornwall]] arrive avec des hommes armés, fait tenir John et Strauss en joue devant le saloon et réclame Dutch. Pendant que Dutch parlemente, Arthur dégaine et libère les deux otages. Le gang sort de Valentine les armes à la main, et Dutch décide de déplacer une nouvelle fois le camp.")},

    {"h4": two("Chapter 3: Clemens Point", "Chapitre 3 : Clemens Point"), "chapter": 3},
    {"p": two(
        "From the new camp at Clemens Point, near Rhodes, the gang plays the feuding Gray and Braithwaite families against each other. At the start of \"Advertising, The New American Art\", John waits with Hosea at a stash of stolen moonshine they plan to sell back to the Braithwaites. Dutch has asked John to look into something else, so he hands his place to Arthur and leaves to scout the Braithwaites' prized race horses. In \"Horse Flesh for Dinner\", John, Arthur and Javier meet Tavish Gray at the Caliga Hall stables. Tavish wants the horses stolen and says they will sell for 5,000 dollars.",
        "Depuis le nouveau camp de Clemens Point, près de Rhodes, le gang monte les familles Gray et Braithwaite, en guerre ouverte, l'une contre l'autre. Au début de \"Advertising, The New American Art\", John attend avec Hosea près d'une réserve d'alcool de contrebande volé, que les deux hommes veulent revendre aux Braithwaite. Dutch a confié une autre affaire à John, qui cède donc sa place à Arthur et part se renseigner sur les chevaux de course des Braithwaite. Dans \"Horse Flesh for Dinner\", John, Arthur et Javier retrouvent Tavish Gray aux écuries de Caliga Hall. Tavish veut qu'ils volent ces chevaux, qui se vendraient selon lui 5 000 dollars.")},
    {"p": two(
        "At Braithwaite Manor, a guard stops the three men. John tells him they have come to make a large investment in the stables, and they are let through. Arthur deals with the stablehand, and Javier ties the three horses together. John leads the escape across Scarlett Meadows while Arthur covers the rear. At Clemens Cove, the horse fence Clay Davies tells them the horses are only worth 700 dollars, a fraction of what they were promised. The three men sell anyway.",
        "À Braithwaite Manor, un garde arrête les trois hommes. John lui explique qu'ils viennent investir une grosse somme dans les écuries, et on les laisse passer. Arthur s'occupe du palefrenier, et Javier attache les trois chevaux ensemble. John ouvre la fuite à travers Scarlett Meadows, Arthur couvrant l'arrière. À Clemens Cove, le receleur Clay Davies leur annonce que les bêtes ne valent que 700 dollars, une fraction de la somme promise. Les trois hommes vendent quand même.")},
    {"p": two(
        "The scheme falls apart. Sean is killed in an ambush in Rhodes, and Jack disappears from camp. In \"Blood Feuds, Ancient and Modern\", the gang concludes that the Braithwaites took the boy in revenge for the stolen horses. John rides to Braithwaite Manor with Dutch, Arthur, Hosea, Charles, Bill, Javier and Lenny. The gang kills the Braithwaite men and sets the house on fire. Catherine Braithwaite, the matriarch, finally reveals that her sons handed Jack over to [[angelo-bronte|Angelo Bronte]], a crime boss in Saint Denis.",
        "Le plan s'effondre. Sean est tué dans une embuscade à Rhodes, et Jack disparaît du camp. Dans \"Blood Feuds, Ancient and Modern\", le gang en conclut que les Braithwaite ont enlevé l'enfant pour se venger du vol des chevaux. John part pour Braithwaite Manor avec Dutch, Arthur, Hosea, Charles, Bill, Javier et Lenny. Le gang abat les hommes de la famille et met le feu au manoir. Catherine Braithwaite, la matriarche, finit par avouer que ses fils ont livré Jack à [[angelo-bronte|Angelo Bronte]], un parrain du crime de Saint-Denis.")},
    {"p": two(
        "The next morning, in \"The Battle of Shady Belle\", Dutch and Hosea try to reassure John about Jack. Pinkerton agents [[andrew-milton|Andrew Milton]] and [[edgar-ross|Edgar Ross]] then ride into Clemens Point. Milton offers the gang amnesty in exchange for Dutch. Nobody accepts, and Milton leaves promising to come back with fifty men. Dutch sends John and Arthur to Shady Belle, an old plantation house in the bayou found earlier by Lenny. On the way, John blames the feud scheme for bringing the Pinkertons back, and says he has been a bad father to Jack. The two men kill the Lemoyne Raiders occupying the house and throw the bodies into the swamp. John then rides back to guide the gang to its new camp.",
        "Le lendemain matin, dans \"The Battle of Shady Belle\", Dutch et Hosea tentent de rassurer John au sujet de Jack. Les agents de la Pinkerton [[andrew-milton|Andrew Milton]] et [[edgar-ross|Edgar Ross]] débarquent alors à Clemens Point. Milton propose l'amnistie au gang en échange de Dutch. Personne n'accepte, et Milton repart en promettant de revenir avec cinquante hommes. Dutch envoie John et Arthur à Shady Belle, une vieille maison de plantation dans le bayou repérée plus tôt par Lenny. En chemin, John accuse le coup monté contre les deux familles d'avoir ramené la Pinkerton, et reconnaît avoir été un mauvais père pour Jack. Les deux hommes abattent les Lemoyne Raiders qui occupent la maison et jettent les corps dans le marais. John repart ensuite guider le gang jusqu'au nouveau camp.")},

    {"h4": two("Chapter 4: Saint Denis", "Chapitre 4 : Saint-Denis"), "chapter": 4},
    {"p": two(
        "In \"Angelo Bronte, A Man of Honor\", John, Arthur and Dutch go to Bronte's mansion in Saint Denis. Dutch has a guard fetch Bronte, presents the gang as \"simple, country folk\" and gains the crime boss's sympathy. Bronte asks for a favor in return for Jack: clearing grave robbers out of the Saint Denis cemetery. On the way to the cemetery, Arthur tells John he kept his head well in front of Bronte. John answers that he would not trust the man an inch, and comes back to his failings as a father. The two men kill the grave robbers, find their stash and slip past the police who arrive. Back at the mansion, Dutch is waiting with Jack. The boy says he was treated well, and John is relieved.",
        "Dans \"Angelo Bronte, A Man of Honor\", John, Arthur et Dutch se rendent au manoir de Bronte, à Saint-Denis. Dutch fait appeler Bronte par un garde, présente le gang comme de \"simples gens de la campagne\" et gagne la sympathie du parrain. En échange de Jack, Bronte demande un service : débarrasser le cimetière de Saint-Denis de ses pilleurs de tombes. En route vers le cimetière, Arthur trouve que John a bien gardé son sang-froid face à Bronte. John répond qu'il ne lui fait aucune confiance, et revient sur ses manquements de père. Les deux hommes abattent les pilleurs, trouvent leur butin et échappent à la police arrivée sur place. De retour au manoir, Dutch les attend avec Jack. L'enfant raconte qu'il a été bien traité, et John est soulagé.")},
    {"p": two(
        "The gang throws a party at Shady Belle for Jack's return. That night, John offers to share his room with Abigail and Jack, an offer she did not expect and welcomes. Dutch, in camp conversations during the chapter, presses John on where his loyalty lies: the gang must come first. In a later exchange he calls him ungrateful. In \"Horsemen, Apocalypses\", Kieran, who disappeared during the party, is sent back into camp dead on a horse, and the O'Driscolls attack. Dutch posts John, Charles and Arthur at the house to defend it. After the fight, John and Arthur clear away the bodies.",
        "Le gang organise une fête à Shady Belle pour le retour de Jack. Ce soir-là, John propose à Abigail de partager sa chambre avec Jack, ce qu'elle n'attendait pas et accueille avec joie. Au fil des conversations de camp du chapitre, Dutch somme John de choisir son camp : le gang d'abord. Une autre fois, il le traite d'ingrat. Dans \"Horsemen, Apocalypses\", Kieran, disparu pendant la fête, est renvoyé au camp sur un cheval, mort, et les O'Driscoll attaquent. Dutch poste John, Charles et Arthur pour défendre la maison. Après le combat, John et Arthur évacuent les corps.")},
    {"p": two(
        "Bronte's tip on a trolley station robbery turns out to be a setup. In \"Revenge is a Dish Best Eaten\", John, Dutch, Arthur, Bill and Lenny land by boat near Bronte's mansion and storm it. John finds Bronte upstairs and knocks him out, and the gang carries him to the boat under police fire. On the water, Bronte insults Dutch and offers money to any gang member who will kill him. Dutch drowns Bronte and feeds the body to an alligator, to the shock of Arthur and John.",
        "Le tuyau de Bronte sur une station de tramway se révèle être un piège. Dans \"Revenge is a Dish Best Eaten\", John, Dutch, Arthur, Bill et Lenny débarquent en barque près du manoir de Bronte et le prennent d'assaut. John trouve Bronte à l'étage et l'assomme, puis le gang l'emmène jusqu'à la barque sous le feu de la police. Sur l'eau, Bronte insulte Dutch et promet de l'argent à quiconque, dans le gang, le tuera. Dutch noie Bronte et jette le corps à un alligator, sous le regard choqué d'Arthur et de John.")},
    {"p": two(
        "\"Banking, The Old American Art\" is meant to be the last big job: robbing the Lemoyne National Bank in Saint Denis. John is inside the bank with Dutch, Arthur and the others when the Pinkertons surround it. Outside, Milton holds Hosea hostage and kills him when Dutch refuses to give himself up. The gang blows a hole in a wall and escapes over the rooftops. Lenny is killed. John is arrested by the Pinkertons and sent to Sisika Penitentiary. Later, John tells Arthur that Dutch saw him being taken and did nothing to stop it.",
        "\"Banking, The Old American Art\" doit être le dernier grand coup : le braquage de la Lemoyne National Bank, à Saint-Denis. John est dans la banque avec Dutch, Arthur et les autres quand la Pinkerton encercle le bâtiment. Dehors, Milton tient Hosea en otage et l'abat quand Dutch refuse de se rendre. Le gang fait sauter un mur et s'enfuit par les toits. Lenny est tué. John est arrêté par la Pinkerton et envoyé au pénitencier de Sisika. Plus tard, John dira à Arthur que Dutch l'a vu se faire prendre sans rien faire pour l'en empêcher.")},

    {"h4": two("Chapter 5: Guarma (John in Sisika)", "Chapitre 5 : Guarma (John à Sisika)"), "chapter": 5},
    {"p": two(
        "John does not appear in chapter 5. While Dutch, Arthur, Bill, Javier and Micah escape Saint Denis by ship and are wrecked on the island of Guarma, John is held at Sisika Penitentiary, on an island in the Lannahechee River off the coast of Lemoyne. He works in the fields there as part of a prison work gang. Abigail stays on the mainland with Jack and the rest of the gang, at Lakay. In \"Fleeting Joy\", the last mission of the chapter, the Guarma group rejoins them, and Abigail tells Arthur there is talk of hanging John. Dutch refuses to make his rescue a priority. The Pinkertons then raid Lakay, and the gang moves to Beaver Hollow.",
        "John n'apparaît pas au chapitre 5. Pendant que Dutch, Arthur, Bill, Javier et Micah quittent Saint-Denis en bateau et font naufrage sur l'île de Guarma, John est détenu au pénitencier de Sisika, sur une île de la Lannahechee, au large du Lemoyne. Il y travaille aux champs, au sein d'une équipe de forçats. Abigail reste sur le continent avec Jack et le reste du gang, à Lakay. Dans \"Fleeting Joy\", dernière mission du chapitre, les rescapés de Guarma les rejoignent, et Abigail apprend à Arthur qu'il est question de pendre John. Dutch refuse d'en faire une priorité. La Pinkerton donne ensuite l'assaut à Lakay, et le gang se replie à Beaver Hollow.")},

    {"h4": two("Chapter 6: Beaver Hollow", "Chapitre 6 : Beaver Hollow"), "chapter": 6},
    {"p": two(
        "Arthur and [[sadie-adler|Sadie Adler]] decide to free John anyway. In \"A Fork in the Road\", a mission on the seam between chapters 5 and 6, Arthur collapses in Saint Denis and is diagnosed with tuberculosis; at high honor, one of the voices he remembers afterwards is John's (\"Sometimes I wonder if things are ever the way we remember 'em\"). In \"Icarus and Friends\", Arthur flies over Sisika in Arturo Bullard's hot air balloon and spots a prisoner in the fields who is almost certainly John. Guards open fire on the balloon. Sadie then proposes that the two of them get John out themselves.",
        "Arthur et [[sadie-adler|Sadie Adler]] décident de libérer John malgré tout. Dans \"A Fork in the Road\", mission à cheval entre les chapitres 5 et 6, Arthur s'effondre à Saint-Denis et apprend qu'il a la tuberculose ; avec un honneur élevé, la voix de John figure parmi celles qui lui reviennent ensuite (\"Sometimes I wonder if things are ever the way we remember 'em\"). Dans \"Icarus and Friends\", Arthur survole Sisika à bord de la montgolfière d'Arturo Bullard et repère dans les champs un prisonnier qui est presque à coup sûr John. Les gardiens tirent sur le ballon. Sadie propose ensuite qu'ils aillent tous les deux le chercher.")},
    {"p": two(
        "In \"Visiting Hours\", Abigail asks to come along at Copperhead Landing; Arthur and Sadie refuse. They row to the island, take a guard named Milliken hostage and demand John at the main gate. The guards bring John out, Arthur releases Milliken, and the three fight their way back to the boat. On the way back, Arthur tells John that Dutch did not want him rescued. John replies that Dutch watched him get taken by the Pinkertons and did nothing. At Beaver Hollow, Dutch is displeased to see him: he says he had a plan, and that the law will now come for all of them.",
        "Dans \"Visiting Hours\", à Copperhead Landing, Abigail demande à les accompagner ; Arthur et Sadie refusent. Ils rejoignent l'île en barque, prennent en otage un gardien nommé Milliken et exigent qu'on leur rende John à l'entrée principale. Les gardiens font sortir John, Arthur relâche Milliken, et le trio regagne la barque sous les balles. Sur le chemin du retour, Arthur explique à John que Dutch ne voulait pas qu'on le libère. John répond que Dutch l'a regardé se faire arrêter par la Pinkerton sans bouger. À Beaver Hollow, Dutch accueille mal son retour : il affirme qu'il avait un plan, et que la loi va désormais s'en prendre à eux tous.")},
    {"p": two(
        "Dutch grows more suspicious, and Micah encourages it. Bill and Javier also come to doubt John's loyalty. Dutch accuses John, in camp, of speaking against him, and admits that he would have left him in Sisika. At the end of \"The Delights of Van Horn\", John waits with Micah near Beaver Hollow, and Micah tells him to take the stolen army dynamite to Bacchus Bridge. In \"The Bridge to Nowhere\", John says Dutch could have saved him at the bank and chose not to. Arthur tells him to take Abigail and Jack, leave, and not look back.",
        "Dutch devient de plus en plus soupçonneux, et Micah l'y pousse. Bill et Javier se mettent eux aussi à douter de la loyauté de John. Au camp, Dutch accuse John de le critiquer en son absence, et reconnaît qu'il l'aurait bien laissé à Sisika. À la fin de \"The Delights of Van Horn\", John attend avec Micah près de Beaver Hollow, et Micah le charge d'apporter la dynamite volée à l'armée jusqu'au pont de Bacchus. Dans \"The Bridge to Nowhere\", John affirme que Dutch aurait pu le sauver à la banque et ne l'a pas fait. Arthur lui conseille de prendre Abigail et Jack, de partir et de ne pas se retourner.")},
    {"p": two(
        "The two men push the crates out on a handcar, fix the charges under the bridge and race a train back to the end of the span before Arthur triggers the detonator. The middle of the bridge falls into the river. John says he does not understand Dutch's plan, and that he feels he no longer knows him. Arthur repeats that loyalty has done neither of them any good, and that John will need money to leave. John says Abigail thinks she knows where Dutch has hidden the gang's money. Arthur tells him to come back to him when she is sure.",
        "Les deux hommes poussent les caisses sur une draisine, fixent les charges sous le tablier et regagnent le bout du pont devant un train lancé à pleine vitesse, avant qu'Arthur n'actionne le détonateur. La partie centrale du pont s'effondre dans la rivière. John avoue qu'il ne comprend pas le plan de Dutch, et qu'il a l'impression de ne plus le connaître. Arthur répète que la loyauté ne leur a rien apporté, et qu'il faudra de l'argent à John pour partir. John explique qu'Abigail pense savoir où Dutch a caché l'argent du gang. Arthur lui demande de revenir le voir quand elle en sera certaine.")},
    {"p": two(
        "In \"My Last Boy\", Eagle Flies rides into Beaver Hollow to raise a war party against the U.S. Army, and the gang, John included, rides to the oil fields to fight alongside the Wapiti warriors. Micah, Cleet and Joe stay out of it. At the start of \"Our Best Selves\", Arthur agrees to take part in a final robbery of an army payroll train on one condition: that John and his family be allowed to leave. Dutch appears to accept. On the way, Arthur rides with John to collect dynamite John has hidden. Arthur promises to do all he can to get the family to safety, and John thanks him for always looking out for him.",
        "Dans \"My Last Boy\", Eagle Flies débarque à Beaver Hollow pour lever une troupe contre l'armée américaine, et le gang, John compris, part combattre aux côtés des guerriers wapitis dans les champs pétrolifères. Micah, Cleet et Joe restent en dehors. Au début de \"Our Best Selves\", Arthur accepte de participer à un dernier coup, l'attaque d'un train transportant la solde de l'armée, à une condition : que John et sa famille puissent partir. Dutch semble accepter. En chemin, Arthur accompagne John récupérer de la dynamite que celui-ci a cachée. Arthur promet de tout faire pour mettre la famille à l'abri, et John le remercie de toujours veiller sur lui.")},
    {"p": two(
        "The train does not stop as planned, and the gang boards it at full speed. When a carriage catches fire, John jumps onto the back of Bill's horse to get past it. On the next car, John works on uncoupling the burning carriage, is shot in the shoulder and falls from the train. Dutch says he will go back for him and rides off with Javier, Micah and Joe. After the robbery, Dutch and Micah tell Arthur that John \"didn't make it\". The gang returns to camp believing him dead.",
        "Le train ne s'arrête pas comme prévu, et le gang l'aborde en pleine course. Quand une voiture prend feu, John saute en croupe derrière Bill pour la dépasser. Sur le wagon suivant, John tente de détacher la voiture en flammes, prend une balle dans l'épaule et tombe du train. Dutch annonce qu'il retourne le chercher et repart avec Javier, Micah et Joe. Après le braquage, Dutch et Micah annoncent à Arthur que John n'a pas survécu. Le gang rentre au camp en le croyant mort.")},
    {"p": two(
        "In the final chapter mission, \"Red Dead Redemption\", Milton captures Abigail at Van Horn. Micah argues against rescuing her: \"Without John, she's just bait.\" Arthur and Sadie go after her anyway. Before he dies, Milton tells Arthur that Micah has been informing for the Pinkertons. Arthur, believing John dead, tells Abigail that John loved her and Jack. Sadie takes Abigail to Copperhead Landing, where [[tilly-jackson|Tilly Jackson]] is hiding with Jack. Abigail tells Arthur where Dutch's money chest is hidden in the caves under the camp, and gives him the key.",
        "Dans la dernière mission du chapitre, \"Red Dead Redemption\", Milton capture Abigail à Van Horn. Micah s'oppose à son sauvetage : sans John, elle ne sert plus que d'appât, explique-t-il. Arthur et Sadie partent quand même la délivrer. Avant de mourir, Milton révèle à Arthur que Micah renseigne la Pinkerton. Arthur, qui croit John mort, assure à Abigail que John les aimait, elle et Jack. Sadie conduit Abigail à Copperhead Landing, où [[tilly-jackson|Tilly Jackson]] se cache avec Jack. Abigail indique à Arthur où se trouve le coffre de Dutch, dans les grottes sous le camp, et lui en remet la clé.")},
    {"p": two(
        "Back at Beaver Hollow, Arthur accuses Micah in front of Dutch. During the standoff, John walks into camp, wounded, and shouts at Dutch: \"You left me... you left me to die!\" Dutch answers that he had no choice. John and [[susan-grimshaw|Susan Grimshaw]] side with Arthur. Susan aims a shotgun at Micah; when Javier warns that Pinkertons are coming, Micah shoots her. Dutch demands to know who is with him and who is betraying him. Bill, Javier, Micah, Cleet and Joe stay with Dutch and turn their guns on Arthur and John. The Pinkertons open fire before anyone else shoots, and the camp scatters.",
        "De retour à Beaver Hollow, Arthur accuse Micah devant Dutch. En pleine confrontation, John entre dans le camp, blessé, et apostrophe Dutch : \"Tu m'as laissé... tu m'as laissé crever !\" Dutch répond qu'il n'avait pas le choix. John et [[susan-grimshaw|Susan Grimshaw]] se rangent du côté d'Arthur. Susan braque un fusil sur Micah ; quand Javier prévient que la Pinkerton arrive, Micah l'abat. Dutch exige de savoir qui est avec lui et qui le trahit. Bill, Javier, Micah, Cleet et Joe restent aux côtés de Dutch et pointent leurs armes sur Arthur et John. La Pinkerton ouvre le feu avant que quiconque ne tire, et le camp se disperse.")},
    {"p": two(
        "Edgar Ross orders his agents to take Arthur and John dead or alive. The two men escape through the caves under the camp. On the way, Arthur tells John that Micah was the informant, as Milton revealed before dying (\"We should've killed him months ago\", John replies); when Arthur mentions the money hidden in the caves, John says there is no time. Once outside, Arthur says that Abigail and Jack are safe with Sadie at Copperhead Landing. John thanks him and calls him \"brother\". The pair outrun Dutch's men, but Pinkerton agents shoot their horses from under them. Surrounded by Pinkertons, Arthur has a choice to make.",
        "Edgar Ross ordonne à ses agents de prendre Arthur et John morts ou vifs. Les deux hommes s'échappent par les grottes sous le camp. En chemin, Arthur apprend à John que Micah était l'informateur, comme Milton l'a révélé avant de mourir (\"On aurait dû le tuer il y a des mois\", répond John) ; quand Arthur évoque l'argent caché dans les grottes, John répond qu'ils n'ont pas le temps. Une fois dehors, Arthur lui dit qu'Abigail et Jack sont en sécurité avec Sadie à Copperhead Landing. John le remercie et l'appelle \"mon frère\". Les deux fuyards distancent les hommes de Dutch, mais des agents de la Pinkerton abattent leurs chevaux. Cerné par la Pinkerton, Arthur doit faire un choix.")},
    {"p": two(
        "If Arthur goes back for the money, John refuses to follow: \"I head down there, I'm dead in five minutes. I got a family, that's more important.\" Arthur gives him his satchel and puts his hat on John's head, and they part. If Arthur helps John escape, the two fight their way up the mountain until Arthur, exhausted by his illness, stops. He gives John his hat and satchel, tells him to go to his family and stays behind to hold off the Pinkertons. \"You're my brother\", John tells him. \"I know\", Arthur answers. In both versions, John gets away and Arthur does not survive.",
        "Si Arthur retourne chercher l'argent, John refuse de le suivre : s'il redescend, il est mort en cinq minutes, et sa famille passe avant. Arthur lui donne sa sacoche, lui pose son chapeau sur la tête, et leurs chemins se séparent. Si Arthur aide John à fuir, les deux hommes se battent jusqu'en haut de la montagne, où Arthur, épuisé par la maladie, s'arrête. Il donne à John son chapeau et sa sacoche, lui ordonne de rejoindre sa famille et reste en arrière pour retenir la Pinkerton. \"T'es mon frère\", lui dit John. \"Je sais\", répond Arthur. Dans les deux versions, John s'en sort et Arthur ne survit pas.")},
    {"p": two(
        "John reaches Copperhead Landing, where Abigail and Jack are waiting with Sadie and Tilly. If Arthur helped him escape, Arthur tells Dutch at the end of his fight with Micah: \"John made it. He's the only one.\" In 1907, during \"Gainful Employment\", Sadie and John refer to an agreement made after the gang's collapse: to kill Micah if they ever found him. \"I know what we said we'd do. That ain't changed\", John tells her. They keep that promise on Mount Hagen, eight years after Beaver Hollow.",
        "John rejoint Copperhead Landing, où l'attendent Abigail, Jack, Sadie et Tilly. Si Arthur l'a aidé à fuir, il lance à Dutch au terme de son combat contre Micah : \"John s'en est sorti. C'est le seul.\" En 1907, dans \"Gainful Employment\", Sadie et John évoquent un engagement pris après l'effondrement du gang : tuer Micah s'ils le retrouvent un jour. \"Je sais ce qu'on a dit qu'on ferait. Ça n'a pas changé\", lui assure John. Ils tiendront parole au mont Hagen, huit ans après Beaver Hollow.")},
]
