def two(en, fr): return {"en": en, "fr": fr}

# ============================================================== UNDEAD NIGHTMARE
BLOCKS_UN = [
    {"h3": two("Undead Nightmare (outside the canon)", "Undead Nightmare (hors continuité)")},
    {"p": two("Undead Nightmare is a single-player expansion for Red Dead Redemption, released in October 2010. Its events are not part of the series' canon and have no effect on the main story. The expansion is set at a point where John, Abigail, Jack and Uncle are all alive at Beecher's Hope: after \"The Outlaw's Return\" and before \"The Last Enemy That Shall Be Destroyed\". A plague raises the dead across the whole map. John crosses West Elizabeth, New Austin and Nuevo Paraíso in search of a cure. The game splits its content into eight main missions and six side missions, several of them given by characters from the main game.",
              "Undead Nightmare est une extension solo de Red Dead Redemption, sortie en octobre 2010. Ses événements ne font pas partie de la continuité officielle et ne changent rien à l'histoire principale. L'action se situe à un moment où John, Abigail, Jack et Uncle vivent tous à Beecher's Hope : après \"The Outlaw's Return\" et avant \"The Last Enemy That Shall Be Destroyed\". Une épidémie relève les morts sur toute la carte. John traverse West Elizabeth, le New Austin et le Nuevo Paraíso en quête d'un remède. Le contenu se répartit en huit missions principales et six missions secondaires, dont plusieurs confiées par des personnages du jeu de base.")},

    {"h4": two("West Elizabeth", "West Elizabeth")},
    {"p": two("In \"Love in the Time of Plague\", John comes home to Beecher's Hope on a stormy night. Uncle is missing: Abigail thought he was out with John. The family eats without him. After dinner, Jack talks about the book he is reading, a story of the ancient Aztecs and a curse that brings a plague; Abigail calls it nonsense. During the night, Uncle walks into the bedroom covered in blood and goes for John, who hits him with a lamp and runs to fetch his gun in his union suit. Uncle gets up, chases Abigail outside and bites her. John shoots him in the head. Abigail then bites Jack, and both turn. John lassoes and hogties his wife and son, leaves them in the house and rides to Blackwater for help.",
              "Dans \"Love in the Time of Plague\", John rentre à Beecher's Hope par une nuit d'orage. Uncle n'est pas là : Abigail le croyait avec John. La famille dîne sans lui. Après le repas, Jack parle du livre qu'il lit, une histoire d'anciens Aztèques et d'une malédiction qui déclenche une épidémie ; Abigail n'y voit que des bêtises. Dans la nuit, Uncle entre dans la chambre couvert de sang et se jette sur John, qui l'assomme avec une lampe et court chercher son arme, en sous-vêtements. Uncle se relève, poursuit Abigail dehors et la mord. John l'abat d'une balle dans la tête. Abigail mord ensuite Jack, et tous deux se transforment. John les attrape au lasso, les ligote, les laisse dans la maison et part chercher de l'aide à Blackwater.")},
    {"p": two("\"Curious Tales from Blackwater\" opens in an empty town. John meets [[harold-macdougal|Harold MacDougal]], back from Yale to continue his research, who admits he has no idea what is going on. When the professor goes down an alley for his medical bag, an undead [[nastas|Nastas]] attacks and devours him. John must kill or avoid both of them. The niece of Mordecai Robbard sends him to the Blackwater cemetery, where he burns the coffins and kills the undead Robbard; the player receives the Repeater Carbine. Back in town, John defends the survivors. A family on the roof of the Auto Livery only argues among themselves. A second group gives him two leads on the origin of the plague: a \"snake oil merchant\" and a \"freak with a glass eye\".",
              "\"Curious Tales from Blackwater\" s'ouvre sur une ville déserte. John y croise [[harold-macdougal|Harold MacDougal]], revenu de Yale pour poursuivre ses recherches, qui avoue ne rien comprendre à la situation. Quand le professeur s'engage dans une ruelle pour récupérer sa sacoche de médecin, [[nastas|Nastas]], devenu mort-vivant, se jette sur lui et le dévore. John doit les tuer ou les éviter tous les deux. La nièce de Mordecai Robbard l'envoie au cimetière de Blackwater, où il brûle les cercueils et abat Robbard, sorti de sa tombe ; le joueur obtient la Repeater Carbine. De retour en ville, John défend les survivants. Une famille réfugiée sur le toit de l'Auto Livery ne fait que se disputer. Un second groupe lui donne deux pistes sur l'origine du fléau : un \"marchand de remèdes miracles\" et un \"phénomène à l'œil de verre\".")},
    {"p": two("The side mission \"Birth of the Conservation Movement\" starts at Tanner's Reach. A frightened frontiersman fires blindly into the woods and tells John he has seen Sasquatches. He asks John to hunt them in Tall Trees. After six kills, John finds the last of the creatures, which speaks to him: its family is dead and it is now alone. It asks John to end its life. The player chooses whether to shoot it or leave it.",
              "La mission secondaire \"Birth of the Conservation Movement\" démarre à Tanner's Reach. Un trappeur paniqué tire au hasard dans les bois et affirme à John avoir vu des Sasquatch. Il lui demande de les chasser à Tall Trees. Après six bêtes abattues, John trouve la dernière créature, qui lui parle : sa famille est morte et elle est désormais seule. Elle lui demande de mettre fin à ses jours. Le joueur choisit de l'abattre ou de l'épargner.")},

    {"h4": two("New Austin", "New Austin")},
    {"p": two("John follows the glass-eye lead in \"Get Back in That Hole, Partner\". At The Old Bacchus Place, [[seth-briars|Seth Briars]] is playing poker with his friend Moses Forth, now one of the undead. Seth plays down the plague (\"It ain't nothin'\"). John reports what people in Blackwater are saying about the glass eye he dug up. Seth loses his temper and urges Moses to attack, but the undead man does not move. He then tells John to clear three cemeteries: Coot's Chapel, Odd Fellow's Rest and Tumbleweed. When John comes back, Seth says the cause has something to do with the Aztecs, \"or, or Incas\", and that the answer is in Mexico.",
              "John suit la piste de l'œil de verre dans \"Get Back in That Hole, Partner\". À The Old Bacchus Place, [[seth-briars|Seth Briars]] joue au poker avec son ami Moses Forth, devenu mort-vivant. Seth minimise l'épidémie (\"It ain't nothin'\"). Quand John rapporte que Blackwater accuse l'œil de verre qu'il a déterré, Seth s'emporte et tente, sans succès, de lancer Moses sur lui. Il l'envoie ensuite nettoyer trois cimetières : Coot's Chapel, Odd Fellow's Rest et Tumbleweed. Au retour de John, Seth explique que tout cela a un rapport avec les Aztèques, \"ou les Incas\", et que la réponse se trouve au Mexique.")},
    {"p": two("The other lead points to [[nigel-west-dickens|Nigel West Dickens]]. In \"A Cure for Most of What Ails You\", John finds him at Fort Mercer selling a tonic to the refugees for 100 gold coins and forces him to hand it out for free. Dickens claims the undead will not approach anyone who uses it. A man walks out to test it and is torn apart. Dickens gives John the tonic to use as bait, then sends him to gather five Desert Sage and five Violet Snowdrop, in Gaptooth Ridge and Tall Trees. With the plants he makes a phosphorus coating for John's ammunition. He then asks for old parts stored at Riley's Charge and uses them, at Benedict Point, to build a Blunderbuss, which he presents as the right weapon against the undead.",
              "L'autre piste mène à [[nigel-west-dickens|Nigel West Dickens]]. Dans \"A Cure for Most of What Ails You\", John le trouve à Fort Mercer en train de vendre un tonique aux réfugiés pour 100 pièces d'or, et l'oblige à le distribuer gratuitement. Dickens affirme que les morts-vivants n'approchent pas ceux qui en boivent. Un homme sort pour vérifier et se fait déchiqueter. Dickens confie le tonique à John pour s'en servir comme appât, puis l'envoie chercher cinq Desert Sage et cinq Violet Snowdrop, à Gaptooth Ridge et à Tall Trees. Avec ces plantes, il prépare un enrobage au phosphore pour les munitions de John. Il réclame ensuite de vieilles pièces entreposées à Riley's Charge et s'en sert, à Benedict Point, pour fabriquer un tromblon, qu'il présente comme l'arme idéale contre les morts-vivants.")},
    {"p": two("Four side missions take place in New Austin. In \"Paternal Pride\", [[bonnie-macfarlane|Bonnie MacFarlane]] asks John to look for her father Drew, who has been inside the barn for a day trying to keep the undead locked in. John climbs in through the upper floor, clears the barn and finds Drew turned; he has to kill him. He tells Bonnie, who says her father died protecting the people he loved. In \"Dinner for Two\", [[leigh-johnson|Marshal Leigh Johnson]] gives John a Sawed-off Shotgun and asks him to find his deputies Eli and Jonah. John passes the shopkeeper Herbert Moon, who is killed and turned outside his store, then finds Eli eating Jonah behind the saloon and kills both.",
              "Quatre missions secondaires se déroulent dans le New Austin. Dans \"Paternal Pride\", [[bonnie-macfarlane|Bonnie MacFarlane]] demande à John de retrouver son père Drew, enfermé depuis un jour dans la grange pour y contenir les morts-vivants. John entre par l'étage, nettoie la grange et trouve Drew transformé ; il doit le tuer. Il l'annonce à Bonnie, qui répond que son père est mort en protégeant ceux qu'il aimait. Dans \"Dinner for Two\", [[leigh-johnson|le marshal Leigh Johnson]] remet à John un fusil à canon scié et le charge de retrouver ses adjoints, Eli et Jonah. En chemin, John croise l'épicier Herbert Moon, tué puis transformé devant sa boutique, puis trouve Eli en train de dévorer Jonah derrière le saloon, et les abat tous les deux.")},
    {"p": two("In \"Filth and Other Entertainment\", the director D.S. MacKenna, camped at Plainview, wants to shoot a film about the undead and asks John to capture a Retcher. Once John brings it, MacKenna unties it and a second captive, and orders them to \"eat human flesh\". They obey: MacKenna is killed and turned, and John deals with all three. In \"Missing Souls\", Captain Cody Hixon is putting up missing-person posters at Fort Mercer. John finds Millicent Waterbury surrounded by undead at Pleasance House and brings her back to her family. Hixon tells him other people are still missing.",
              "Dans \"Filth and Other Entertainment\", le réalisateur D.S. MacKenna, installé sous une tente à Plainview, veut tourner un film sur les morts-vivants et demande à John de capturer un Retcher. Une fois la créature livrée, MacKenna la détache avec un second prisonnier et leur ordonne de \"manger de la chair humaine\". Ils obéissent : MacKenna est tué puis transformé, et John règle le sort des trois. Dans \"Missing Souls\", le capitaine Cody Hixon placarde des avis de disparition à Fort Mercer. John retrouve Millicent Waterbury cernée par les morts-vivants à Pleasance House et la ramène à sa famille. Hixon lui apprend que d'autres personnes sont encore portées disparues.")},
    {"p": two("In \"American Imperialism\", Dickens meets John at Solomon's Folly. He has heard that the plague is less severe in Mexico, and that a U.S. Army train at Benedict Point is about to leave for the border. Disguised as a soldier, John could board it. Dickens points him to a group of deserters camped at The Scratching Post. John either helps them fight off the undead and receives a uniform, or steals it. At Benedict Point, he helps defend the train and rides on a flatbed car, fighting off undead until the train stops at Frontera Bridge, blocked by debris. The captain orders the men to clear it; the soldiers flee when the undead attack. John holds alone, releases the brakes and drives the train into Mexico. He does not see Dickens again.",
              "Dans \"American Imperialism\", Dickens retrouve John à Solomon's Folly. Il a entendu dire que l'épidémie fait moins de ravages au Mexique, et qu'un train de l'armée américaine s'apprête à partir de Benedict Point vers la frontière. Déguisé en soldat, John pourrait y monter. Dickens l'oriente vers un groupe de déserteurs installés à The Scratching Post. John les aide à repousser les morts-vivants pour obtenir un uniforme, ou le vole. À Benedict Point, il aide à défendre le train, puis tient un wagon plat face aux morts-vivants jusqu'à Frontera Bridge, où des débris bloquent la voie. Le capitaine ordonne de dégager la voie ; les soldats s'enfuient quand les morts-vivants attaquent. John tient seul, desserre les freins et fait passer le train au Mexique. Il ne revoit plus Dickens.")},

    {"h4": two("Nuevo Paraíso", "Nuevo Paraíso")},
    {"p": two("In \"Mother Superior Blues\", John reaches the Las Hermanas train station as an undead is strangling the Mother Superior. She frees herself and shoots it in the head. Afraid she has sinned, she is reassured by John: she was defending herself. She asks him to clear the convent so her nuns are safe. To understand the plague, she then needs a \"fresh\" undead: John hogties one and brings it back. She pours holy water on it, and the body burns briefly in blue flame without dying. She sends John to cleanse the Sepulcro cemetery, where an undead [[vincente-de-santa|Vincente de Santa]] rises from his grave. Holy Water becomes available to the player. On his return, she tells him a woman linked the plague to something [[abraham-reyes|Abraham Reyes]] did, and sends him to Escalera.",
              "Dans \"Mother Superior Blues\", John arrive à la gare de Las Hermanas au moment où un mort-vivant étrangle la mère supérieure. Elle se dégage et l'abat d'une balle dans la tête, puis craint d'avoir commis un péché mortel ; John lui répond qu'il s'agissait de légitime défense. Elle lui demande de libérer le couvent pour mettre ses religieuses à l'abri. Pour comprendre l'épidémie, il lui faut ensuite un mort-vivant \"frais\" : John en ligote un et le lui ramène. Elle l'asperge d'eau bénite, et le corps brûle un instant d'une flamme bleue sans mourir. Elle envoie John purifier le cimetière de Sepulcro, où [[vincente-de-santa|Vincente de Santa]], mort-vivant, sort de sa tombe. L'eau bénite devient disponible pour le joueur. À son retour, elle lui rapporte qu'une femme attribue le fléau à un acte d'[[abraham-reyes|Abraham Reyes]], et l'envoie à Escalera.")},
    {"p": two("The side mission \"Biographies and Lies\" takes place in Casa Madrugada, which [[landon-ricketts|Landon Ricketts]] is defending on his own. John had expected Mexico to be quieter. Ricketts admits that in all his years he never saw anything to match the dead getting up. He suggests luring the undead in to kill them in numbers. John mentions that Dickens' elixir works as bait, and Ricketts asks him for a few bottles and some dynamite. He puts a stick into an opened bottle, throws it at an undead and fires at the ground to set it off. He gives John two of these Boom Baits, and the two men part.",
              "La mission secondaire \"Biographies and Lies\" se déroule à Casa Madrugada, que [[landon-ricketts|Landon Ricketts]] défend seul. John s'attendait à un Mexique plus calme. Ricketts lui dit avoir vu des horreurs dans sa vie, mais jamais rien de comparable aux morts qui marchent. Il propose d'attirer les morts-vivants pour les tuer en nombre. John signale que l'élixir de Dickens sert d'appât, et Ricketts lui demande deux flacons et deux bâtons de dynamite. Il fixe un bâton sur un flacon ouvert, le lance vers un mort-vivant et tire au sol pour le faire sauter. Il remet à John deux de ces Boom Baits, puis les deux hommes se séparent.")},
    {"p": two("In \"A Civilized Man\", John enters the presidential mansion in Escalera and finds an undead Reyes chasing a young woman round the table. John shouts at him and Reyes turns on him; John kills him. The woman explains that Reyes removed a mask from the catacombs beneath the town, and that putting it back will end the plague. The entrance is in the stands of the bullring behind the mansion. John fights through the catacombs and notices that the undead leave the woman alone. Once the mask is back on its altar, she reveals that she is Ayauhtéotl, then vanishes; her voice tells John to go back to his family.",
              "Dans \"A Civilized Man\", John pénètre dans la résidence présidentielle d'Escalera et trouve Reyes, devenu mort-vivant, en train de poursuivre une jeune femme autour de la table de la salle à manger. John l'interpelle, Reyes se retourne contre lui et John l'abat. La femme explique que Reyes a retiré un masque des catacombes situées sous la ville, et que le remettre en place mettra fin à l'épidémie. L'entrée se trouve dans les gradins de l'arène, derrière la résidence. John se fraie un chemin dans les catacombes et remarque que les morts-vivants ignorent la jeune femme. Une fois le masque replacé sur son autel, elle révèle être Ayauhtéotl, puis disparaît ; sa voix dit à John de retourner auprès des siens.")},

    {"h4": two("Epilogue", "Épilogue")},
    {"p": two("\"On a Pale Horse\" is listed as the last mission but has no title card of its own. John returns to Beecher's Hope and finds Abigail and Jack still tied up, but cured. The family is reunited. Three months later, Seth steals the mask again from the Escalera catacombs. By then, John has died, as in \"The Last Enemy That Shall Be Destroyed\", and the plague raises him from his grave. An in-game message explains that his wife and son buried him with a flask of water he valued, without knowing its power: he comes back with the body of an undead but the soul of a man. The player keeps control of him. Seth and the mask cannot be found, and the catacombs are sealed.",
              "\"On a Pale Horse\" figure comme dernière mission, mais n'a pas d'écran titre. John rentre à Beecher's Hope et trouve Abigail et Jack toujours ligotés, mais guéris. La famille se retrouve. Trois mois plus tard, Seth vole de nouveau le masque dans les catacombes d'Escalera. John est mort entre-temps, comme dans \"The Last Enemy That Shall Be Destroyed\", et l'épidémie le fait sortir de sa tombe. Un message du jeu explique que sa femme et son fils l'ont enterré avec une gourde d'eau à laquelle il tenait, sans en connaître le pouvoir : il revient avec le corps d'un mort-vivant mais l'âme d'un homme. Le joueur continue de le diriger. Seth et le masque restent introuvables, et l'entrée des catacombes est fermée.")},
    {"p": two("After this mission, towns can still be overrun and must be cleared again, and the remaining challenges and \"Missing Souls\" posters stay available. In this state, John walks and runs with a lopsided gait, which straightens when he draws a weapon. Other undead ignore him until he provokes them, for instance by shooting at them, walking too close or carrying a lit torch near them. His left foot is twisted, and his stance is the one he has when he collapses in \"The Last Enemy That Shall Be Destroyed\".",
              "Après cette mission, les villes peuvent encore être envahies et doivent être de nouveau libérées, et les défis restants comme les avis de \"Missing Souls\" restent accessibles. Dans cet état, John marche et court en boitant, et se redresse dès qu'il dégaine. Les autres morts-vivants l'ignorent tant qu'il ne les provoque pas, en leur tirant dessus, en s'approchant trop ou en brandissant une torche près d'eux. Son pied gauche est tordu, et sa posture reprend celle de sa chute dans \"The Last Enemy That Shall Be Destroyed\".")},
]

# ============================================================== MISSIONS
R2 = lambda mission, chap, en, fr: [mission, chap, two(en, fr)]
EP = lambda mission, part, en, fr: [mission, part, two(en, fr)]
UN = lambda mission, en, fr: [mission, two(en, fr)]
K = lambda name, game, mission, en, fr: [name, game, mission, two(en, fr)]

BLOCKS_MISSIONS = [
    # ---------------------------------------------------------- RDR2 1899
    {"h3": two("Red Dead Redemption 2 (1899)", "Red Dead Redemption 2 (1899)")},
    {"table": {"head": [two("Mission", "Mission"), two("Ch.", "Ch."), two("John's role", "Rôle de John")], "rows": [
        R2("Outlaws from the West", "1", "Missing in the snow", "Disparu dans la neige"),
        R2("Enter, Pursued by a Memory", "1", "Rescued from the wolves", "Sauvé des loups"),
        R2("Who the Hell is Leviticus Cornwall?", "1", "Bedridden, stays behind", "Alité, reste au camp"),
        R2("Eastward Bound", "1", "Carried out on a stretcher", "Évacué sur une civière"),
        R2("Paying a Social Call", "2", "Raids Six Point Cabin", "Attaque de Six Point Cabin"),
        R2("Pouring Forth Oil I, III, IV", "2", "Plans and robs the train (he also gives Arthur part II)", "Monte et exécute l'attaque du train (il confie aussi la partie II à Arthur)"),
        R2("The Sheep and the Goats", "2", "Sheep theft, taken hostage", "Vol de moutons, pris en otage"),
        R2("Advertising, The New American Art", "3", "Sent by Dutch to look at the Braithwaite horses", "Envoyé par Dutch repérer les chevaux des Braithwaite"),
        R2("Horse Flesh for Dinner", "3", "Steals the Braithwaite horses", "Vole les chevaux des Braithwaite"),
        R2("Blood Feuds, Ancient and Modern", "3", "Attack on Braithwaite Manor", "Assaut de Braithwaite Manor"),
        R2("The Battle of Shady Belle", "3", "Clears the plantation", "Libère la plantation"),
        R2("Angelo Bronte, A Man of Honor", "4", "Jack is returned", "Retour de Jack"),
        R2("Horsemen, Apocalypses", "4", "Defends the camp", "Défend le camp"),
        R2("Revenge is a Dish Best Eaten", "4", "Knocks out Bronte", "Assomme Bronte"),
        R2("Banking, The Old American Art", "4", "Arrested", "Arrêté"),
        R2("A Fork in the Road", "5", "Voice only", "Voix uniquement"),
        R2("Icarus and Friends", "6", "Spotted in the Sisika yard from Sadie's balloon", "Repéré dans la cour de Sisika depuis le ballon de Sadie"),
        R2("Visiting Hours", "6", "Freed from Sisika", "Libéré de Sisika"),
        R2("The Delights of Van Horn", "6", "Takes the stolen dynamite to the bridge", "Emporte la dynamite volée vers le pont"),
        R2("The Bridge to Nowhere", "6", "Blows up the Bacchus Bridge", "Fait sauter le pont de Bacchus"),
        R2("My Last Boy", "6", "Battle at the oil fields", "Bataille des champs pétrolifères"),
        R2("Our Best Selves", "6", "Shot, falls from the train", "Touché, tombe du train"),
        R2("Red Dead Redemption", "6", "Returns and escapes", "Revient et s'échappe"),
    ]}},

    # ---------------------------------------------------------- RDR2 epilogue
    {"h3": two("Red Dead Redemption 2: the epilogue (1907)", "Red Dead Redemption 2 : l'épilogue (1907)")},
    {"p": two("The player controls John in every epilogue mission: 11 in part 1 (Pronghorn Ranch) and 12 in part 2 (Beecher's Hope). Some pairs can be played in either order, which slightly changes the dialogue: when \"Jim Milton Rides, Again?\" or \"Fatherhood, For Idiots\" is completed first, John later has a flashback of Arthur's advice.",
              "Le joueur incarne John dans toutes les missions de l'épilogue : 11 dans la première partie (Pronghorn Ranch) et 12 dans la seconde (Beecher's Hope). Certaines paires se jouent dans l'ordre que l'on veut, ce qui modifie un peu les dialogues : selon que \"Jim Milton Rides, Again?\" ou \"Fatherhood, For Idiots\" est terminée en premier, John se remémore plus tard un conseil d'Arthur.")},
    {"table": {"head": [two("Mission", "Mission"), two("Part", "Partie"), two("Summary", "Résumé")], "rows": [
        EP("The Wheel", "1", "The family reaches Strawberry; as \"Jim Milton\", John delivers supplies to Pronghorn Ranch and recovers the wagon from two Laramie thieves.",
           "La famille arrive à Strawberry ; sous le nom de \"Jim Milton\", John livre des fournitures au Pronghorn Ranch et reprend le chariot à deux voleurs du gang Laramie."),
        EP("Simple Pleasures", "1", "John lets his real name slip in front of David Geddes; Abigail and Jack move into the ranch cabin.",
           "John laisse échapper son vrai nom devant David Geddes ; Abigail et Jack s'installent dans la cabane du ranch."),
        EP("Farming, For Beginners", "1", "Fence building with Tom Dickens, then John lassoes a bull that has knocked down Angus Geddes.",
           "Pose de clôtures avec Tom Dickens, puis John attrape au lasso un taureau qui a renversé Angus Geddes."),
        EP("Fatherhood, For Beginners", "1", "John helps Duncan Geddes with a horse, helps a mare give birth, then rides with Jack on a borrowed pony.",
           "John aide Duncan Geddes avec un cheval, assiste une jument qui met bas, puis chevauche avec Jack sur un poney prêté."),
        EP("Old Habits", "1", "The Laramie leader harasses the ranch; John beats him until Abigail stops him.",
           "Le chef des Laramie s'en prend au ranch ; John le frappe jusqu'à ce qu'Abigail l'arrête."),
        EP("Fatherhood, For Idiots", "1", "At the Strawberry post office John gives his real name; three riders linked to the Roanoke Ridge killing attack him and he kills them in front of Jack.",
           "Au bureau de poste de Strawberry, John donne son vrai nom ; trois cavaliers liés au meurtre du Roanoke Ridge l'attaquent et il les tue devant Jack."),
        EP("Jim Milton Rides, Again?", "1", "After a night raid, John, Tom and Abe take the cattle back at Hanging Dog Ranch; John kills the Laramie leader.",
           "Après un raid nocturne, John, Tom et Abe reprennent le bétail à Hanging Dog Ranch ; John tue le chef des Laramie."),
        EP("Motherhood", "1", "Abigail leaves with Jack; John works on at the ranch and Geddes directs him to the banker Ansel Atherton.",
           "Abigail part avec Jack ; John reste travailler au ranch et Geddes l'adresse au banquier Ansel Atherton."),
        EP("Gainful Employment", "1", "Reunited with Sadie in Valentine, John helps her capture the embezzler Nathan Kirk in Strawberry.",
           "Retrouvailles avec Sadie à Valentine ; John l'aide à capturer l'escroc Nathan Kirk à Strawberry."),
        EP("The Landowning Classes", "1", "John asks Atherton for a loan to buy Beecher's Hope, guaranteed by Geddes.",
           "John demande à Atherton un prêt pour acheter Beecher's Hope, avec la garantie de Geddes."),
        EP("Home of the Gentry?", "1", "John removes three squatters from Beecher's Hope (paid off or shot), signs the loan and buys the land.",
           "John chasse trois squatteurs de Beecher's Hope (en les payant ou en les abattant), signe le prêt et achète le terrain."),
        EP("Bare Knuckle Friendships", "2", "With Uncle, John finds Charles at a prize fight in Saint Denis.",
           "Avec Uncle, John retrouve Charles lors d'un combat de boxe à Saint-Denis."),
        EP("An Honest Day's Labors", "2", "John and Sadie take the fugitive Shane Finley back from the bounty hunter James Langton at Pike's Basin.",
           "John et Sadie reprennent le fugitif Shane Finley au chasseur de primes James Langton, à Pike's Basin."),
        EP("Home Improvement for Beginners", "2", "John, Charles and Uncle pull down the old shack.",
           "John, Charles et Uncle abattent la vieille cabane."),
        EP("The Tool Box", "2", "John buys a pre-cut house in Blackwater and tools at Manzanita Post, then fights off the Skinner Brothers.",
           "John achète une maison en kit à Blackwater et des outils à Manzanita Post, puis repousse les Skinner Brothers."),
        EP("A New Jerusalem", "2", "John and Charles build the house over several weeks; John writes to Abigail.",
           "John et Charles construisent la maison en plusieurs semaines ; John écrit à Abigail."),
        EP("A Quick Favor for an Old Friend", "2", "John orders a barn, then helps Sadie capture Ramón Cortez and recapture him after the Del Lobos free him in Rhodes.",
           "John commande une grange, puis aide Sadie à capturer Ramón Cortez et à le reprendre après son évasion de Rhodes, organisée par les Del Lobo."),
        EP("Uncle's Bad Day", "2", "John and Charles rescue Uncle from the Skinner Brothers' camp.",
           "John et Charles arrachent Uncle au camp des Skinner Brothers."),
        EP("The Best of Women", "2", "Cutscene: Abigail and Jack return to Beecher's Hope.",
           "Cinématique : Abigail et Jack reviennent à Beecher's Hope."),
        EP("Trying Again", "2", "John takes Jack fishing; he treats Rufus after a snake bite.",
           "John emmène Jack pêcher ; il soigne Rufus, mordu par un serpent."),
        EP("A Really Big Bastard", "2", "Abigail agrees to bounty work; with Sadie, John finds Marshall Thurwell in Tall Trees and is charged by a grizzly.",
           "Abigail accepte le travail de chasseur de primes ; avec Sadie, John retrouve Marshall Thurwell à Tall Trees et se fait charger par un grizzly."),
        EP("A New Future Imagined", "2", "A day in Blackwater with Abigail; John proposes to her in a canoe on the lake.",
           "Une journée à Blackwater avec Abigail ; John la demande en mariage en canoë, sur le lac."),
        EP("American Venom", "2", "Cleet gives up Micah's location; on Mount Hagen, Dutch shoots Micah and John finishes him.",
           "Cleet révèle où se cache Micah ; au mont Hagen, Dutch tire sur Micah et John l'achève."),
    ]}},

    # ---------------------------------------------------------- RDR1
    {"h3": two("Red Dead Redemption (1911): the 57 story missions", "Red Dead Redemption (1911) : les 57 missions principales")},
    {"table": {"head": [two("Act", "Acte"), two("Mission giver", "Donneur"), two("Missions", "Missions")], "rows": [
        ["I", "John", "Exodus in America"],
        ["I", "[[bonnie-macfarlane|Bonnie MacFarlane]]", "New Friends, Old Problems · Obstacles in Our Path · This is Armadillo, USA · Women and Cattle · Wild Horses, Tamed Passions · A Tempest Looms · The Burning"],
        ["I", "[[leigh-johnson|Leigh Johnson]]", "Political Realities in Armadillo · Justice in Pike's Basin · Spare the Rod, Spoil the Bandit · Hanging Bonnie MacFarlane · The Assault on Fort Mercer"],
        ["I", "[[nigel-west-dickens|Nigel West Dickens]]", "Old Swindler Blues · You Shall Not Give False Testimony, Except for Profit · Liars, Cheats and Other Proud Americans · Can a Swindler Change His Spots? · The Sport of Kings, and Liars"],
        ["I", "[[seth-briars|Seth Briars]]", "Exhuming and Other Fine Hobbies · A Gentle Drive with Friends · Let the Dead Bury Their Dead"],
        ["I", "[[irish|Irish]]", two("A Frenchman, a Welshman and an Irishman · Man is Born Unto Trouble · On Shaky's Ground · We Shall Be Together in Paradise (counted as Act II in the game's statistics)", "A Frenchman, a Welshman and an Irishman · Man is Born Unto Trouble · On Shaky's Ground · We Shall Be Together in Paradise (comptée dans l'acte II par les statistiques du jeu)")],
        ["II", "[[vincente-de-santa|Vincente de Santa]]", "Civilization, at Any Price · The Demon Drink · Empty Promises · Mexican Caesar · Cowards Die Many Times"],
        ["II", "[[landon-ricketts|Landon Ricketts]]", "The Gunslinger's Tragedy · Landon Ricketts Rides Again · Lucky in Love · The Mexican Wagon Train"],
        ["II", "[[luisa-fortuna|Luisa Fortuna]]", "My Sister's Keeper · Must a Savior Die? · Father Abraham · Captain De Santa's Downfall"],
        ["II", "[[abraham-reyes|Abraham Reyes]]", "The Great Mexican Train Robbery · The Gates of El Presidio · An Appointed Time"],
        ["III", "[[edgar-ross|Edgar Ross]]", "Bear One Another's Burdens · Great Men are Not Always Wise · And You Will Know The Truth · And The Truth Will Set You Free"],
        ["III", "[[harold-macdougal|Harold MacDougal]]", "At Home with Dutch · For Purely Scientific Purposes · The Prodigal Son Returns (To Yale)"],
        ["III", "[[abigail-marston|Abigail Marston]]", "The Outlaw's Return · Pestilence · Old Friends, New Problems"],
        ["III", "[[uncle|Uncle]]", "By Sweat and Toil · A Continual Feast"],
        ["III", "[[jack-marston|Jack Marston]]", "John Marston and Son · Wolves, Dogs and Sons · Spare the Love, Spoil the Child · The Last Enemy That Shall Be Destroyed"],
    ]}},
    {"p": two("John appears in every mission of Red Dead Redemption except the stranger mission \"Remember My Family\", played as Jack after his death.",
              "John apparaît dans toutes les missions de Red Dead Redemption, sauf la mission d'inconnu \"Remember My Family\", jouée avec Jack après sa mort.")},

    # ---------------------------------------------------------- Undead Nightmare
    {"h3": two("Undead Nightmare (2010)", "Undead Nightmare (2010)")},
    {"table": {"head": [two("Mission", "Mission"), two("Summary", "Résumé")], "rows": [
        UN("Love in the Time of Plague", "Uncle turns and bites Abigail, who bites Jack; John kills Uncle and hogties his wife and son.",
           "Uncle, transformé, mord Abigail, qui mord Jack ; John abat Uncle et ligote sa femme et son fils."),
        UN("Curious Tales from Blackwater", "MacDougal is killed by an undead Nastas; John clears the cemetery and the town, and gets two leads.",
           "MacDougal est tué par Nastas, devenu mort-vivant ; John nettoie le cimetière et la ville, et obtient deux pistes."),
        UN("Get Back in That Hole, Partner", "Seth sends John to clear three cemeteries, then points him to Mexico.",
           "Seth envoie John nettoyer trois cimetières, puis l'oriente vers le Mexique."),
        UN("A Cure for Most of What Ails You", "Dickens's tonic proves to be bait; he makes a phosphorus coating and a Blunderbuss.",
           "Le tonique de Dickens se révèle être un appât ; il prépare un enrobage au phosphore et un tromblon."),
        UN("American Imperialism", "Disguised in an army uniform, John rides the army train and drives it into Mexico.",
           "Sous un uniforme de l'armée, John monte dans le train militaire et le conduit jusqu'au Mexique."),
        UN("Mother Superior Blues", "John clears Las Hermanas and Sepulcro for the Mother Superior; Holy Water is unlocked.",
           "John libère Las Hermanas et Sepulcro pour la mère supérieure ; l'eau bénite est débloquée."),
        UN("A Civilized Man", "John kills the undead Reyes and returns the mask to its altar with Ayauhtéotl.",
           "John abat Reyes, devenu mort-vivant, et replace le masque sur son autel avec Ayauhtéotl."),
        UN("On a Pale Horse", "The family is cured; months later, Seth steals the mask and John rises from his grave.",
           "La famille est guérie ; des mois plus tard, Seth vole le masque et John sort de sa tombe."),
        UN("Birth of the Conservation Movement", "Side mission: six Sasquatches hunted in Tall Trees; the last one asks to die.",
           "Mission secondaire : six Sasquatch chassés à Tall Trees ; le dernier demande à mourir."),
        UN("Paternal Pride", "Side mission: John kills the undead Drew MacFarlane in his barn.",
           "Mission secondaire : John abat Drew MacFarlane, devenu mort-vivant, dans sa grange."),
        UN("Dinner for Two", "Side mission: John kills Leigh Johnson's turned deputies, Eli and Jonah.",
           "Mission secondaire : John abat les adjoints transformés de Leigh Johnson, Eli et Jonah."),
        UN("Missing Souls", "Side mission: John rescues Millicent Waterbury for Captain Hixon; more missing people follow.",
           "Mission secondaire : John sauve Millicent Waterbury pour le capitaine Hixon ; d'autres disparus suivent."),
        UN("Filth and Other Entertainment", "Side mission: D.S. MacKenna is eaten by the undead he wanted to film.",
           "Mission secondaire : D.S. MacKenna est dévoré par les morts-vivants qu'il voulait filmer."),
        UN("Biographies and Lies", "Side mission: Landon Ricketts makes Boom Bait from elixir and dynamite.",
           "Mission secondaire : Landon Ricketts fabrique des Boom Baits avec de l'élixir et de la dynamite."),
    ]}},

    # ---------------------------------------------------------- strangers & bounties
    {"h3": two("Stranger missions and bounties", "Missions d'inconnus et primes")},
    {"ul": [
        two("Red Dead Redemption: 18 of the game's 19 stranger missions are played as John (all except \"Remember My Family\"): American Appetites, American Lobbyist, Aztec Gold, California, Deadalus and Son, Eva in Peril, Flowers for a Lady, Funny Man, I Know You, Jenny's Faith, Let No Man Put Asunder, Lights, Camera, Action, Love is the Opiate, Poppycock, The Prohibitionist, Water and Honesty, Who Are You to Judge? and The Wronged Woman.",
            "Red Dead Redemption : 18 des 19 missions d'inconnus se jouent avec John (toutes sauf \"Remember My Family\") : American Appetites, American Lobbyist, Aztec Gold, California, Deadalus and Son, Eva in Peril, Flowers for a Lady, Funny Man, I Know You, Jenny's Faith, Let No Man Put Asunder, Lights, Camera, Action, Love is the Opiate, Poppycock, The Prohibitionist, Water and Honesty, Who Are You to Judge? et The Wronged Woman."),
        two("Red Dead Redemption: John takes bounties from wanted posters, bringing targets in dead or alive. The bounty on Mo van Barr is tied to the Deadly Assassin Outfit.",
            "Red Dead Redemption : John accepte des primes affichées sur les avis de recherche et ramène les fugitifs morts ou vifs. La prime sur Mo van Barr est liée à la tenue Deadly Assassin."),
        two("Red Dead Redemption 2, epilogue: stranger missions left unfinished by Arthur can be completed as John, among them \"The Noblest of Men, and a Woman\" (John asks the biographer Theodore Levin to send the money to \"Jim Milton\"). Charlotte Balfour can be visited at her cabin, where John tells her of Arthur's death.",
            "Red Dead Redemption 2, épilogue : les missions d'inconnus laissées inachevées par Arthur peuvent être terminées avec John, dont \"The Noblest of Men, and a Woman\" (John demande au biographe Theodore Levin d'envoyer l'argent à \"Jim Milton\"). John peut rendre visite à Charlotte Balfour dans sa cabane et lui annoncer la mort d'Arthur."),
        two("Red Dead Redemption 2, epilogue: besides Sadie's bounty missions, John can take wanted posters, among them Lindsey Wofford (Saint Denis, $100), Esteban Cortez (Tumbleweed, $65, hiding at Gaptooth Breach after his brother Ramón's capture), Bart Cavanaugh (Strawberry, after \"Gainful Employment\"), Elias Green and Otis Skinner (Blackwater) and Camille de Millemont.",
            "Red Dead Redemption 2, épilogue : en plus des missions de Sadie, John peut suivre des avis de recherche, dont Lindsey Wofford (Saint-Denis, 100 $), Esteban Cortez (Tumbleweed, 65 $, caché à Gaptooth Breach après la capture de son frère Ramón), Bart Cavanaugh (Strawberry, après \"Gainful Employment\"), Elias Green et Otis Skinner (Blackwater) et Camille de Millemont."),
    ]},

    # ---------------------------------------------------------- notable kills
    {"h3": two("Notable people John kills", "Personnages notables tués par John")},
    {"p": two("The table lists named characters John kills in the course of missions. Kills marked optional depend on the player's choices.",
              "Le tableau recense les personnages nommés que John tue au fil des missions. Ceux marqués facultatifs dépendent des choix du joueur.")},
    {"table": {"head": [two("Name", "Nom"), two("Game", "Jeu"), two("Mission", "Mission"), two("Circumstances", "Circonstances")], "rows": [
        K("Gerald and Gareth Braithwaite", "RDR2 (1899)", "Blood Feuds, Ancient and Modern",
          "Shot in Catherine Braithwaite's bedroom during the attack on the manor, by Arthur or John.",
          "Abattus dans la chambre de Catherine Braithwaite lors de l'assaut du manoir, par Arthur ou par John."),
        K("Three riders", "RDR2 (1907)", "Fatherhood, For Idiots",
          "Linked to the man John killed in Roanoke Ridge, one of them his brother; they draw and John shoots all three.",
          "Liés à l'homme tué par John dans le Roanoke Ridge, dont son frère ; ils dégainent et John les abat tous les trois."),
        K("Laramie gang leader", "RDR2 (1907)", "Jim Milton Rides, Again?",
          "Ambushes John in the barn at Hanging Dog Ranch; John disarms him and kills him with his own shotgun.",
          "Tend une embuscade à John dans la grange de Hanging Dog Ranch ; John le désarme et le tue avec son propre fusil."),
        K("Beecher's Hope squatters", "RDR2 (1907)", "Home of the Gentry?",
          "Optional: if John tries to intimidate them, they draw and he kills all three; he can pay them $10 instead.",
          "Facultatif : si John cherche à les intimider, ils dégainent et il les tue tous les trois ; il peut aussi leur donner 10 $."),
        K("James Langton", "RDR2 (1907)", "An Honest Day's Labors",
          "Killed by John or Sadie in the shootout at Pike's Basin.",
          "Tué par John ou par Sadie lors de la fusillade de Pike's Basin."),
        K("Cleet", "RDR2 (1907)", "American Venom",
          "Optional: hanged by John in Strawberry; if spared, Sadie shoots him.",
          "Facultatif : pendu par John à Strawberry ; s'il est épargné, Sadie l'abat."),
        K("Joe", "RDR2 (1907)", "American Venom",
          "Shot with two other members of Micah's gang on Mount Hagen.",
          "Abattu avec deux autres membres de la bande de Micah au mont Hagen."),
        K("[[micah-bell|Micah Bell]]", "RDR2 (1907)", "American Venom",
          "Shot in the chest by Dutch, then finished by John.",
          "Touché à la poitrine par Dutch, puis achevé par John."),
        K("Walton Lowe", "RDR1", "Political Realities in Armadillo",
          "Optional: the marshal asks John to shoot him in the leg, or kill him if he must.",
          "Facultatif : le marshal demande à John de le blesser à la jambe, ou de le tuer s'il le faut."),
        K("Moses Forth", "RDR1", "Exhuming and Other Fine Hobbies",
          "Optional, at the player's choice.",
          "Facultatif, au choix du joueur."),
        K("Leander Holland and Alwyn Lloyd", "RDR1", "A Frenchman, a Welshman and an Irishman",
          "Shot in self-defense when they rush John, who is protecting Irish.",
          "Abattus en légitime défense quand ils se ruent sur John, venu protéger Irish."),
        K("Simon", "RDR1", "The Gunslinger's Tragedy",
          "With two companions, he harasses John in Chuparosa and takes his hat; John shoots all three.",
          "Avec deux complices, il provoque John à Chuparosa et lui prend son chapeau ; John abat les trois."),
        K("Andreas Müller", "RDR1", "Lucky in Love",
          "Accuses John of cheating at poker in Chuparosa; killed in a duel.",
          "Accuse John de tricher au poker à Chuparosa ; tué en duel."),
        K("Sanchez", "RDR1", "Lucky in Love",
          "Takes a woman hostage at knifepoint after Müller's death; John shoots him.",
          "Prend une femme en otage au couteau après la mort de Müller ; John l'abat d'une balle dans la tête."),
        K("Espinoza", "RDR1", "Cowards Die Many Times",
          "Killed in the fighting in Chuparosa after de Santa betrays John.",
          "Tué lors des combats de Chuparosa, après la trahison de De Santa."),
        K("[[vincente-de-santa|Vincente de Santa]]", "RDR1", "Captain De Santa's Downfall",
          "Optional, at the player's choice.",
          "Facultatif, au choix du joueur."),
        K("[[javier-escuella|Javier Escuella]]", "RDR1", "The Gates of El Presidio",
          "Optional: captured alive or killed at the end of the chase.",
          "Facultatif : capturé vivant ou tué au terme de la poursuite."),
        K("Raul Zubieta", "RDR1", "An Appointed Time",
          "Killed in a duel after the death of Luisa Fortuna; John also kills Aurelio Canizales and Sebastian Nolasco.",
          "Tué en duel après la mort de Luisa Fortuna ; John abat aussi Aurelio Canizales et Sebastian Nolasco."),
        K("[[agustin-allende|Agustin Allende]] and [[bill-williamson|Bill Williamson]]", "RDR1", "An Appointed Time",
          "Optional: each is shot by John or by Reyes, depending on the player's choices.",
          "Facultatif : chacun est abattu par John ou par Reyes, selon les choix du joueur."),
        K("[[archer-fordham|Archer Fordham]]", "RDR1", "The Last Enemy That Shall Be Destroyed",
          "Optional, during the attack on Beecher's Hope.",
          "Facultatif, pendant l'assaut de Beecher's Hope."),
        K("Mario Alcalde", "RDR1", "Eva in Peril",
          "Found digging up Eva Cortes, whom he killed, at Sepulcro; killed in a duel.",
          "Surpris à Sepulcro en train de déterrer Eva Cortes, qu'il a tuée ; tué en duel."),
        K("Harold Thornton", "RDR1", "The Wronged Woman",
          "Killed in a duel in Blackwater after Clara LaGuerta's accusation; his widow reveals that Clara lied.",
          "Tué en duel à Blackwater après l'accusation de Clara LaGuerta ; sa veuve révèle que Clara a menti."),
        K("Randall Forrester", "RDR1", "American Appetites",
          "Optional: Forrester sends John after Andrew Holifield, the man who escaped him; if John hands Holifield over, Forrester eats him.",
          "Facultatif : Forrester envoie John à la poursuite d'Andrew Holifield, qui lui a échappé ; si John le lui ramène, Forrester le dévore."),
        K("Clyde Evans", "RDR1", "Water and Honesty",
          "Optional: John can buy the Pleasance House deed or kill Evans to take it.",
          "Facultatif : John peut acheter l'acte de Pleasance House ou tuer Evans pour le prendre."),
        K("Uriah Tollets", "RDR1", "Poppycock",
          "Optional: John learns the package he delivered was opium.",
          "Facultatif : John découvre que le colis qu'il a livré contenait de l'opium."),
        K("Abner Forsyth", "RDR1", "The Prohibitionist",
          "Optional: the saloon owner Oliver Philips pays for his death; John can warn him instead.",
          "Facultatif : le patron de saloon Oliver Philips paie pour sa mort ; John peut aussi le prévenir."),
        K("Andrew Holifield", "RDR1", "American Appetites",
          "Optional, at the player's choice.",
          "Facultatif, au choix du joueur."),
        K("Andrew McAllister", "RDR1", "Water and Honesty",
          "Optional, once the mission is complete.",
          "Facultatif, une fois la mission terminée."),
        K("Basilio Aguirre Olmos de la Vargas", "RDR1", "Aztec Gold",
          "Optional, at the player's choice.",
          "Facultatif, au choix du joueur."),
        K("Mr. Philmore and Aldous Worthington", "RDR1", "American Lobbyist",
          "Optional, at the player's choice.",
          "Facultatif, au choix du joueur."),
        K("Anselmo and Elisio", "RDR2 (1907)", "The Noblest of Men, and a Woman",
          "Optional: two men at Flaco Hernández's camp, if the mission is still unfinished when the epilogue begins.",
          "Facultatif : deux hommes du camp de Flaco Hernández, si la mission n'est pas terminée au début de l'épilogue."),
        K("Emmet Granger, Flaco Hernández, Billy Midnight, Jim \"Boy\" Calloway", "RDR2 (1907)", "The Noblest of Men, and a Woman",
          "Duels, only if the mission is still unfinished when the epilogue begins.",
          "Duels, seulement si la mission n'est pas terminée au début de l'épilogue."),
    ]}},

    # ---------------------------------------------------------- multiplayer
    {"h3": two("Multiplayer", "Multijoueur")},
    {"p": two("John was added to the multiplayer mode of Red Dead Redemption with the Liars and Cheats pack, released on September 21, 2010; he can be selected in the \"Redemption\" section of the Outfitter. Undead Nightmare added an undead version of him in the \"Zombies\" section. In multiplayer, this undead John walks and runs normally. John does not appear as a character in Red Dead Online.",
              "John rejoint le multijoueur de Red Dead Redemption avec le pack Liars and Cheats, sorti le 21 septembre 2010 ; on le choisit dans la section \"Redemption\" de l'Outfitter. Undead Nightmare ajoute une version mort-vivante du personnage, dans la section \"Zombies\". En multijoueur, ce John mort-vivant marche et court normalement. John n'apparaît pas comme personnage dans Red Dead Online.")},
]
