def two(en, fr): return {"en": en, "fr": fr}

# Every quote below was checked verbatim against the Red Dead Wiki transcript page
# "<Mission>/dialogues" (or "/Dialogues") on 8 Oct 2026. Original spelling kept.
BLOCKS_QUOTES = [
    {"h3": two("Red Dead Redemption 2 (1899)", "Red Dead Redemption 2 (1899)")},
    {"quotes": [
        {"q": two("Never thought I'd say this, but... it's good to see you, Arthur Morgan.",
                  "Never thought I'd say this, but... it's good to see you, Arthur Morgan."),
         "src": two("Enter, Pursued by a Memory (RDR2, chapter 1), to Arthur on the ledge where the wolves cornered him",
                    "Enter, Pursued by a Memory (RDR2, chapitre 1), à Arthur, sur la corniche où les loups l'ont acculé. Traduction : « J'aurais jamais cru dire ça, mais... ça fait plaisir de te voir, Arthur Morgan. »")},
        {"q": two("I was always ugly, Dutch... it's just a scratch.",
                  "I was always ugly, Dutch... it's just a scratch."),
         "src": two("Who the Hell is Leviticus Cornwall? (RDR2, chapter 1), about the wolf scars on his face",
                    "Who the Hell is Leviticus Cornwall? (RDR2, chapitre 1), à propos des cicatrices laissées par les loups. Traduction : « J'ai toujours été moche, Dutch... c'est qu'une égratignure. »")},
        {"q": two("Rip Van Winkle.", "Rip Van Winkle."),
         "src": two("The Battle of Shady Belle (RDR2, chapter 3), his answer when Pinkerton agent Andrew Milton asks who he is",
                    "The Battle of Shady Belle (RDR2, chapitre 3), sa réponse quand l'agent Pinkerton Andrew Milton lui demande qui il est. Traduction : « Rip Van Winkle. » (nom du héros d'une nouvelle de Washington Irving)")},
        {"q": two("You left me... you left me to die!", "You left me... you left me to die!"),
         "src": two("Red Dead Redemption (RDR2, chapter 6), to Dutch, on returning to camp after his escape from Sisika",
                    "Red Dead Redemption (RDR2, chapitre 6), à Dutch, en revenant au camp après son évasion de Sisika. Traduction : « Tu m'as laissé... tu m'as laissé crever ! »")},
        {"q": two("Thank you... brother.", "Thank you... brother."),
         "src": two("Red Dead Redemption (RDR2, chapter 6), after Arthur tells him Abigail and Jack are with Sadie at Copperhead Landing",
                    "Red Dead Redemption (RDR2, chapitre 6), quand Arthur lui apprend qu'Abigail et Jack sont avec Sadie à Copperhead Landing. Traduction : « Merci... mon frère. »")},
        {"q": two("I head down there, I'm dead in five minutes. I got a family, that's more important.",
                  "I head down there, I'm dead in five minutes. I got a family, that's more important."),
         "src": two("Red Dead Redemption (RDR2, chapter 6)",
                    "Red Dead Redemption (RDR2, chapitre 6). Traduction : « Si j'y retourne, je suis mort en cinq minutes. J'ai une famille, c'est plus important. »")},
        {"q": two("You're my brother...", "You're my brother..."),
         "src": two("Red Dead Redemption (RDR2, chapter 6), his last words to Arthur when Arthur tells him to leave",
                    "Red Dead Redemption (RDR2, chapitre 6), ses derniers mots à Arthur, qui lui ordonne de partir. Traduction : « T'es mon frère... »")},
    ]},
    {"h3": two("Red Dead Redemption 2: the epilogue (1907)", "Red Dead Redemption 2 : l'épilogue (1907)")},
    {"quotes": [
        {"q": two("All this... all this wouldn't exist if it weren't for Arthur, Sadie... and all the folks as fell. If I let him go... this place ain't no more real than... than one of Jack's dragons.",
                  "All this... all this wouldn't exist if it weren't for Arthur, Sadie... and all the folks as fell. If I let him go... this place ain't no more real than... than one of Jack's dragons."),
         "src": two("American Venom (RDR2, epilogue), to Abigail before leaving to hunt Micah",
                    "American Venom (RDR2, épilogue), à Abigail, avant de partir traquer Micah. Traduction : « Tout ça... tout ça existerait pas sans Arthur, sans Sadie... et sans tous ceux qui sont tombés. Si je le laisse filer... cet endroit sera pas plus réel que... qu'un des dragons de Jack. »")},
        {"q": two("Dutch... Dutch... we all did our best for you... ain't our fault, things turned out the way they did. Dutch... killing me won't solve nothing!",
                  "Dutch... Dutch... we all did our best for you... ain't our fault, things turned out the way they did. Dutch... killing me won't solve nothing!"),
         "src": two("American Venom (RDR2, epilogue), at the standoff on Mount Hagen",
                    "American Venom (RDR2, épilogue), lors du face-à-face au mont Hagen. Traduction : « Dutch... Dutch... on a tous fait de notre mieux pour toi... c'est pas notre faute si ça a tourné comme ça. Dutch... me tuer, ça réglera rien ! »")},
        {"q": two("It's over, Abigail. It's all over.", "It's over, Abigail. It's all over."),
         "src": two("American Venom (RDR2, epilogue), back at Beecher's Hope",
                    "American Venom (RDR2, épilogue), de retour à Beecher's Hope. Traduction : « C'est fini, Abigail. Tout est fini. »")},
    ]},
    {"h3": two("Red Dead Redemption (1911)", "Red Dead Redemption (1911)")},
    {"quotes": [
        {"q": two("Bill, I implore you, think about this.", "Bill, I implore you, think about this."),
         "src": two("Exodus in America (RDR1, act I), outside Fort Mercer, before Bill Williamson's men shoot him",
                    "Exodus in America (RDR1, acte I), devant Fort Mercer, avant que les hommes de Bill Williamson ne lui tirent dessus. Traduction : « Bill, je t'en conjure, réfléchis. »")},
        {"q": two("People don't forget. Nothing gets forgiven.", "People don't forget. Nothing gets forgiven."),
         "src": two("Women and Cattle (RDR1, act I), to Bonnie MacFarlane, after describing his Scottish father",
                    "Women and Cattle (RDR1, acte I), à Bonnie MacFarlane, après avoir parlé de son père écossais. Traduction : « Les gens n'oublient pas. Rien n'est jamais pardonné. »")},
        {"q": two("I think it's this land that makes the men, as much as the other way around. Men are born, and then they're formed, at least that's how I see it.",
                  "I think it's this land that makes the men, as much as the other way around. Men are born, and then they're formed, at least that's how I see it."),
         "src": two("Spare the Rod, Spoil the Bandit (RDR1, act I), to Marshal Leigh Johnson",
                    "Spare the Rod, Spoil the Bandit (RDR1, acte I), au marshal Leigh Johnson. Traduction : « Je crois que c'est cette terre qui fait les hommes, autant que l'inverse. On naît, et ensuite on est façonné, c'est comme ça que je vois les choses. »")},
        {"q": two("I have a son at home and a daughter in heaven.", "I have a son at home and a daughter in heaven."),
         "src": two("Father Abraham (RDR1, act II), when Luisa Fortuna asks whether he has children",
                    "Father Abraham (RDR1, acte II), quand Luisa Fortuna lui demande s'il a des enfants. Traduction : « J'ai un fils à la maison et une fille au ciel. »")},
        {"q": two("I tried to go straight. I did. I left the gang after the gang left me. Left me to die after I'd been shot.",
                  "I tried to go straight. I did. I left the gang after the gang left me. Left me to die after I'd been shot."),
         "src": two("The Mexican Wagon Train (RDR1, act II), to Landon Ricketts",
                    "The Mexican Wagon Train (RDR1, acte II), à Landon Ricketts. Traduction : « J'ai essayé de me ranger. Vraiment. J'ai quitté le gang après que le gang m'a quitté. Il m'a laissé mourir après que j'ai pris une balle. »")},
        {"q": two("What you and Dutch did was wrong. And the way you left me was wrong. Now, I ain't the judge, but as it turns out, it's you or me, the way I see it, it might as well be you.",
                  "What you and Dutch did was wrong. And the way you left me was wrong. Now, I ain't the judge, but as it turns out, it's you or me, the way I see it, it might as well be you."),
         "src": two("The Gates of El Presidio (RDR1, act II), to Javier Escuella",
                    "The Gates of El Presidio (RDR1, acte II), à Javier Escuella. Traduction : « Ce que Dutch et toi avez fait, c'était mal. Et la façon dont vous m'avez laissé, c'était mal. Je suis pas juge, mais il se trouve que c'est toi ou moi, et tant qu'à faire, autant que ce soit toi. »")},
        {"q": two("It's time to stop running, Bill!", "It's time to stop running, Bill!"),
         "src": two("An Appointed Time (RDR1, act II), during the assault on Escalera",
                    "An Appointed Time (RDR1, acte II), pendant l'assaut d'Escalera. Traduction : « Il est temps d'arrêter de fuir, Bill ! »")},
        {"q": two("My side ain't chosen. My side was given. I'd kill you a hundred times before I killed Dutch, if it was an option.",
                  "My side ain't chosen. My side was given. I'd kill you a hundred times before I killed Dutch, if it was an option."),
         "src": two("Great Men are Not Always Wise (RDR1, act III), to Edgar Ross, who has just told him his side is chosen",
                    "Great Men are Not Always Wise (RDR1, acte III), à Edgar Ross, qui vient de lui dire qu'il a choisi son camp. Traduction : « Mon camp, je l'ai pas choisi. On me l'a imposé. Je te tuerais cent fois avant de tuer Dutch, si j'avais le choix. »")},
        {"q": two("They told us there was a prize when you got to 50.", "They told us there was a prize when you got to 50."),
         "src": two("Bear One Another's Burdens (RDR1, act III), after Ross credits him with at least 40 bank robberies",
                    "Bear One Another's Burdens (RDR1, acte III), quand Ross lui attribue au moins 40 braquages de banque. Traduction : « On nous avait dit qu'il y avait un prix à partir de 50. »")},
        {"q": two("Well, some trees flourish, others die. Some cattle grow strong, others are taken by wolves. Some men are born rich enough and dumb enough to enjoy their lives. Ain't nothing fair. You know that.",
                  "Well, some trees flourish, others die. Some cattle grow strong, others are taken by wolves. Some men are born rich enough and dumb enough to enjoy their lives. Ain't nothing fair. You know that."),
         "src": two("The Outlaw's Return (RDR1, act III), to Abigail at Beecher's Hope",
                    "The Outlaw's Return (RDR1, acte III), à Abigail, à Beecher's Hope. Traduction : « Certains arbres poussent, d'autres meurent. Certaines bêtes deviennent fortes, d'autres finissent sous les crocs des loups. Certains naissent assez riches et assez bêtes pour profiter de la vie. Rien n'est juste. Tu le sais. »")},
        {"q": two("If you find yourself in a hole, the first thing to do is stop diggin'.",
                  "If you find yourself in a hole, the first thing to do is stop diggin'."),
         "src": two("Old Friends, New Problems (RDR1, act III)",
                    "Old Friends, New Problems (RDR1, acte III). Traduction : « Quand on se retrouve au fond d'un trou, la première chose à faire, c'est d'arrêter de creuser. »")},
        {"q": two("He ain't going to be no frontier gunslinger, killing and running in no gang though. That way's over. Railroads and government and motorcars and everything gone and done away with all that.",
                  "He ain't going to be no frontier gunslinger, killing and running in no gang though. That way's over. Railroads and government and motorcars and everything gone and done away with all that."),
         "src": two("Pestilence (RDR1, act III), to Abigail, about Jack",
                    "Pestilence (RDR1, acte III), à Abigail, à propos de Jack. Traduction : « Mais il sera pas un pistolero de la frontière, à tuer et à cavaler avec un gang. Cette époque est finie. Le chemin de fer, le gouvernement, les automobiles, tout ça a balayé ce monde-là. »")},
        {"q": two("We all need friends, old timer. We die alone, but we live among men.",
                  "We all need friends, old timer. We die alone, but we live among men."),
         "src": two("Water and Honesty (RDR1, stranger mission), to Clyde Evans",
                    "Water and Honesty (RDR1, mission d'inconnu), à Clyde Evans. Traduction : « On a tous besoin d'amis, l'ancien. On meurt seul, mais on vit parmi les hommes. »")},
        {"q": two("Ain't no trouble, Abigail. Ain't no trouble. I love you.",
                  "Ain't no trouble, Abigail. Ain't no trouble. I love you."),
         "src": two("The Last Enemy That Shall Be Destroyed (RDR1, act III), to Abigail as the army surrounds the ranch",
                    "The Last Enemy That Shall Be Destroyed (RDR1, acte III), à Abigail, alors que l'armée encercle le ranch. Traduction : « C'est rien, Abigail. C'est rien. Je t'aime. »")},
        {"q": two("Now go. Git.", "Now go. Git."),
         "src": two("The Last Enemy That Shall Be Destroyed (RDR1, act III), sending Abigail and Jack away before he faces Ross's men alone",
                    "The Last Enemy That Shall Be Destroyed (RDR1, acte III), en renvoyant Abigail et Jack avant d'affronter seul les hommes de Ross. Traduction : « Allez, filez. »")},
    ]},
]

BLOCKS_TRIVIA = [
    {"h4": two("General", "Généralités")},
    {"ul": [
        two("John and Abigail have the same first names as John Adams, the second president of the United States, and his wife Abigail Adams.",
            "John et Abigail portent les mêmes prénoms que John Adams, deuxième président des États-Unis, et sa femme Abigail Adams."),
        two("The pairing also appears in Arthur Miller's play The Crucible (1953), where John Proctor and Abigail Williams have a secret affair.",
            "Le même duo de prénoms figure dans la pièce d'Arthur Miller Les Sorcières de Salem (The Crucible, 1953), où John Proctor et Abigail Williams ont une liaison cachée."),
        two("He is playable in three releases: Red Dead Redemption (2010), its expansion Undead Nightmare (2010) and Red Dead Redemption 2 (2018).",
            "Il est jouable dans trois titres : Red Dead Redemption (2010), son extension Undead Nightmare (2010) et Red Dead Redemption 2 (2018)."),
        two("Leaving aside the optional characters of the GTA London expansions (1999), he is the first protagonist created by Rockstar to be playable in more than one game. Max Payne, playable in three games, was created by Remedy Entertainment: Rockstar published the first two games and developed only Max Payne 3 (2012).",
            "Hors personnages optionnels des extensions GTA London (1999), c'est le premier héros créé par Rockstar à être jouable dans plus d'un jeu. Max Payne, jouable dans trois jeux, est une création de Remedy Entertainment : Rockstar a édité les deux premiers épisodes et n'a développé que Max Payne 3 (2012)."),
        two("His grave at Beecher's Hope gives the years 1873 and 1911 and the epitaph \"Blessed are the peacemakers\". The line is a beatitude from the Sermon on the Mount, in the Gospel of Matthew (5:9).",
            "Sa tombe à Beecher's Hope porte les années 1873 et 1911, avec l'épitaphe \"Blessed are the peacemakers\" (\"Heureux les artisans de paix\"). C'est l'une des béatitudes du Sermon sur la montagne, dans l'Évangile selon Matthieu (5:9)."),
        two("Red Dead Redemption 2 reuses the epitaph as a mission title: \"Blessed are the Peacemakers\" is a chapter 3 mission given by [[micah-bell|Micah Bell]] at Clemens Point.",
            "Red Dead Redemption 2 reprend l'épitaphe comme titre de mission : \"Blessed are the Peacemakers\" est une mission du chapitre 3, confiée par [[micah-bell|Micah Bell]] à Clemens Point."),
        two("His default revolver in Red Dead Redemption, the Cattleman Revolver, is the game's version of the Colt Single Action Army, a gun nicknamed the \"Peacemaker\", the same word as on his grave.",
            "Son revolver de départ dans Red Dead Redemption, le Cattleman Revolver, est la version du jeu du Colt Single Action Army, une arme surnommée \"Peacemaker\", le mot même de son épitaphe."),
        two("Rob Wiethoff told Polygon in 2013 that people on the first game's set kept saying \"Remember in GTA when this happened\". He did not even know what GTA was, and had to take the director aside to ask.",
            "Rob Wiethoff a raconté à Polygon en 2013 que sur le tournage du premier jeu, on lui parlait sans cesse de ce qui se passait \"dans GTA\". Il ne savait même pas ce qu'était GTA, et a dû prendre le réalisateur à part pour lui demander."),
    ]},
    {"h4": two("Red Dead Redemption", "Red Dead Redemption")},
    {"ul": [
        two("In the first trailers released before the game, John looks younger and thinner than in the final version.",
            "Dans les premières bandes-annonces diffusées avant la sortie, John paraît plus jeune et plus mince que dans la version finale."),
        two("The same early trailers use different voices for several characters: John, [[leigh-johnson|Leigh Johnson]], [[abraham-reyes|Abraham Reyes]], [[luisa-fortuna|Luisa Fortuna]], [[bonnie-macfarlane|Bonnie MacFarlane]] and her father Drew MacFarlane.",
            "Ces mêmes bandes-annonces prêtent une autre voix à plusieurs personnages : John, [[leigh-johnson|Leigh Johnson]], [[abraham-reyes|Abraham Reyes]], [[luisa-fortuna|Luisa Fortuna]], [[bonnie-macfarlane|Bonnie MacFarlane]] et son père, Drew MacFarlane."),
        two("John opens the game on a steamboat that docks at Blackwater, escorted by two lawmen. He then takes the train to Armadillo (\"Exodus in America\").",
            "Le jeu s'ouvre sur John débarquant d'un bateau à vapeur à Blackwater, escorté par deux représentants de la loi. Il prend ensuite le train pour Armadillo (\"Exodus in America\")."),
        two("Outside Fort Mercer in \"Exodus in America\", John tells Bill Williamson \"I implore you\". Bill mocks the phrase, reminds John that he \"always were one for fancy words\", and declares that he is now in charge, with no more Dutch.",
            "Devant Fort Mercer, dans \"Exodus in America\", John lance à Bill Williamson \"I implore you\" (\"je t'en conjure\"). Bill se moque de la formule, lui rappelle qu'il a toujours aimé les grands mots et proclame que c'est désormais lui le chef, sans Dutch."),
        two("In \"Women and Cattle\", he tells Bonnie that his father, a Scot born on the boat to New York, hated the English for what they had done to great-grandparents he had never met.",
            "Dans \"Women and Cattle\", il raconte à Bonnie que son père, un Écossais né sur le bateau qui l'amenait à New York, haïssait les Anglais pour ce qu'ils avaient fait à des arrière-grands-parents qu'il n'avait jamais connus."),
        two("In \"Bear One Another's Burdens\", [[edgar-ross|Edgar Ross]] calls him \"the whore's son\", says his files credit him with \"at least 40\" bank robberies, and accuses him of killing hundreds of innocent people.",
            "Dans \"Bear One Another's Burdens\", [[edgar-ross|Edgar Ross]] le traite de \"fils de pute\", affirme que ses dossiers lui attribuent \"au moins 40\" braquages de banque et l'accuse d'avoir tué des centaines d'innocents."),
        two("In \"Father Abraham\", he tells Luisa Fortuna that he has \"a son at home and a daughter in heaven\". The game never gives the daughter's name.",
            "Dans \"Father Abraham\", il confie à Luisa Fortuna avoir \"un fils à la maison et une fille au ciel\". Le jeu ne donne jamais le prénom de cette fille."),
        two("At the last meeting of \"I Know You\", the Strange Man looks down on the ranch from the hill at Beecher's Hope and says more than once that it is a fine spot. John's grave is later dug on that hill.",
            "Lors de la dernière rencontre de \"I Know You\", l'homme mystérieux regarde le ranch depuis la colline de Beecher's Hope et répète que l'endroit est beau. C'est sur cette colline que John sera enterré."),
        two("John cannot swim in Red Dead Redemption: he dies as soon as the water rises above his chin.",
            "John ne sait pas nager dans Red Dead Redemption : il meurt dès que l'eau dépasse son menton."),
        two("Rob Wiethoff said during a live stream on his YouTube channel that the pose of John lying on his back with one leg straight and the other bent, which he calls \"Number Four\", is a nod to his wife, Tayler. He worked it into the motion capture whenever he could.",
            "Rob Wiethoff a raconté, lors d'un direct sur sa chaîne YouTube, que la pose de John allongé sur le dos, une jambe tendue et l'autre pliée, qu'il appelle \"Number Four\", est un clin d'œil à sa femme, Tayler. Il la glissait dans la capture de mouvement dès qu'il le pouvait."),
        two("The pose is easiest to see in \"The Last Enemy That Shall Be Destroyed\", when John falls to the ground.",
            "La posture se repère le plus facilement dans \"The Last Enemy That Shall Be Destroyed\", quand John s'effondre."),
        two("In the final cutscene of \"I Know You\", John fires at the Strange Man, who is unharmed. The mission has to be finished before \"The Last Enemy That Shall Be Destroyed\", and it is the only stranger mission that Jack cannot play.",
            "Dans la dernière cinématique de \"I Know You\", John tire sur l'homme mystérieux, qui n'a pas une égratignure. La mission doit être terminée avant \"The Last Enemy That Shall Be Destroyed\", et c'est la seule mission d'inconnu que Jack ne peut pas jouer."),
        two("The stranger mission \"Water and Honesty\" can be started as John or as Jack. When Jack plays it, he says the same line as his father: \"We all need friends, old timer. We die alone, but we live among men.\"",
            "La mission d'inconnu \"Water and Honesty\" peut se jouer avec John ou avec Jack. Avec Jack, celui-ci reprend mot pour mot la réplique de son père : \"We all need friends, old timer. We die alone, but we live among men.\""),
        two("In \"Great Men are Not Always Wise\", after seeing Dutch again, John tells Ross that Dutch reminds him of Ross himself, calling him a \"violent piece of shit who went and confused himself with God\".",
            "Dans \"Great Men are Not Always Wise\", après avoir revu Dutch, John dit à Ross que Dutch lui rappelle Ross lui-même, et le traite de \"violent piece of shit who went and confused himself with God\" (une sale brute violente qui s'est prise pour Dieu)."),
        two("In \"Pestilence\", Abigail says she has been cooking the same dish for 15 years in the hope of poisoning him. John answers that it tastes bad enough to kill a man, then calls her \"my angel\" before going to shoot the crows raiding the silo.",
            "Dans \"Pestilence\", Abigail affirme cuisiner le même plat depuis 15 ans dans l'espoir de l'empoisonner. John répond que c'est assez mauvais pour tuer un homme, puis l'appelle \"my angel\" avant d'aller abattre les corbeaux qui pillent le silo."),
    ]},
    {"h4": two("Undead Nightmare", "Undead Nightmare")},
    {"ul": [
        two("If John goes back to Beecher's Hope before the final mission, he stops at the front door and hears Ayauhtéotl say \"Did you listen to a word I said?\", even though he only meets her properly in that last mission.",
            "Si John revient à Beecher's Hope avant la dernière mission, il s'arrête devant la porte et entend Ayauhtéotl lui demander s'il a écouté un seul mot de ce qu'elle a dit, alors qu'il ne la rencontre vraiment qu'au cours de cette dernière mission."),
    ]},
    {"h4": two("Red Dead Redemption 2", "Red Dead Redemption 2")},
    {"ul": [
        two("John has his own musical theme, heard in several of his missions. Four characters in the game have a leitmotif: John, [[sadie-adler|Sadie Adler]], [[colm-odriscoll|Colm O'Driscoll]] and [[angelo-bronte|Angelo Bronte]].",
            "John a son propre thème musical, entendu dans plusieurs de ses missions. Quatre personnages du jeu ont un leitmotiv : John, [[sadie-adler|Sadie Adler]], [[colm-odriscoll|Colm O'Driscoll]] et [[angelo-bronte|Angelo Bronte]]."),
        two("Playable John drowns in deep water. His stamina core empties immediately, fortified or not, and his health follows within seconds.",
            "Le John jouable se noie en eau profonde. Son endurance se vide instantanément, même renforcée, et sa santé suit en quelques secondes."),
        two("The non-playable John can swim: players who get him as a companion through a glitch and lead him into deep water see him swim normally.",
            "Le John non jouable, lui, sait nager : les joueurs qui l'obtiennent comme compagnon grâce à un bug et l'emmènent en eau profonde le voient nager normalement."),
        two("The mechanic is written into the story. At Clemens Point, Arthur remarks in a camp exchange that the nearby water makes John nervous. Arthur also mentions it during poker games and in \"The Sheep and the Goats\".",
            "Cette contrainte de jeu est intégrée au récit. À Clemens Point, Arthur remarque lors d'un échange au camp que la proximité de l'eau rend John nerveux. Il y fait aussi allusion pendant les parties de poker et dans \"The Sheep and the Goats\"."),
        two("John's Dead Eye sound effect is the original one from Red Dead Redemption, not the one used for Arthur.",
            "L'effet sonore du Dead Eye de John est celui de Red Dead Redemption, pas celui d'Arthur."),
        two("If Arthur provokes the camp too often, John can punch him and throw him out, a reaction shared with [[lenny-summers|Lenny]], [[javier-escuella|Javier]], [[bill-williamson|Bill]], [[sean-macguire|Sean]] and [[charles-smith|Charles]].",
            "Si Arthur provoque trop souvent le camp, John peut le frapper et le mettre dehors, comme [[lenny-summers|Lenny]], [[javier-escuella|Javier]], [[bill-williamson|Bill]], [[sean-macguire|Sean]] et [[charles-smith|Charles]]."),
        two("John's 1907 journal looks less polished than Arthur's: plainer handwriting, simpler sketches and frequent crossings-out. A few drawings, among them a Pekin duck and a Merino sheep, are as careful as Arthur's.",
            "Le journal de John en 1907 est moins soigné que celui d'Arthur : écriture plus simple, croquis plus sommaires, ratures fréquentes. Quelques dessins, dont un canard de Pékin et un mouton mérinos, sont toutefois aussi travaillés que ceux d'Arthur."),
        two("The holster on the gunbelt he wears when he is rescued in Colter is shaped for the Mauser Pistol.",
            "L'étui du ceinturon qu'il porte lors de son sauvetage à Colter est taillé pour le Mauser Pistol."),
        two("To urge his horse on, playable John clicks his tongue: unlike Arthur, and unlike his own 1911 self, he has no spoken line for it. He does speak to slow the horse down.",
            "Pour faire accélérer son cheval, le John jouable claque de la langue : contrairement à Arthur, et à lui-même en 1911, il n'a aucune réplique pour cela. Il parle en revanche pour le ralentir."),
        two("After leaving the gang in 1899, John and his family went to the Yukon for the gold rush and made no profit, as Sadie recalls in \"Gainful Employment\". The real Klondike Gold Rush took place in the Yukon and ended in 1899.",
            "Après avoir quitté le gang en 1899, John et sa famille partent au Yukon pour la ruée vers l'or, sans rien y gagner, comme le rappelle Sadie dans \"Gainful Employment\". La véritable ruée vers l'or du Klondike a eu lieu au Yukon et s'est achevée en 1899."),
        two("At Pronghorn Ranch in 1907, John works under the alias Jim Milton. He blurts out his real first name before correcting himself, and Sadie later mocks the alias when they meet again in Valentine. The name returns in the mission title \"Jim Milton Rides, Again?\".",
            "Au Pronghorn Ranch, en 1907, John travaille sous le nom d'emprunt de Jim Milton. Il laisse échapper son vrai prénom avant de se reprendre, et Sadie se moque de ce pseudonyme quand ils se retrouvent à Valentine. Le nom revient dans le titre de la mission \"Jim Milton Rides, Again?\"."),
        two("At the post office in Strawberry, John gives his real name although he is a wanted man, and is recognised by a man whose brother he killed.",
            "Au bureau de poste de Strawberry, John donne son vrai nom alors qu'il est recherché, et se fait reconnaître par un homme dont il a tué le frère."),
        two("Playable John borrows several of Arthur's assets: his body model, his stance and his walking and running animations at Beecher's Hope, and even Arthur's retching sound when he eats Oleander Sage, although the game files hold a separate one for John.",
            "Le John jouable emprunte plusieurs éléments à Arthur : son modèle corporel, sa posture et ses animations de marche et de course à Beecher's Hope, et jusqu'à son bruit de haut-le-cœur quand il mange de l'Oleander Sage, alors que les fichiers du jeu en contiennent un propre à John."),
        two("When Pinkerton agent [[andrew-milton|Andrew Milton]] visits the Clemens Point camp in \"The Battle of Shady Belle\" and asks who he is, John answers \"Rip Van Winkle\". Rip Van Winkle is the title character of an 1819 short story by Washington Irving: he falls asleep in the mountains and wakes up twenty years later.",
            "Quand l'agent Pinkerton [[andrew-milton|Andrew Milton]] se présente au camp de Clemens Point dans \"The Battle of Shady Belle\" et lui demande qui il est, John répond \"Rip Van Winkle\". C'est le héros d'une nouvelle de Washington Irving parue en 1819, qui s'endort dans la montagne et se réveille vingt ans plus tard."),
        two("In the epilogue, returning to an old camp site triggers flashbacks: John hears lines spoken by gang members during the chapter set at that camp.",
            "Dans l'épilogue, revenir sur un ancien campement déclenche des réminiscences : John entend des répliques des membres du gang tirées du chapitre qui s'y déroulait."),
        two("Antagonized at Beecher's Hope, Abigail sometimes snaps back with his full name, which the subtitles misspell as \"John Martson\".",
            "Quand John la provoque à Beecher's Hope, Abigail lui répond parfois en l'appelant par son nom complet, que les sous-titres écrivent \"John Martson\"."),
        two("By 1907 the wolf scars have closed into two lines across one cheek and one on the upper lip, where his beard no longer grows. Micah and Sean call him \"Scarface\" because of them.",
            "En 1907, les cicatrices laissées par les loups se sont refermées en deux traits sur une joue et un sur la lèvre supérieure, où la barbe ne repousse plus. Micah et Sean l'appellent \"Scarface\" à cause d'elles."),
    ]},
    {"h4": two("Red Dead Online", "Red Dead Online")},
    {"ul": [
        two("The Clelland outfit in Red Dead Online is modelled on John's default cowboy outfit from Red Dead Redemption.",
            "La tenue Clelland de Red Dead Online s'inspire de la tenue de cow-boy par défaut de John dans Red Dead Redemption."),
    ]},
]

BLOCKS_MEDIA = [
    {"h3": two("The Man from Blackwater (2010)", "The Man from Blackwater (2010)")},
    {"p": two("John is the lead character of Red Dead Redemption: The Man from Blackwater, a short film directed by John Hillcoat and edited by Barry Alexander Brown. It runs about half an hour and was made entirely with the game's engine, from cutscenes, gameplay footage and scenes shot from new angles. Fox broadcast it in the United States at midnight on May 29, 2010, eleven days after the game's release. In the United Kingdom, 5USA aired it on June 5, 2010. Rockstar and IGN then made it available to download on their websites. Hillcoat had previously directed The Proposition (2005), an Australian western.",
               "John est le personnage principal de Red Dead Redemption: The Man from Blackwater, un court métrage réalisé par John Hillcoat et monté par Barry Alexander Brown. Long d'environ une demi-heure, il a été entièrement fabriqué avec le moteur du jeu, à partir de cinématiques, de séquences de jeu et de plans tournés sous de nouveaux angles. Fox le diffuse aux États-Unis le 29 mai 2010 à minuit, onze jours après la sortie du jeu. Au Royaume-Uni, 5USA le programme le 5 juin 2010. Rockstar et IGN le proposent ensuite en téléchargement sur leurs sites. Hillcoat avait auparavant réalisé The Proposition (2005), un western australien.")},
    {"p": two("The film follows the first act of the game in New Austin. John teams up with Marshal [[leigh-johnson|Leigh Johnson]], [[nigel-west-dickens|Nigel West Dickens]] and [[seth-briars|Seth Briars]] to take Fort Mercer from [[bill-williamson|Bill Williamson]]. It reuses scenes from \"Old Swindler Blues\", \"Political Realities in Armadillo\", \"Spare the Rod, Spoil the Bandit\", \"Exhuming and Other Fine Hobbies\" and \"The Assault on Fort Mercer\", in a different order from the game. Several scenes are exclusive to the film: John scouting Fort Mercer, flashbacks of the gang robbing the Blackwater bank and approaching a train, and a closing shot of John at a barred window as Bill rides away. In the film, John mostly carries a LeMat Revolver and wears the Duster Coat, rather than his starting Cattleman Revolver and cowboy outfit.",
               "Le film reprend le premier acte du jeu, dans le New Austin. John s'allie au marshal [[leigh-johnson|Leigh Johnson]], à [[nigel-west-dickens|Nigel West Dickens]] et à [[seth-briars|Seth Briars]] pour prendre Fort Mercer à [[bill-williamson|Bill Williamson]]. Il réutilise des scènes de \"Old Swindler Blues\", \"Political Realities in Armadillo\", \"Spare the Rod, Spoil the Bandit\", \"Exhuming and Other Fine Hobbies\" et \"The Assault on Fort Mercer\", dans un ordre différent de celui du jeu. Plusieurs séquences sont propres au film : John en repérage devant Fort Mercer, des flash-back du gang braquant la banque de Blackwater puis approchant d'un train, et un plan final de John derrière une fenêtre à barreaux tandis que Bill s'enfuit à cheval. John y porte surtout un LeMat Revolver et le Duster Coat, au lieu du Cattleman Revolver et de la tenue de cow-boy du début du jeu.")},
    {"h3": two("Multiplayer and Red Dead Online", "Multijoueur et Red Dead Online")},
    {"p": two("John became a playable multiplayer model in Red Dead Redemption with the Liars and Cheats pack, released on September 21, 2010. The pack added 15 story characters to the Outfitter, sorted into two groups. John sits in the \"Redemption\" group with Abigail, Jack, Bonnie MacFarlane, Leigh Johnson, Luisa Fortuna, Nigel West Dickens and Seth Briars. The Undead Nightmare pack then added an undead version of him to the \"Zombies\" section. Red Dead Online, the online mode of Red Dead Redemption 2, does not feature John as a character. Its Clelland outfit is modelled on his default cowboy outfit from the first game.",
               "John devient un modèle jouable en multijoueur dans Red Dead Redemption avec le pack Liars and Cheats, sorti le 21 septembre 2010. Ce pack ajoute à l'Outfitter 15 personnages de l'histoire, répartis en deux groupes. John figure dans le groupe \"Redemption\", avec Abigail, Jack, Bonnie MacFarlane, Leigh Johnson, Luisa Fortuna, Nigel West Dickens et Seth Briars. Le pack Undead Nightmare ajoute ensuite une version mort-vivant de John dans la section \"Zombies\". Red Dead Online, le mode en ligne de Red Dead Redemption 2, ne met pas John en scène. Sa tenue Clelland reprend toutefois la tenue de cow-boy par défaut du premier jeu.")},
    {"h3": two("References in other Rockstar games", "Clins d'œil dans d'autres jeux Rockstar")},
    {"ul": [
        two("Grand Theft Auto Online: John Marston is one of the fathers available in the character creator's heritage options. The player's face is generated from the features of the chosen father and mother.",
            "Grand Theft Auto Online : John Marston fait partie des pères proposés dans les options d'hérédité de l'éditeur de personnage. Le visage du joueur est généré à partir des traits du père et de la mère choisis."),
        two("Grand Theft Auto V: in the mission \"Daddy's Little Girl\", an employee at a bicycle rental stand wears a shirt with a picture of John on it.",
            "Grand Theft Auto V : dans la mission \"Daddy's Little Girl\", un employé d'un stand de location de vélos porte un t-shirt à l'effigie de John."),
        two("L.A. Noire (2011, published by Rockstar Games): in the opening cutscene, a Hollywood actor playing a cowboy wears a parody of John's hat.",
            "L.A. Noire (2011, édité par Rockstar Games) : dans la cinématique d'ouverture, un acteur hollywoodien qui joue un cow-boy porte une parodie du chapeau de John."),
    ]},
    {"h3": two("Re-releases and the cast", "Rééditions et équipe du jeu")},
    {"p": two("Red Dead Redemption, with Undead Nightmare included, was re-released on PlayStation 4 and Nintendo Switch on August 17, 2023, then on Windows on October 29, 2024, which made John's original story playable on current platforms. Rob Wiethoff, who plays John, runs a YouTube channel on which he has streamed full playthroughs of Red Dead Redemption, including the finale. Gabriel Sloyer, who plays [[javier-escuella|Javier Escuella]], has said that John is his favourite character.",
               "Red Dead Redemption, avec Undead Nightmare, ressort sur PlayStation 4 et Nintendo Switch le 17 août 2023, puis sur Windows le 29 octobre 2024, ce qui rend l'histoire originale de John jouable sur les plateformes actuelles. Rob Wiethoff, qui incarne John, anime une chaîne YouTube sur laquelle il a diffusé des parties complètes de Red Dead Redemption, finale comprise. Gabriel Sloyer, interprète de [[javier-escuella|Javier Escuella]], a déclaré que John était son personnage préféré.")},
]
