def two(en, fr): return {"en": en, "fr": fr}

# ---------------------------------------------------------------- PERSONALITY
BLOCKS_PERSONALITY = [
    {"h3": two("Personality", "Personnalité")},
    {"p": two(
        "Rockstar's official description of the 1899 John calls him \"shrewd, fearless and strong-willed\" and names him, with Arthur Morgan, as one of Dutch's two \"proudest protégés\". The Complete Official Guide to Red Dead Redemption 2 adds that he \"isn't always sure about where his priorities lie\" between the gang and his family. The Game of the Year Edition guide to Red Dead Redemption describes the 1911 John as a former believer in Dutch's ideas who gave up that life to become a farmer, and as \"a man who understands that human beings change\".",
        "La présentation officielle de Rockstar décrit le John de 1899 comme un homme \"rusé, sans peur et obstiné\", et le range avec Arthur Morgan parmi les deux protégés dont Dutch est le plus fier. Le guide officiel de Red Dead Redemption 2 précise qu'il ne sait pas toujours où sont ses priorités, entre le gang et sa famille. Le guide de l'édition Game of the Year de Red Dead Redemption présente le John de 1911 comme un ancien fidèle des idées de Dutch, qui a renoncé à cette vie pour devenir fermier, et comme un homme qui sait que les êtres humains changent.")},
    {"h4": two("1899", "1899")},
    {"p": two(
        "In Red Dead Redemption 2, John is a gang member who acts on impulse and often keeps his family at a distance. Bedridden after the wolf attack, he answers Dutch's concern about his scars with \"I was always ugly, Dutch... it's just a scratch\" in \"Who the Hell is Leviticus Cornwall?\", and still asks to join the train robbery before Dutch orders him to rest. He has doubts about being Jack's father, and Abigail's reproaches about his absences irritate him. At Sean's homecoming party he gets drunk and argues with Abigail. He can also flirt with Karen Jones there, who turns him down because of Abigail.",
        "Dans Red Dead Redemption 2, John est un membre du gang qui agit sur un coup de tête et tient souvent sa famille à distance. Alité après l'attaque des loups, il répond à Dutch, inquiet pour ses cicatrices, qu'il a \"toujours été moche\" et que ce n'est \"qu'une égratignure\", dans \"Who the Hell is Leviticus Cornwall?\". Il demande malgré tout à participer à l'attaque du train, avant que Dutch ne lui ordonne de se reposer. Il doute d'être le père de Jack, et les reproches d'Abigail sur ses absences l'agacent. À la fête donnée pour le retour de Sean, il s'enivre et se dispute avec Abigail ; il peut aussi y draguer Karen Jones, qui le repousse par égard pour Abigail.")},
    {"p": two(
        "John also shows practical sense. He comes up with the idea of parking a stolen oil wagon across the tracks to stop a train, and in \"The Sheep and the Goats\" he negotiates the Valentine auctioneer's commission down from 25 to 18 percent. When the Braithwaite horses sell for 700 dollars instead of the promised 5,000 in \"Horse Flesh for Dinner\", he accepts the money, which annoys Arthur. After the Valentine shootout, Charles reports in \"A Strange Kindness\" that John went back alone to the auction yard to collect the money for the sheep. In Saint Denis, he openly distrusts Angelo Bronte.",
        "John fait aussi preuve de sens pratique. C'est lui qui a l'idée de garer un wagon-citerne volé en travers des voies pour arrêter un train, et dans \"The Sheep and the Goats\", il obtient du commissaire-priseur de Valentine que sa commission passe de 25 à 18 %. Quand les chevaux des Braithwaite ne rapportent que 700 dollars au lieu des 5 000 promis, dans \"Horse Flesh for Dinner\", il prend l'argent, ce qui agace Arthur. Après la fusillade de Valentine, Charles raconte dans \"A Strange Kindness\" que John est retourné seul au parc aux enchères pour toucher le prix des moutons. À Saint-Denis, il ne cache pas sa méfiance envers Angelo Bronte.")},
    {"p": two(
        "Jack's kidnapping changes his behavior. On the ride to Shady Belle in \"The Battle of Shady Belle\", he tells Arthur he has been a bad father. When Jack is returned, he asks Abigail and Jack to share his room from then on. His relationship with Dutch degrades in parallel: he saw Dutch kill a young woman during the Blackwater ferry robbery, he questions Dutch's decisions, and in a camp scene Dutch reminds him coldly that the gang comes first. In chapter 6, he tells Arthur that Dutch could have saved him during the Saint Denis bank robbery and chose not to. Back at Beaver Hollow in the final mission, he shouts \"You left me... you left me to die!\" In the ending where Arthur goes back for the money, John refuses to follow him: \"I got a family, that's more important.\"",
        "L'enlèvement de Jack modifie son comportement. Sur la route de Shady Belle, dans \"The Battle of Shady Belle\", il avoue à Arthur avoir été un mauvais père. Une fois Jack rendu, il propose à Abigail et à Jack de partager désormais sa chambre. Sa relation avec Dutch se dégrade en parallèle : il l'a vu abattre une jeune femme lors du braquage du ferry de Blackwater, il conteste ses décisions, et dans une scène de camp, Dutch lui rappelle sèchement que le gang passe avant tout. Au chapitre 6, il confie à Arthur que Dutch aurait pu le sauver lors du braquage de la banque de Saint-Denis, et ne l'a pas fait. De retour à Beaver Hollow lors de la dernière mission, il lui lance qu'il l'a laissé mourir. Dans la fin où Arthur retourne chercher l'argent, John refuse de le suivre : sa famille, dit-il, compte davantage.")},
    {"h4": two("1907", "1907")},
    {"p": two(
        "Eight years later, John wants an honest life but struggles to keep one. In \"The Wheel\", Abigail asks him whether his only options are \"Tahiti or killing\", and he tells her: \"I am always honest... maybe not always good... but I'm always honest.\" In \"Fatherhood, For Idiots\", she reproaches him for showing \"the entire world\" that he is not Jimmy Milton wherever they settle. His journal from that period records that he killed a man \"because he looked at me funny\" and that \"Jack don't like me, and Abigail cannot stand me, or is it the reverse?\". He gives his real name at the Strawberry post office, and at Hanging Dog Ranch he kills the Laramie gang leader, who ambushes him in the barn, with the man's own shotgun.",
        "Huit ans plus tard, John veut une vie honnête mais peine à s'y tenir. Dans \"The Wheel\", Abigail lui demande si ses seules options sont \"Tahiti ou tuer\", et il lui répond qu'il est toujours honnête, \"peut-être pas toujours bon\", mais toujours honnête. Dans \"Fatherhood, For Idiots\", elle lui reproche de montrer à tout le monde qu'il n'est pas Jimmy Milton, partout où ils s'installent. Son journal de l'époque note qu'il a tué un homme parce que celui-ci l'avait \"regardé de travers\", et que \"Jack ne m'aime pas, et Abigail ne me supporte pas, ou c'est l'inverse ?\". Il donne son vrai nom au bureau de poste de Strawberry et, à Hanging Dog Ranch, il tue avec son propre fusil le chef du gang Laramie, qui l'attendait en embuscade dans la grange.")},
    {"p": two(
        "After Abigail leaves with Jack, John takes a bank loan to buy Beecher's Hope and writes to her. He builds the ranch with Uncle and Charles, spends time fishing with Jack, and proposes to Abigail on a lake near Blackwater, after telling Sadie he intends to marry her. He keeps the promise made to Sadie in 1899 about Micah: in \"Gainful Employment\" he tells her \"I know what we said we'd do. That ain't changed.\" He leaves for Mount Hagen despite Abigail's objections. After Dutch shoots Micah, John tries to thank him, and Dutch leaves without answering. Back at the ranch, he tells Abigail: \"It's over, Abigail. It's all over.\"",
        "Après le départ d'Abigail et de Jack, John contracte un emprunt pour acheter Beecher's Hope et lui écrit. Il bâtit le ranch avec Uncle et Charles, va pêcher avec Jack et demande Abigail en mariage sur un lac près de Blackwater, après avoir annoncé à Sadie son intention de l'épouser. Il tient la promesse faite à Sadie en 1899 au sujet de Micah : dans \"Gainful Employment\", il lui assure que ce qu'ils s'étaient dit n'a pas changé. Il part pour le mont Hagen malgré les objections d'Abigail. Après que Dutch a tiré sur Micah, John tente de le remercier ; Dutch s'en va sans un mot. De retour au ranch, il dit à Abigail que tout est fini.")},
    {"h4": two("1911", "1911")},
    {"p": two(
        "In Red Dead Redemption, John is terse with the people he works for and states his objections openly. He threatens Irish to make him sober up and hits him when Irish holds up two nuns. He shows disgust at Seth Briars's grave robbing and criticizes Nigel West Dickens's swindles. When Dickens cites Waldo Emerson in \"Liars, Cheats and Other Proud Americans\", John calls Emerson \"another fool with his head in the clouds\" and explains that he reads \"a little\", taught by Dutch. He tells Marshal Leigh Johnson that killing is a crime \"unless it's ordered by a court of law\", and states that \"most men can't handle power\". In Mexico, he answers the speeches of Abraham Reyes and Colonel Allende with sarcasm, while working for both camps to find Bill and Javier.",
        "Dans Red Dead Redemption, John est laconique avec ceux pour qui il travaille et dit ouvertement ce qu'il désapprouve. Il menace Irish pour qu'il dessoûle, et le frappe quand Irish braque deux religieuses. Il montre son dégoût pour les pillages de tombes de Seth Briars et critique les escroqueries de Nigel West Dickens. Quand Dickens cite Waldo Emerson, dans \"Liars, Cheats and Other Proud Americans\", John traite Emerson de rêveur la tête dans les nuages, et précise qu'il lit \"un peu\", grâce à Dutch. Il fait remarquer au marshal Leigh Johnson que tuer est un crime, \"sauf sur ordre d'un tribunal\", et affirme que la plupart des hommes ne savent pas gérer le pouvoir. Au Mexique, il répond par l'ironie aux discours d'Abraham Reyes et du colonel Allende, tout en travaillant pour les deux camps afin de retrouver Bill et Javier.")},
    {"p": two(
        "He is formal with women: he keeps calling Bonnie MacFarlane \"Miss MacFarlane\" although she asks him to use her first name, and he tells her that he is married and has a son. In \"Women and Cattle\" he tells her about his parents and his past, and says: \"People don't forget. Nothing gets forgiven.\" He describes the automobile as slow and prefers his horse. Back at Beecher's Hope, he tries to teach Jack to hunt and ride and tells him about a bear he once hunted in Tall Trees, while Jack talks about his books. The player decides in several scenes whether he kills Bill, Javier and Captain de Santa himself or leaves their fate to others, and his honor depends on the player's actions.",
        "Il reste cérémonieux avec les femmes : il continue d'appeler Bonnie MacFarlane \"Miss MacFarlane\" alors qu'elle lui demande d'utiliser son prénom, et il lui apprend qu'il est marié et père d'un fils. Dans \"Women and Cattle\", il lui parle de ses parents et de son passé, et lâche : \"People don't forget. Nothing gets forgiven\" (les gens n'oublient pas, rien n'est pardonné). Il juge l'automobile lente et lui préfère son cheval. De retour à Beecher's Hope, il essaie d'apprendre à Jack à chasser et à monter, et lui raconte un ours qu'il a chassé à Tall Trees, pendant que Jack lui parle de ses livres. Dans plusieurs scènes, le joueur décide si John tue lui-même Bill, Javier et le capitaine de Santa ou s'il laisse ce soin à d'autres, et son honneur dépend des actions du joueur.")},
    {"h4": two("Names and nicknames", "Noms et surnoms")},
    {"p": two(
        "Besides Jim Milton, the alias he works under at Pronghorn Ranch in 1907, John collects names from the people around him. Arthur calls him \"Little Johnny Marston\" and \"Wolf Man\", Micah and Sean \"Scarface\". Abigail turns the alias into \"Jimmy Milton\" when she mocks it, and she and Uncle sometimes shorten him to \"J.M.\", the initials Sadie also uses in her telegrams. After John lets his real first name slip, Tom Dickens calls him \"'John' Jim\". Uncle nicknames him \"The Rock Farmer\", and the banker Ansel Atherton calls him \"the man with two names\". In 1911, Irish calls him \"Johnny\" and \"Johnny Boy\", and Edgar Ross \"old boy\".",
        "Outre Jim Milton, le nom d'emprunt sous lequel il travaille au Pronghorn Ranch en 1907, John accumule les surnoms. Arthur l'appelle \"Little Johnny Marston\" et \"Wolf Man\", Micah et Sean \"Scarface\". Abigail transforme l'alias en \"Jimmy Milton\" quand elle s'en moque, et Uncle et elle le réduisent parfois à \"J.M.\", les initiales qu'emploie aussi Sadie dans ses télégrammes. Après que John a laissé échapper son vrai prénom, Tom Dickens l'appelle \"'John' Jim\". Uncle le surnomme \"The Rock Farmer\" (le fermier des cailloux), et le banquier Ansel Atherton \"l'homme aux deux noms\". En 1911, Irish l'appelle \"Johnny\" et \"Johnny Boy\", et Edgar Ross \"old boy\".")},
    {"h4": two("What the creators said", "Ce qu'en disent ses créateurs")},
    {"p": two(
        "In a May 2010 USA Today Q&A, Dan Houser explained that the game offers John no brothels because he is \"a family man\". Technical director Ted Carson told GameSpot in 2010 that the team wanted a nuanced character rather than a plain hero or villain, one with \"a foot in both the old world and the world that was to come\". For Red Dead Redemption 2, Rob Wiethoff told The Hollywood Reporter in November 2018 that he based the younger John on the older friends of his sister, whose approval he sought as a teenager, in the same way John seeks the approval of the older gang members.",
        "Dans un entretien à USA Today, en mai 2010, Dan Houser explique que le jeu ne propose pas de maison close à John, parce qu'il est un père de famille. Le directeur technique Ted Carson explique à GameSpot la même année que l'équipe voulait un personnage nuancé plutôt qu'un héros ou un méchant tout d'une pièce, avec un pied dans l'ancien monde et un dans celui qui arrive. Pour Red Dead Redemption 2, Rob Wiethoff raconte au Hollywood Reporter, en novembre 2018, qu'il a construit le jeune John à partir des amis plus âgés de sa sœur, dont il recherchait l'approbation adolescent, comme John recherche celle des aînés du gang.")},
]

# ---------------------------------------------------------------- APPEARANCE
BLOCKS_APPEARANCE = [
    {"h3": two("Appearance", "Apparence")},
    {"p": two(
        "The scars are the one constant in John's appearance. Wolves inflict them in the Ambarino mountains in the first chapter of Red Dead Redemption 2, and he carries them until his death in 1911. Micah Bell and Sean MacGuire call him \"Scarface\" because of them, and Arthur Morgan calls him \"Wolf Man\". The John shown in the first Red Dead Redemption trailers looked younger and thinner than the one in the released game.",
        "Les cicatrices sont le seul élément qui ne change jamais chez John. Les loups les lui infligent dans les montagnes de l'Ambarino, au premier chapitre de Red Dead Redemption 2, et il les porte jusqu'à sa mort en 1911. Micah Bell et Sean MacGuire l'appellent \"Scarface\" (le balafré) à cause d'elles, Arthur Morgan \"Wolf Man\" (l'homme-loup). Dans les premières bandes-annonces de Red Dead Redemption, John paraissait plus jeune et plus mince que dans le jeu final.")},
    {"h4": two("1899", "1899")},
    {"p": two(
        "Arthur and Javier find him in the snow with his face torn open, wrapped in a heavy black coat buttoned to the neck. Blood-soaked bandages then cover half his face, and he still has them on the stretcher that carries him out of Colter. By chapter 2 the wounds have been stitched. His hair is near-black, down to the collar and parted on the right. He starts with a thin goatee and sideburns, which give way to a few days' stubble from chapter 3. At the end of chapter 6, before they part, Arthur hands him his own hat and satchel.",
        "Arthur et Javier le retrouvent dans la neige, le visage lacéré, emmitouflé dans un épais manteau noir boutonné jusqu'au cou. Des pansements gorgés de sang lui masquent ensuite la moitié du visage ; il les porte encore sur la civière qui l'évacue de Colter. Au chapitre 2, les plaies sont recousues. Ses cheveux, presque noirs, descendent jusqu'au col, avec une raie à droite. Il porte d'abord un bouc clairsemé et des favoris, remplacés à partir du chapitre 3 par une barbe de quelques jours. À la fin du chapitre 6, avant qu'ils se séparent, Arthur lui confie son propre chapeau et sa sacoche.")},
    {"table": {"head": [two("Outfit", "Tenue"), two("When", "Quand")], "rows": [
        [two("Orange union suit, scout coat or black leather jacket, dark trousers", "Sous-vêtement long orange, veste d'éclaireur ou blouson de cuir noir, pantalon sombre"),
         two("Chapter 2, while his face heals", "Chapitre 2, pendant la cicatrisation")],
        [two("Grey coat, black shirt, white union suit, orange leather vest, striped light grey trousers, worn gambler hat", "Manteau gris, chemise noire, sous-vêtement long blanc, gilet de cuir orange, pantalon gris clair à rayures, vieux chapeau de joueur"),
         two("Most of the gang's story; some scenes show only the black shirt, or the white union suit with a beige vest", "L'essentiel de l'histoire du gang ; certaines scènes ne montrent que la chemise noire, ou le sous-vêtement blanc avec un gilet beige")],
        [two("Dark blue suit, white shirt, pinstriped vest, gambler hat with a silver band", "Costume bleu foncé, chemise blanche, gilet à fines rayures, chapeau de joueur cerclé d'argent"),
         two("\"Banking, The Old American Art\", the Saint Denis bank robbery", "\"Banking, The Old American Art\", le braquage de la banque de Saint-Denis")],
        [two("Black and white striped uniform, heavy stubble", "Uniforme rayé noir et blanc, barbe drue"),
         two("Sisika Penitentiary", "Pénitencier de Sisika")],
    ]}},
    {"h4": two("1907", "1907")},
    {"p": two(
        "Eight years on, the scars have closed into two lines on one cheek and one on the upper lip, where no beard grows. By default his hair is short and parted on the left, with a full beard. From \"Motherhood\" onwards, the player chooses his clothes, haircut, beard and cleanliness. Playable John is built on Arthur's body model and shares his list of haircuts, which includes neither the 1899 nor the 1911 cut; the long hair seen in pre-release images only returns in a brief flashback in \"A New Jerusalem\". Food changes his weight as it does Arthur's: heavier means more health and less stamina, lighter the reverse. When he aims, he closes his left eye and keeps the right one open. Four hats stand out: the worn gambler hat, a newer blue version of it, his classic hat and Arthur's.",
        "Huit ans plus tard, les cicatrices se sont refermées en deux traits sur une joue et un sur la lèvre supérieure, où la barbe ne pousse plus. Par défaut, il a les cheveux courts, une raie à gauche et une barbe fournie. À partir de \"Motherhood\", le joueur choisit ses vêtements, sa coupe, sa barbe et son hygiène. Le John jouable repose sur le modèle corporel d'Arthur et dispose des mêmes coupes que lui, parmi lesquelles ne figurent ni celle de 1899 ni celle de 1911 ; les cheveux longs visibles sur les images d'avant la sortie ne reviennent que le temps d'un bref souvenir dans \"A New Jerusalem\". La nourriture joue sur son poids comme sur celui d'Arthur : plus lourd, il gagne en santé et perd en endurance, et inversement. Pour viser, il ferme l'œil gauche et garde le droit ouvert. Quatre chapeaux se détachent : le vieux chapeau de joueur, sa version bleue plus récente, son chapeau classique et celui d'Arthur.")},
    {"table": {"head": [two("Outfit", "Tenue"), two("When", "Quand")], "rows": [
        [two("Dark blue trousers, red and white shirt, worn flat cap, black coat", "Pantalon bleu foncé, chemise rouge et blanche, casquette plate usée, manteau noir"),
         two("\"The Wheel\"", "\"The Wheel\"")],
        [two("Old gambler hat with assorted shirts and trousers", "Vieux chapeau de joueur avec diverses chemises et pantalons"),
         two("Work at Pronghorn Ranch; the hat can be kept by picking it up after it is knocked off", "Travail au Pronghorn Ranch ; on peut garder le chapeau en le ramassant quand il tombe")],
        [two("Denim vest, white shirt, white suspenders, dark blue work trousers, dark brown boots with yellow spurs, red neckerchief, black gloves, the hat he still wears in 1911", "Gilet en jean, chemise blanche, bretelles blanches, pantalon de travail bleu foncé, bottes brun foncé à éperons jaunes, foulard rouge, gants noirs, le chapeau qu'il porte encore en 1911"),
         two("His usual outfit; a black coat is added for the climb of Mount Hagen in \"American Venom\"", "Sa tenue habituelle ; un manteau noir s'y ajoute pour l'ascension du mont Hagen dans \"American Venom\"")],
        [two("Black vest, grey flannel shirt, brown trousers, dark brown boots, black gloves, classic hat", "Gilet noir, chemise en flanelle grise, pantalon marron, bottes brun foncé, gants noirs, chapeau classique"),
         two("Default outfit after \"American Venom\"", "Tenue par défaut après \"American Venom\"")],
    ]}},
    {"h4": two("1911", "1911")},
    {"p": two(
        "In Red Dead Redemption, his hair is dark brown and parted on the right, close to the 1899 cut but shorter and a shade lighter, and his beard stays a short stubble. One of the formal outfits gives him longer hair and a trimmed moustache. At Beecher's Hope, he silently tips his hat when he passes Abigail, Jack, Uncle or the ranch hand Amos.",
        "Dans Red Dead Redemption, ses cheveux sont brun foncé, avec une raie à droite, dans une coupe proche de celle de 1899, en plus court et un peu plus clair ; sa barbe reste un chaume court. L'une des tenues habillées lui donne des cheveux plus longs et une moustache taillée. À Beecher's Hope, il soulève son chapeau sans un mot quand il croise Abigail, Jack, Uncle ou Amos, l'employé du ranch.")},
    {"table": {"head": [two("Outfit", "Tenue"), two("When", "Quand")], "rows": [
        [two("Grey striped trousers, loose beige shirt, dark denim vest, classic hat", "Pantalon gris à rayures, chemise beige ample, gilet en jean foncé, chapeau classique"),
         two("Default outfit", "Tenue par défaut")],
        [two("The 1907 cowboy outfit, now with a beige shirt buttoned at the collar, closer-fitting gloves, the lower vest buttons undone and no patch on the trousers", "La tenue de cow-boy de 1907, avec désormais une chemise beige boutonnée au col, des gants plus ajustés, le bas du gilet déboutonné et plus de pièce au pantalon"),
         two("Returns from 1907 with these changes", "Reprise de 1907 avec ces différences")],
        [two("Brown trousers, grey shirt, leather gloves, open black vest, black boots, classic hat", "Pantalon marron, chemise grise, gants de cuir, gilet noir ouvert, bottes noires, chapeau classique"),
         two("Rancher clothes, after \"The Outlaw's Return\"", "Tenue de rancher, après \"The Outlaw's Return\"")],
    ]}},
    {"h4": two("Undead Nightmare", "Undead Nightmare")},
    {"p": two(
        "Risen from his grave, John limps and runs crooked on a twisted left foot, frozen in the posture of his death in \"The Last Enemy That Shall Be Destroyed\". He straightens up as soon as he draws. The hat of the Undead Cowboy Outfit reveals a bullet hole above his right eye, which is not there with the bareheaded Undead Hunter Outfit. In multiplayer, the \"Liars and Cheats\" pack adds John as a playable model, and \"Undead Nightmare\" adds Zombie Marston.",
        "Sorti de sa tombe, John boite et court de travers sur un pied gauche tordu, figé dans la posture de sa mort dans \"The Last Enemy That Shall Be Destroyed\". Il se redresse dès qu'il dégaine. Le chapeau de la tenue Undead Cowboy laisse voir un impact de balle au-dessus de son œil droit, absent avec la tenue Undead Hunter, portée tête nue. En multijoueur, le pack \"Liars and Cheats\" ajoute John comme modèle jouable, et \"Undead Nightmare\" un Zombie Marston.")},
]

# ---------------------------------------------------------------- SKILLS
BLOCKS_SKILLS = [
    {"h3": two("Skills, weapons and horses", "Compétences, armes et chevaux")},
    {"h4": two("Gunfighting", "Armes à feu")},
    {"p": two(
        "John is one of the gang's most effective gunmen. In \"The Sheep and the Goats\", after being freed from one of Leviticus Cornwall's men, he catches his captor's falling revolver and shoots another guard with it. In 1907, he climbs Mount Hagen alone after Charles is shot by a sniper and Sadie is stabbed, and kills Micah's men on his way up, including Joe. In 1911, he storms Fort Mercer from Nigel West Dickens's wagon with a Gatling gun, and in Mexico he defends an army train with a mounted machine gun. In the final mission, he holds Beecher's Hope against soldiers and agents with Uncle and Jack.",
        "John est l'un des tireurs les plus redoutables du gang. Dans \"The Sheep and the Goats\", une fois libéré de l'un des hommes de Leviticus Cornwall, il rattrape au vol le revolver de son ravisseur et abat un autre garde avec. En 1907, il gravit seul le mont Hagen après que Charles a été touché par un tireur embusqué et Sadie poignardée, et élimine en chemin les hommes de Micah, dont Joe. En 1911, il prend d'assaut Fort Mercer depuis le chariot de Nigel West Dickens avec une mitrailleuse Gatling, et au Mexique, il défend un train de l'armée derrière une mitrailleuse montée. Lors de la dernière mission, il tient Beecher's Hope face aux soldats et aux agents avec Uncle et Jack.")},
    {"p": two(
        "His fame in Red Dead Redemption follows the player's actions. Passers-by comment on his exploits, and amateur gunslingers challenge him to duels in town streets. Duels use a dedicated mechanic: the player draws, then places shots on the opponent before time resumes. He also fights hand to hand, both in brawls and in scripted fights, and he beats a very large man named Bertram in a one-on-one fistfight. Nigel West Dickens presents John's strength and aim to a crowd as proof that his elixir works.",
        "Sa réputation dans Red Dead Redemption dépend des actions du joueur. Les passants commentent ses exploits, et des tireurs amateurs le provoquent en duel dans les rues des villes. Les duels obéissent à une mécanique dédiée : le joueur dégaine, puis place ses tirs sur l'adversaire avant que le temps ne reprenne son cours. Il se bat aussi à mains nues, en bagarre libre comme en combat scénarisé, et il bat en combat singulier un colosse nommé Bertram. Nigel West Dickens présente à la foule la force et l'adresse de John comme la preuve que son élixir fonctionne.")},
    {"h4": two("Dead Eye and Eagle Eye", "Dead Eye et Eagle Eye")},
    {"p": two(
        "Like the other protagonists of the series, John can use Dead Eye, which slows time so the player can mark several targets before firing. In Red Dead Redemption, the ability has three levels unlocked over the story, from simple slowed aiming to manual marking of each shot. In Red Dead Redemption 2, his Dead Eye can also reveal critical areas on a target, and its sound effect is the one from the 2010 game, different from Arthur's. Red Dead Redemption 2 also gives him Eagle Eye, which highlights tracks, scents and points of interest so the player can follow a trail over long distances.",
        "Comme les autres héros de la série, John dispose du Dead Eye, qui ralentit le temps pour permettre au joueur de marquer plusieurs cibles avant de tirer. Dans Red Dead Redemption, la capacité compte trois niveaux débloqués au fil de l'histoire, du simple ralenti au marquage manuel de chaque tir. Dans Red Dead Redemption 2, son Dead Eye peut aussi révéler les points vitaux d'une cible, et son effet sonore reprend celui du jeu de 2010, différent de celui d'Arthur. Red Dead Redemption 2 lui donne en outre l'Eagle Eye, qui met en évidence traces, odeurs et points d'intérêt pour suivre une piste sur de longues distances.")},
    {"h4": two("Ranching, hunting and riding", "Ranch, chasse et équitation")},
    {"p": two(
        "John is an experienced rider and hunter. At MacFarlane's Ranch in 1911, he herds cattle, patrols at night and breaks wild horses, notably in \"Wild Horses, Tamed Passions\", and he uses the lasso to catch animals and hogtie fugitives. Bounty posters in Red Dead Redemption pay more for a target brought back alive. At Pronghorn Ranch in 1907, he milks cows, helps deliver a foal, builds fences and teaches David Geddes's younger son, Duncan, to break and ride a horse. He also teaches Jack to ride, and later fishes and hunts with him. In 1911 he hunts with Jack in \"John Marston and Son\" and saves him from a bear in \"Spare the Love, Spoil the Child\". In the RDR2 epilogue, he clicks his tongue to make his horse speed up instead of speaking.",
        "John est un cavalier et un chasseur expérimenté. Au ranch MacFarlane, en 1911, il mène le bétail, fait des rondes de nuit et dresse des chevaux sauvages, notamment dans \"Wild Horses, Tamed Passions\", et il se sert du lasso pour attraper les bêtes et ligoter les fugitifs. Dans Red Dead Redemption, les avis de recherche paient davantage pour une cible ramenée vivante. Au Pronghorn Ranch, en 1907, il trait les vaches, aide une jument à mettre bas, pose des clôtures et apprend à Duncan, le cadet de David Geddes, à dresser et monter un cheval. Il apprend aussi à Jack à monter, puis va pêcher et chasser avec lui. En 1911, il chasse avec son fils dans \"John Marston and Son\" et le sauve d'un ours dans \"Spare the Love, Spoil the Child\". Dans l'épilogue de RDR2, il fait claquer sa langue pour accélérer l'allure de son cheval, au lieu de parler.")},
    {"h4": two("Reading, writing, languages and swimming", "Lecture, écriture, langues et natation")},
    {"p": two(
        "Dutch taught John to read. In 1911 he tells Nigel West Dickens he reads \"a little\". His RDR2 journal is messier than Arthur's: the handwriting and sketches are simpler and words are often crossed out, although some drawings, such as a Pekin duck and a Merino sheep, are detailed. In Mexico he speaks only basic Spanish. John cannot swim. In Red Dead Redemption, he dies as soon as water rises above his chin. In Red Dead Redemption 2, his stamina drains at once in deep water and he drowns. The game turns this into a story detail: at Clemens Point, Arthur remarks that camping near the water makes John nervous, and he teases him about it while playing poker and in \"The Sheep and the Goats\".",
        "C'est Dutch qui a appris à lire à John. En 1911, il dit à Nigel West Dickens qu'il lit \"un peu\". Son journal dans RDR2 est plus brouillon que celui d'Arthur : écriture et croquis plus simples, mots souvent raturés, même si certains dessins, comme un canard de Pékin ou un mouton mérinos, sont soignés. Au Mexique, il ne parle qu'un espagnol rudimentaire. John ne sait pas nager. Dans Red Dead Redemption, il meurt dès que l'eau dépasse son menton. Dans Red Dead Redemption 2, son endurance se vide aussitôt en eau profonde et il se noie. Le jeu en fait un trait de l'histoire : à Clemens Point, Arthur note que camper près de l'eau rend John nerveux, et il le taquine à ce sujet au poker et dans \"The Sheep and the Goats\".")},
    {"p": two(
        "John is less skilled at living under a false identity than Dutch, Hosea or Arthur. At Pronghorn Ranch he gives his real first name before his alias, Jim Milton, and his lack of experience as a ranch hand shows. In Valentine, Sadie mocks the alias. He gives his real name at the Strawberry post office, which leads the brother of a man he killed to find him.",
        "John sait moins bien que Dutch, Hosea ou Arthur vivre sous une fausse identité. Au Pronghorn Ranch, il donne son vrai prénom avant son alias, Jim Milton, et son manque d'expérience de garçon de ferme se voit. À Valentine, Sadie se moque de cet alias. Il donne son vrai nom au bureau de poste de Strawberry, ce qui permet au frère d'un homme qu'il a tué de le retrouver.")},
    {"h4": two("Weapons", "Armes")},
    {"p": two(
        "In Red Dead Redemption, John starts with a Cattleman Revolver, a model nicknamed the Peacemaker. Over the story he can use revolvers, pistols such as the Mauser and the High Power Pistol, repeaters, rifles, shotguns, the Explosive Rifle, dynamite, throwing knives and a lasso. In Red Dead Redemption 2, the weapons associated with him include a bow, the Cattleman, Schofield and Double-Action revolvers, the Carbine, Lancaster and Litchfield repeaters, the Bolt Action Rifle, the Repeating Shotgun and a hunting knife; in the epilogue the player chooses his arsenal. Three of these are his own: a Cattleman Revolver with a blackened steel finish and a bone grip, a custom Lancaster Repeater and a personal knife. In Undead Nightmare, Nigel West Dickens builds him a Blunderbuss, Landon Ricketts makes Boom Bait, and Leigh Johnson gives him a Sawed-off Shotgun.",
        "Dans Red Dead Redemption, John commence avec un Cattleman Revolver, un modèle surnommé le Peacemaker. Au fil de l'histoire, il peut utiliser revolvers, pistolets comme le Mauser et le High Power Pistol, carabines à répétition, fusils, fusils à pompe, l'Explosive Rifle, la dynamite, des couteaux de lancer et un lasso. Dans Red Dead Redemption 2, les armes qui lui sont associées comprennent un arc, les revolvers Cattleman, Schofield et Double-Action, les carabines Carbine, Lancaster et Litchfield, le Bolt Action Rifle, le Repeating Shotgun et un couteau de chasse ; dans l'épilogue, le joueur compose son arsenal. Trois de ces armes lui appartiennent en propre : un Cattleman Revolver à finition acier noirci et crosse en os, une Lancaster Repeater personnalisée et un couteau personnel. Dans Undead Nightmare, Nigel West Dickens lui fabrique un tromblon (Blunderbuss), Landon Ricketts des appâts explosifs (Boom Bait), et Leigh Johnson lui donne un fusil à canon scié.")},
    {"h4": two("Horses", "Chevaux")},
    {"p": two(
        "In 1899, John's bay mare is killed by the wolves in the mountains above Colter; Arthur and Javier find the dead horse before finding him. In chapter 2 he rides Old Boy, and carries Kieran Duffy on it to Six Point Cabin in \"Paying a Social Call\". In the epilogue, his default horse is Rachel. Through the stranger mission \"The Veteran\", he can receive Buell, the horse of Hamish Sinclair. In Red Dead Redemption, Bonnie MacFarlane provides him with a horse in \"New Friends, Old Problems\", and \"Wild Horses, Tamed Passions\" rewards him with a Kentucky Saddler. From then on, the player chooses his mounts. The family dog, Rufus, is with the Marstons in 1907 and 1911.",
        "En 1899, la jument baie de John est tuée par les loups dans les montagnes au-dessus de Colter ; Arthur et Javier trouvent la bête morte avant de le retrouver lui. Au chapitre 2, il monte Old Boy, sur lequel il emmène Kieran Duffy jusqu'à Six Point Cabin dans \"Paying a Social Call\". Dans l'épilogue, son cheval par défaut est Rachel. La mission d'inconnu \"The Veteran\" peut lui valoir Buell, le cheval de Hamish Sinclair. Dans Red Dead Redemption, Bonnie MacFarlane lui fournit un cheval dans \"New Friends, Old Problems\", et \"Wild Horses, Tamed Passions\" lui vaut un Kentucky Saddler. Ensuite, le joueur choisit ses montures. Le chien de la famille, Rufus, accompagne les Marston en 1907 comme en 1911.")},
]

# ---------------------------------------------------------------- RELATIONSHIPS
BLOCKS_RELATIONSHIPS = [
    {"h3": two("Relationships in detail", "Ses relations en détail")},
    {"h4": two("Abigail Marston", "Abigail Marston")},
    {"p": two(
        "[[abigail-marston|Abigail Roberts]] joined the gang in 1894, and Jack was born the following year. Around 1896, John left the gang for a year, leaving her alone with the child. In 1899 they argue often, notably at Sean's homecoming party, and Abigail scolds him after his rescue from the wolves. After Jack's kidnapping, John invites her and Jack to sleep in his tent. In 1907 she leaves him at Pronghorn Ranch after the killings of the Laramie gang leader and of the three riders, then returns to Beecher's Hope after his letter. He proposes on a lake and marries her once the loan is paid off. In 1911, the Bureau holds her to force John's cooperation. During the final attack, he sends her away on horseback with Jack.",
        "[[abigail-marston|Abigail Roberts]] rejoint le gang en 1894, et Jack naît l'année suivante. Vers 1896, John quitte le gang pendant un an, la laissant seule avec l'enfant. En 1899, ils se disputent souvent, notamment à la fête donnée pour le retour de Sean, et Abigail le sermonne après son sauvetage. Après l'enlèvement de Jack, John leur propose, à elle et à leur fils, de dormir sous sa tente. En 1907, elle le quitte à Pronghorn Ranch après la mort du chef du gang Laramie et des trois cavaliers, puis revient à Beecher's Hope après avoir reçu sa lettre. Il la demande en mariage sur un lac et l'épouse une fois l'emprunt remboursé. En 1911, le Bureau la retient pour forcer John à coopérer. Lors de l'assaut final, il la fait fuir à cheval avec Jack.")},
    {"h4": two("Jack Marston", "Jack Marston")},
    {"p": two(
        "In 1899, John doubts he is [[jack-marston|Jack]]'s father and leaves his upbringing to Abigail and the gang. After Jack is kidnapped and handed to Angelo Bronte, John takes part in the attack on Braithwaite Manor and goes to Bronte's mansion to get him back. In 1907 Abigail asks him to spend time with the boy: he teaches Jack to ride and takes him to Strawberry, where Jack sees him kill three men and has a panic attack. At Beecher's Hope they go fishing with Rufus. In 1911, John hunts with Jack, listens to him talk about his books and saves him from a bear. Three years after John's death, Jack kills Edgar Ross in \"Remember My Family\".",
        "En 1899, John doute d'être le père de [[jack-marston|Jack]] et laisse son éducation à Abigail et au gang. Après l'enlèvement de Jack, livré à Angelo Bronte, John participe à l'assaut de Braithwaite Manor et se rend au manoir de Bronte pour le récupérer. En 1907, Abigail lui demande de s'occuper du garçon : il lui apprend à monter et l'emmène à Strawberry, où Jack le voit abattre trois hommes et fait une crise de panique. À Beecher's Hope, ils vont pêcher avec Rufus. En 1911, John chasse avec Jack, l'écoute parler de ses lectures et le sauve d'un ours. Trois ans après la mort de John, Jack tue Edgar Ross dans \"Remember My Family\".")},
    {"h4": two("Arthur Morgan", "Arthur Morgan")},
    {"p": two(
        "[[arthur-morgan|Arthur]] and John grew up together in the gang under Dutch. Arthur held John's year-long departure around 1896 against him, and in 1899 he still reproaches him for it. Arthur nonetheless rescues him from the wolves with Javier, robs trains and steals sheep and horses with him, and gets him out of Sisika with Sadie in \"Visiting Hours\". While they blow up the Bacchus Bridge, Arthur urges him to leave with his family once they have the money. At Beaver Hollow, the two stand together against Dutch and Micah. Whatever the player's choice, Arthur gives John his hat and satchel and stays behind. In the ending where Arthur helps him escape, John calls him his brother.",
        "[[arthur-morgan|Arthur]] et John ont grandi ensemble dans le gang, sous la coupe de Dutch. Arthur n'a pas pardonné à John son départ d'un an vers 1896, et le lui reproche encore en 1899. Il le sauve pourtant des loups avec Javier, attaque des trains et vole moutons et chevaux avec lui, puis le fait sortir de Sisika avec Sadie dans \"Visiting Hours\". Pendant qu'ils font sauter le pont de Bacchus, Arthur le presse de partir avec sa famille dès qu'ils auront l'argent. À Beaver Hollow, les deux hommes font front ensemble contre Dutch et Micah. Quel que soit le choix du joueur, Arthur confie à John son chapeau et sa sacoche et reste en arrière. Dans la fin où Arthur l'aide à s'enfuir, John l'appelle son frère.")},
    {"h4": two("Dutch van der Linde", "Dutch van der Linde")},
    {"p": two(
        "[[dutch-van-der-linde|Dutch]] saved John from a hanging at twelve, raised him, taught him to read and read him Evelyn Miller's books. In 1899, John has seen Dutch shoot a young woman during the Blackwater ferry robbery, and he starts to question his leader. After Jack's return, Dutch reminds him that the gang comes first, calls him ungrateful in another scene, and later admits, in a camp scene, that he wanted to let him rot in prison. During \"Our Best Selves\", Dutch leaves him behind after he falls from the train, and tells the gang he is dead. In 1907, Dutch shoots Micah on Mount Hagen and leaves without answering John's thanks. In 1911, cornered at Cochinay, Dutch warns John that the government will always need a new monster, then lets himself fall from the cliff.",
        "[[dutch-van-der-linde|Dutch]] sauve John de la pendaison à douze ans, l'élève, lui apprend à lire et lui fait la lecture des livres d'Evelyn Miller. En 1899, John l'a vu abattre une jeune femme lors du braquage du ferry de Blackwater, et commence à contester son chef. Après le retour de Jack, Dutch lui rappelle que le gang passe avant tout, le traite d'ingrat dans une autre scène, puis avoue, dans une scène de camp, qu'il voulait le laisser pourrir en prison. Pendant \"Our Best Selves\", Dutch l'abandonne après sa chute du train et annonce au gang qu'il est mort. En 1907, Dutch tire sur Micah au mont Hagen et s'en va sans répondre aux remerciements de John. En 1911, acculé à Cochinay, Dutch prévient John que le gouvernement aura toujours besoin d'un nouveau monstre, puis se laisse tomber de la falaise.")},
    {"h4": two("Hosea Matthews", "Hosea Matthews")},
    {"p": two(
        "[[hosea-matthews|Hosea]] was already in the gang alongside Dutch, Arthur and Susan Grimshaw when John joined it at twelve. Unlike Arthur, Hosea welcomed John back after his year away around 1896. At Clemens Point, Dutch first assigns John to sell moonshine for the Braithwaites with Hosea, before sending him to the Grays instead. On the ride to Shady Belle, John tells Arthur that he blames Hosea and Dutch's scheme between the two families for Jack's kidnapping and Sean's death. Hosea is killed during the Saint Denis bank robbery, the same mission in which John is arrested.",
        "[[hosea-matthews|Hosea]] fait déjà partie du gang, avec Dutch, Arthur et Susan Grimshaw, quand John y entre à douze ans. Contrairement à Arthur, Hosea accueille bien John à son retour, après son année d'absence vers 1896. À Clemens Point, Dutch charge d'abord John de vendre de l'alcool de contrebande pour les Braithwaite avec Hosea, avant de l'envoyer plutôt chez les Gray. Sur la route de Shady Belle, John confie à Arthur qu'il reproche à Hosea et à Dutch leur combine entre les deux familles, qui a mené à l'enlèvement de Jack et à la mort de Sean. Hosea est tué lors du braquage de la banque de Saint-Denis, la mission même où John est arrêté.")},
    {"h4": two("Uncle", "Uncle")},
    {"p": two(
        "[[uncle|Uncle]] is the gang member who stays closest to the Marstons after 1899. In 1907, John finds him in Blackwater and brings him to Beecher's Hope, where Uncle helps build the house and the ranch. He calls John \"the rock farmer\" and \"J.M.\". In 1911 he lives on the ranch and gives John missions there. He is killed during the attack on Beecher's Hope in \"The Last Enemy That Shall Be Destroyed\", and buried on the hill where John is buried beside him. In Undead Nightmare, a zombified Uncle bites Abigail, and John shoots him.",
        "[[uncle|Uncle]] est le membre du gang qui reste le plus proche des Marston après 1899. En 1907, John le retrouve à Blackwater et l'emmène à Beecher's Hope, où Uncle aide à bâtir la maison et le ranch. Il surnomme John \"the rock farmer\" (le fermier de cailloux) et \"J.M.\". En 1911, il vit au ranch et y confie des missions à John. Il est tué lors de l'assaut de Beecher's Hope, dans \"The Last Enemy That Shall Be Destroyed\", et enterré sur la colline où John repose à ses côtés. Dans Undead Nightmare, Uncle, devenu zombie, mord Abigail, et John l'abat.")},
    {"h4": two("Sadie Adler", "Sadie Adler")},
    {"p": two(
        "[[sadie-adler|Sadie]] and Arthur free John from Sisika in \"Visiting Hours\". At Copperhead Landing, after the gang's collapse, Sadie and John promise each other to kill Micah if they ever find him. In 1907 she works as a bounty hunter in Valentine. In \"Gainful Employment\" she mocks his alias, then gives him bounty jobs that help pay off his loan; her telegrams sign him off as \"JM\". John tells her he wants to marry Abigail. When she finds a lead on Micah, she brings in John and Charles. She is stabbed on Mount Hagen, then holds Micah at gunpoint before he takes her hostage. She leaves Beecher's Hope on good terms after the wedding.",
        "[[sadie-adler|Sadie]] et Arthur font sortir John de Sisika dans \"Visiting Hours\". À Copperhead Landing, après l'effondrement du gang, Sadie et John se promettent de tuer Micah s'ils le retrouvent un jour. En 1907, elle est chasseuse de primes à Valentine. Dans \"Gainful Employment\", elle se moque de son alias, puis lui confie des contrats qui l'aident à rembourser son emprunt ; ses télégrammes lui sont adressés sous les initiales \"JM\". John lui annonce son intention d'épouser Abigail. Quand elle trouve une piste menant à Micah, elle fait appel à John et à Charles. Poignardée au mont Hagen, elle tient ensuite Micah en joue avant qu'il ne la prenne en otage. Elle quitte Beecher's Hope en bons termes après le mariage.")},
    {"h4": two("Charles Smith", "Charles Smith")},
    {"p": two(
        "[[charles-smith|Charles]] joined the gang in 1898. In chapter 2 he robs the Scarlett Meadows train with John and Arthur. In 1907, John finds him in Saint Denis and asks for his help. Charles works with him and Uncle to build the house at Beecher's Hope. He joins the hunt for Micah and is shot in the shoulder by a sniper on Mount Hagen, but keeps climbing with John and Sadie until Sadie is stabbed and sends John on alone. He attends the wedding, then leaves the ranch.",
        "[[charles-smith|Charles]] rejoint le gang en 1898. Au chapitre 2, il attaque le train de Scarlett Meadows avec John et Arthur. En 1907, John le retrouve à Saint-Denis et lui demande son aide. Charles bâtit avec lui et Uncle la maison de Beecher's Hope. Il participe à la traque de Micah et reçoit une balle de tireur embusqué à l'épaule au mont Hagen, mais poursuit l'ascension avec John et Sadie, jusqu'à ce que Sadie, poignardée, envoie John seul au sommet. Il assiste au mariage, puis quitte le ranch.")},
    {"h4": two("Bill Williamson", "Bill Williamson")},
    {"p": two(
        "In 1899, [[bill-williamson|Bill]] raids Six Point Cabin with John and Arthur, and the two persuade Arthur to keep Kieran Duffy. In chapter 6, Bill is among those who suspect John of working with the law, and he sides with Dutch at Beaver Hollow. In 1911, Bill leads his own gang from Fort Mercer. When John asks him to surrender, Bill accuses him of having always taken him for an idiot and of saving only himself, mocks the way he talks, and one of his men shoots John. Bill flees to Mexico before the assault on the fort, takes refuge with Colonel Allende, and dies at Escalera, shot by John or by Reyes depending on the player's choices.",
        "En 1899, [[bill-williamson|Bill]] attaque Six Point Cabin avec John et Arthur, et tous deux convainquent Arthur de garder Kieran Duffy. Au chapitre 6, Bill fait partie de ceux qui soupçonnent John de travailler pour la loi, et il se range du côté de Dutch à Beaver Hollow. En 1911, Bill dirige son propre gang depuis Fort Mercer. Quand John lui demande de se rendre, Bill l'accuse de l'avoir toujours pris pour un idiot et de n'avoir sauvé que sa peau, se moque de sa façon de parler, et l'un de ses hommes tire sur John. Bill s'enfuit au Mexique avant l'assaut du fort, se réfugie auprès du colonel Allende, et meurt à Escalera, abattu par John ou par Reyes selon les choix du joueur.")},
    {"h4": two("Javier Escuella", "Javier Escuella")},
    {"p": two(
        "In \"Enter, Pursued by a Memory\", [[javier-escuella|Javier]] goes with Arthur to look for John and carries him back on his horse while Arthur holds off the wolves. In chapter 3, the three men steal the Braithwaite horses in \"Horse Flesh for Dinner\". In chapter 6, Javier suspects John of being an informant and sides with Dutch and Micah. In 1911, Javier is in Mexico under Colonel Allende's protection. He escapes on horseback during the attack on El Presidio; at the end of the chase, the player chooses whether John captures him alive or kills him, and Javier, alive or dead, is handed over to Ross and Fordham.",
        "Dans \"Enter, Pursued by a Memory\", [[javier-escuella|Javier]] part avec Arthur à la recherche de John et le ramène sur son cheval pendant qu'Arthur repousse les loups. Au chapitre 3, les trois hommes volent les chevaux des Braithwaite dans \"Horse Flesh for Dinner\". Au chapitre 6, Javier soupçonne John d'être un indicateur et se range du côté de Dutch et de Micah. En 1911, Javier vit au Mexique sous la protection du colonel Allende. Il s'enfuit à cheval lors de l'attaque d'El Presidio ; au terme de la poursuite, le joueur choisit si John le capture vivant ou le tue, et Javier, mort ou vif, est remis à Ross et Fordham.")},
    {"h4": two("Micah Bell", "Micah Bell")},
    {"p": two(
        "[[micah-bell|Micah]] joined the gang in 1898 and pushed Dutch towards the Blackwater ferry robbery. At Colter, Dutch sends John and Micah ahead as scouts; Dutch and Arthur find Micah, but he does not know where John is. Micah calls John \"Scarface\", feeds Dutch's suspicion that John is a traitor in chapter 6, and with Dutch tells the gang that John died during the train robbery. At Beaver Hollow, he kills Susan Grimshaw and chases John and Arthur. In 1907, John, Sadie and Charles track him to Mount Hagen through Cleet. After Dutch shoots Micah in the chest, Micah tries to shoot back, and John outdraws and kills him.",
        "[[micah-bell|Micah]] rejoint le gang en 1898 et pousse Dutch à monter le braquage du ferry de Blackwater. À Colter, Dutch envoie John et Micah en éclaireurs ; Dutch et Arthur retrouvent Micah, qui ignore où est John. Micah surnomme John \"Scarface\", nourrit au chapitre 6 les soupçons de Dutch sur sa prétendue trahison, et annonce avec Dutch au gang que John est mort pendant l'attaque du train. À Beaver Hollow, il tue Susan Grimshaw et prend John et Arthur en chasse. En 1907, John, Sadie et Charles remontent jusqu'à lui au mont Hagen grâce à Cleet. Après que Dutch lui a tiré dans la poitrine, Micah tente de riposter, mais John dégaine plus vite et l'abat.")},
    {"h4": two("Edgar Ross", "Edgar Ross")},
    {"p": two(
        "[[edgar-ross|Edgar Ross]] appears beside Agent Andrew Milton at Clemens Point in 1899. In 1907, now head of the Bureau of Investigation, he finds Micah's body on Mount Hagen and, with Archer Fordham, traces the killing to John at Beecher's Hope. In 1911 he holds Abigail and Jack, sends John after Bill, Javier and Dutch, and addresses him as \"old boy\". After Dutch's fall at Cochinay, Ross takes John's gun and shoots the body: \"It looks better on the report that way.\" He then leads the soldiers and agents who attack Beecher's Hope, and lights a cigar while John dies. Jack kills him in a duel in 1914.",
        "[[edgar-ross|Edgar Ross]] apparaît aux côtés de l'agent Andrew Milton à Clemens Point, en 1899. En 1907, devenu chef du Bureau of Investigation, il découvre le corps de Micah au mont Hagen et remonte, avec Archer Fordham, jusqu'à John, à Beecher's Hope. En 1911, il retient Abigail et Jack, envoie John traquer Bill, Javier et Dutch, et l'appelle \"old boy\" (mon vieux). Après la chute de Dutch à Cochinay, Ross prend l'arme de John et tire sur le corps, parce que ça fera mieux dans le rapport. Il mène ensuite les soldats et les agents qui attaquent Beecher's Hope, et allume un cigare pendant que John agonise. Jack le tue en duel en 1914.")},
    {"h4": two("Archer Fordham", "Archer Fordham")},
    {"p": two(
        "[[archer-fordham|Archer Fordham]] works under Edgar Ross at the Bureau of Investigation. In 1907 he helps Ross question witnesses after Micah's death, and the RDR2 epilogue ends on the two agents watching John's ranch. In \"Exodus in America\", in 1911, Fordham and Ross escort John through Blackwater to the train that takes him to Armadillo. Fordham is with Ross when Javier is handed over in Mexico, and he takes part in the operations against Dutch in West Elizabeth.",
        "[[archer-fordham|Archer Fordham]] travaille sous les ordres d'Edgar Ross au Bureau of Investigation. En 1907, il aide Ross à interroger des témoins après la mort de Micah, et l'épilogue de RDR2 se clôt sur les deux agents observant le ranch de John. Dans \"Exodus in America\", en 1911, Fordham et Ross escortent John à travers Blackwater jusqu'au train qui l'emmène à Armadillo. Fordham accompagne Ross lors de la remise de Javier au Mexique, et participe aux opérations contre Dutch en West Elizabeth.")},
    {"h4": two("Bonnie MacFarlane", "Bonnie MacFarlane")},
    {"p": two(
        "After the shooting at Fort Mercer, [[bonnie-macfarlane|Bonnie]] and her ranch hand Amos find John by the road and take him to Doctor Nathaniel Johnston in Armadillo. She lodges and feeds him in exchange for work, and he repays the 15 dollars she paid the doctor by herding, patrolling and breaking horses. He calls her \"Miss MacFarlane\". In \"Women and Cattle\", he tells her about his parents and his past in the gang. When Bill's men burn the barn in \"The Burning\", John saves the horses, and when they kidnap Bonnie, he helps Marshal Johnson rescue her from the gallows in \"Hanging Bonnie MacFarlane\". Later, in \"Old Friends, New Problems\", pests have eaten her harvest; she telegrams the Marstons, and John and Abigail drive a wagon of corn to her ranch, where the two women meet for the first time.",
        "Après la fusillade de Fort Mercer, [[bonnie-macfarlane|Bonnie]] et son garçon de ferme Amos trouvent John au bord de la route et le conduisent chez le docteur Nathaniel Johnston, à Armadillo. Elle le loge et le nourrit en échange de son travail, et il lui rembourse les 15 dollars de médecin en menant le bétail, en faisant des rondes et en dressant des chevaux. Il l'appelle \"Miss MacFarlane\". Dans \"Women and Cattle\", il lui parle de ses parents et de son passé dans le gang. Quand les hommes de Bill incendient la grange dans \"The Burning\", John sauve les chevaux, et quand ils enlèvent Bonnie, il aide le marshal Johnson à la sauver de la potence dans \"Hanging Bonnie MacFarlane\". Plus tard, dans \"Old Friends, New Problems\", les nuisibles ont dévoré sa récolte : elle envoie un télégramme aux Marston, et John et Abigail lui livrent du maïs en chariot. Les deux femmes font alors connaissance.")},
    {"h4": two("Leigh Johnson", "Leigh Johnson")},
    {"p": two(
        "John works for [[leigh-johnson|Marshal Leigh Johnson]] in and around Armadillo in exchange for his help against Bill Williamson. During these missions, John tells him that killing is a crime unless a court orders it. Together they rescue Bonnie and plan the assault on Fort Mercer, for which Johnson joins the posse with his deputies. In Undead Nightmare, John offers to find Johnson's missing deputies, Eli and Jonah, and Johnson hands him a sawed-off shotgun for the search.",
        "John travaille pour [[leigh-johnson|le marshal Leigh Johnson]] à Armadillo et dans ses environs, en échange de son aide contre Bill Williamson. Au cours de ces missions, John lui fait remarquer que tuer est un crime, sauf quand un tribunal l'ordonne. Ensemble, ils sauvent Bonnie et préparent l'assaut de Fort Mercer, auquel Johnson participe avec ses adjoints. Dans Undead Nightmare, John se propose pour retrouver Eli et Jonah, les adjoints disparus de Johnson, qui lui remet un fusil à canon scié pour les recherches.")},
    {"h4": two("Nigel West Dickens", "Nigel West Dickens")},
    {"p": two(
        "John's first scene with [[nigel-west-dickens|Nigel West Dickens]], where he finds the injured salesman on the prairie, was the first cutscene recorded for Red Dead Redemption, according to producer Rob Nelson. John helps him in exchange for his help with Fort Mercer, while openly disapproving of his swindles. Dickens introduces him to Irish and Seth, and hides John and a Gatling gun in his wagon for the assault on the fort. In Undead Nightmare, John forces him to stop selling his elixir as a cure, gathers parts for him, and Dickens builds him a Blunderbuss.",
        "Selon le producteur Rob Nelson, la première scène entre John et [[nigel-west-dickens|Nigel West Dickens]], où il trouve le vendeur blessé dans la prairie, est la toute première cinématique tournée pour Red Dead Redemption. John l'aide en échange de son soutien contre Fort Mercer, sans cacher qu'il désapprouve ses escroqueries. Dickens lui présente Irish et Seth, et cache John et une mitrailleuse Gatling dans son chariot pour l'assaut du fort. Dans Undead Nightmare, John l'oblige à cesser de vendre son élixir comme remède, lui rapporte des pièces, et Dickens lui fabrique un tromblon.")},
    {"h4": two("Seth Briars", "Seth Briars")},
    {"p": two(
        "[[seth-briars|Seth]] is a grave robber John meets through Nigel West Dickens. John makes no secret of his disgust for Seth's activities, but helps him search for a treasure map in exchange for joining the attack on Fort Mercer. In Undead Nightmare, John finds Seth playing cards with an undead man at the Old Bacchus Place; Seth sends him to clear graveyards and points him towards Mexico. In the expansion's last scene, Seth steals the Aztec mask again, and John rises from his grave.",
        "[[seth-briars|Seth]] est un pilleur de tombes que John rencontre par l'intermédiaire de Nigel West Dickens. John ne cache pas son dégoût pour ses activités, mais l'aide à rechercher une carte au trésor en échange de sa participation à l'attaque de Fort Mercer. Dans Undead Nightmare, John trouve Seth en train de jouer aux cartes avec un mort-vivant à l'Old Bacchus Place ; Seth l'envoie nettoyer des cimetières et l'oriente vers le Mexique. Dans la dernière scène de l'extension, Seth vole de nouveau le masque aztèque, et John sort de sa tombe.")},
    {"h4": two("Irish", "Irish")},
    {"p": two(
        "[[irish|Irish]] is a drunk John meets through Dickens. He calls John \"Johnny\", \"Johnny Boy\" and \"Mr Jesus of Nazareth\". John threatens him to get him sober, and hits him when he holds up two nuns. Irish obtains the Gatling gun used at Fort Mercer, and in \"We Shall Be Together in Paradise\" he takes John across the border into Nuevo Paraíso.",
        "[[irish|Irish]] est un ivrogne que John rencontre par l'intermédiaire de Dickens. Il appelle John \"Johnny\", \"Johnny Boy\" et \"Mr Jesus of Nazareth\". John le menace pour qu'il dessoûle, et le frappe quand il braque deux religieuses. Irish procure la mitrailleuse Gatling utilisée à Fort Mercer et, dans \"We Shall Be Together in Paradise\", il fait passer la frontière à John jusqu'au Nuevo Paraíso.")},
    {"h4": two("Landon Ricketts", "Landon Ricketts")},
    {"p": two(
        "[[landon-ricketts|Landon Ricketts]], an aging gunslinger living in Chuparosa, teaches John new gunfighting techniques in Nuevo Paraíso, and the two attack Mexican Army patrols together. Ricketts gives John four missions: \"The Gunslinger's Tragedy\", \"Landon Ricketts Rides Again\", \"Lucky in Love\" and \"The Mexican Wagon Train\". In Undead Nightmare, John meets him again at Casa Madrugada, where Ricketts is fighting the undead alone; John brings him bait and dynamite, from which Ricketts makes Boom Bait.",
        "[[landon-ricketts|Landon Ricketts]], un tireur vieillissant installé à Chuparosa, enseigne à John de nouvelles techniques de combat au Nuevo Paraíso, et les deux hommes attaquent ensemble des patrouilles de l'armée mexicaine. Ricketts confie quatre missions à John : \"The Gunslinger's Tragedy\", \"Landon Ricketts Rides Again\", \"Lucky in Love\" et \"The Mexican Wagon Train\". Dans Undead Nightmare, John le retrouve à Casa Madrugada, où Ricketts affronte seul les morts-vivants ; John lui rapporte appâts et dynamite, dont Ricketts tire des appâts explosifs.")},
    {"h4": two("Abraham Reyes and Luisa Fortuna", "Abraham Reyes et Luisa Fortuna")},
    {"p": two(
        "John works for the rebel leader [[abraham-reyes|Abraham Reyes]] and his lover [[luisa-fortuna|Luisa Fortuna]] to obtain information on Bill and Javier, and answers Reyes's speeches with sarcasm. When Colonel Allende turns on John, Reyes's rebels save him from execution, and John then fights with them at El Presidio and at Allende's villa. Luisa is killed during the attack on the villa; John kills Raul Zubieta and two soldiers in response. Allende and Bill then die at Escalera, shot by John or by Reyes. In Undead Nightmare, John kills a zombified Reyes, who had stolen the Aztec mask behind the plague.",
        "John travaille pour le chef rebelle [[abraham-reyes|Abraham Reyes]] et sa compagne [[luisa-fortuna|Luisa Fortuna]] afin d'obtenir des informations sur Bill et Javier, et répond par l'ironie aux discours de Reyes. Quand le colonel Allende se retourne contre John, les rebelles de Reyes le sauvent de l'exécution ; John combat ensuite à leurs côtés à El Presidio et à la villa d'Allende. Luisa est tuée pendant l'assaut de la villa ; John abat Raul Zubieta et deux soldats en représailles. Allende et Bill meurent ensuite à Escalera, abattus par John ou par Reyes. Dans Undead Nightmare, John tue Reyes devenu zombie, qui avait volé le masque aztèque à l'origine de l'épidémie.")},
    {"h4": two("Agustin Allende and Vincente de Santa", "Agustin Allende et Vincente de Santa")},
    {"p": two(
        "On arriving in Nuevo Paraíso, John works for the provisional governor, [[agustin-allende|Colonel Agustin Allende]], and his second, [[vincente-de-santa|Captain Vincente de Santa]], who promise him Bill and Javier. He meets their speeches with sarcasm. Allende eventually betrays him and has his men try to kill him. De Santa is killed in \"Captain De Santa's Downfall\"; depending on the player's choice, John kills him or leaves him to the rebels. Allende flees his villa with Bill and dies at Escalera.",
        "À son arrivée au Nuevo Paraíso, John travaille pour le gouverneur provisoire, [[agustin-allende|le colonel Agustin Allende]], et son second, [[vincente-de-santa|le capitaine Vincente de Santa]], qui lui promettent Bill et Javier. Il accueille leurs discours avec ironie. Allende finit par le trahir et ordonne à ses hommes de le tuer. De Santa meurt dans \"Captain De Santa's Downfall\" ; selon le choix du joueur, John l'abat lui-même ou le laisse aux rebelles. Allende fuit sa villa avec Bill et meurt à Escalera.")},
    {"h4": two("Harold MacDougal and Nastas", "Harold MacDougal et Nastas")},
    {"p": two(
        "In West Elizabeth, Edgar Ross assigns John to work with [[harold-macdougal|Professor Harold MacDougal]], a Yale academic, and with [[nastas|Nastas]], a Native American informant, to track down Dutch. Both help him locate Dutch's hideout at Cochinay, which John then attacks with the Bureau and the army. In Undead Nightmare, John finds MacDougal in Blackwater, where an undead Nastas attacks him; John has to kill both.",
        "En West Elizabeth, Edgar Ross charge John de travailler avec [[harold-macdougal|le professeur Harold MacDougal]], un universitaire de Yale, et avec [[nastas|Nastas]], un informateur amérindien, pour retrouver Dutch. Tous deux l'aident à localiser le repaire de Dutch à Cochinay, que John attaque ensuite avec le Bureau et l'armée. Dans Undead Nightmare, John retrouve MacDougal à Blackwater, où Nastas, devenu mort-vivant, l'attaque ; John doit les abattre tous les deux.")},
    {"h4": two("Kieran Duffy", "Kieran Duffy")},
    {"p": two(
        "[[kieran-duffy|Kieran]] is a former O'Driscoll captured by the gang in chapter 1. In \"Paying a Social Call\", he rides behind John on Old Boy to lead the gang to the O'Driscoll hideout at Six Point Cabin. After Kieran saves Arthur's life during the fight, John and Bill persuade Arthur to let him stay, and they take him back to camp.",
        "[[kieran-duffy|Kieran]] est un ancien O'Driscoll capturé par le gang au chapitre 1. Dans \"Paying a Social Call\", il monte derrière John sur Old Boy pour guider le gang jusqu'à la planque des O'Driscoll, à Six Point Cabin. Après que Kieran a sauvé la vie d'Arthur pendant l'affrontement, John et Bill convainquent Arthur de le garder, et le ramènent au camp.")},
    {"h4": two("Other members of the gang", "Autres membres du gang")},
    {"p": two(
        "[[susan-grimshaw|Susan Grimshaw]] was in the gang when John joined it as a boy. At Beaver Hollow, she sides with John and Arthur and holds Micah at gunpoint, and Micah kills her. [[sean-macguire|Sean MacGuire]] took part in the Blackwater ferry robbery with John, robs the Scarlett Meadows train with him, and is one of those who call him \"Scarface\". [[karen-jones|Karen Jones]] turns down John's drunken advances at Sean's homecoming party out of respect for Abigail. Agent [[andrew-milton|Andrew Milton]] offers the gang amnesty in exchange for Dutch at Clemens Point; asked who he is, John answers \"Rip Van Winkle\".",
        "[[susan-grimshaw|Susan Grimshaw]] fait partie du gang quand John y entre enfant. À Beaver Hollow, elle se range du côté de John et d'Arthur et tient Micah en joue ; Micah la tue. [[sean-macguire|Sean MacGuire]] participe avec John au braquage du ferry de Blackwater, attaque avec lui le train de Scarlett Meadows, et fait partie de ceux qui l'appellent \"Scarface\". [[karen-jones|Karen Jones]] repousse les avances de John, ivre, à la fête du retour de Sean, par respect pour Abigail. À Clemens Point, l'agent [[andrew-milton|Andrew Milton]] propose l'amnistie au gang en échange de Dutch ; quand il demande à John qui il est, celui-ci répond \"Rip Van Winkle\".")},
]
