"""Arthur Morgan, full template (7 Oct 2026).

Fact base: two research passes (1899 storyline / background + real world), each
fact tagged CONFIRMED or WIKI-ONLY; only CONFIRMED stated as fact.
Sources (internal register): Red Dead Wiki EN + ~90 mission pages and
/dialogues transcripts, English Wikipedia "Arthur Morgan" (GA) and "Red Dead
Redemption 2", PowerPyx mission list and walkthroughs, THR (Shanley, 7 Sep 2018
Josh Bass; 8 Nov 2018 cast), Variety (Crecente, 24 Oct 2018; 10 Jan and 14 Mar
2019), GQ UK (White, 24 Oct 2018), Vulture (Goldberg, 14 Oct 2018), GamesRadar+
(Serin, 8 Nov 2025; Weber, 9 Nov 2021), Irish Times (Gorman, 15 Apr 2019),
VG247 (McKeand, 6 Feb 2019), Shacknews (1 Feb 2019), Twinfinite (Madsen,
19 Feb 2019), Polygon (6 Dec 2018), IGN (Reilly, 25 Oct 2018), Kotaku
(Hamilton, 26 Oct 2018), Game Informer (Gwaltney, 7 Nov 2018), NYT (Suderman,
23 Nov 2018), Nintendo Life (Reynolds, 4 Apr 2024).
Left out (wiki-only or contested): exact birth year, parents' details, the
doctor's name, Eliza's age and the "ten dollars", epitaphs and grave look, the
100% cutscene, numeric honor thresholds, death music, the cough anecdote.
Fixes vs the earlier fiche: Arthur is NOT in Red Dead Online.
"""

def two(en, fr): return {"en": en, "fr": fr}

def build(cl, CH):
    def ch(n, en, fr): return {"h4": two(en, fr), "chapter": CH[n]}
    M = lambda mission, chap, en, fr: [mission, chap, two(en, fr)]
    VID = {"id": "pl2ZPoevd0I",
      "title": two("Roger Clark wins Best Performance for Red Dead Redemption 2 at The Game Awards 2018",
                   "Roger Clark reçoit le prix de la meilleure interprétation pour Red Dead Redemption 2 aux Game Awards 2018"),
      "cap": two("Roger Clark accepting Best Performance at The Game Awards 2018.",
                 "Roger Clark reçoit le prix de la meilleure interprétation aux Game Awards 2018.")}
    return {
 "slug": "arthur-morgan", "name": "Arthur Morgan",
 "publishDate": "2026-06-22", "updated": "2026-10-07", "schema_game": "Red Dead Redemption 2",
 "reg_role_en": "Van der Linde gang &middot; RDR2", "reg_role_fr": "Gang Van der Linde &middot; RDR2",
 "gender": "Male", "death": "1899", "nationality": "American",
 "portrait_alt": two("Arthur Morgan in Red Dead Redemption 2", "Arthur Morgan dans Red Dead Redemption 2"),
 "eyebrow": two("Character &middot; Van der Linde gang", "Personnage &middot; Gang Van der Linde"),
 "meta_desc": two("Arthur Morgan, protagonist of Red Dead Redemption 2: full biography, every chapter and mission, the four endings, Roger Clark's performance, development and awards.",
                  "Arthur Morgan, héros de Red Dead Redemption 2 : biographie complète, chaque chapitre et chaque mission, les quatre fins, l'interprétation de Roger Clark, la conception et les récompenses."),
 "og_desc": two("The complete reference on Arthur Morgan: life, missions, endings, quotes, development and reception.",
                "La référence complète sur Arthur Morgan : vie, missions, fins, citations, conception et accueil."),
 "schema_desc": two("Protagonist of Red Dead Redemption 2 and senior member of the Van der Linde gang.",
                    "Héros de Red Dead Redemption 2 et pilier du gang Van der Linde."),
 "chips": [two("Died <strong>1899</strong>", "Mort en <strong>1899</strong>"), two("Deceased", "Décédé"),
           two("Van der Linde gang", "Gang Van der Linde"), two("Voiced by <strong>Roger Clark</strong>", "Voix de <strong>Roger Clark</strong>")],
 "facts": [
   {"label": two("Born","Naissance"), "value": two("Early 1860s","Début des années 1860")},
   {"label": two("Died","Mort"), "value": two("1899","1899")},
   {"label": two("Status","Statut"), "value": two("Deceased","Décédé")},
   {"label": two("Nationality","Nationalité"), "value": two("American","Américaine")},
   {"label": two("Affiliation","Affiliation"), "value": two("Van der Linde gang","Gang Van der Linde")},
   {"label": two("Role","Rôle"), "value": two("Dutch's senior enforcer","Principal homme de main de Dutch")},
   {"label": two("Family","Famille"), "value": two("Son Isaac, with Eliza (both killed)","Un fils, Isaac, avec Eliza (tous deux tués)")},
      {"label": two("Games","Jeux"), "value": two("Red Dead Redemption 2","Red Dead Redemption 2")},
   {"label": two("Voiced by","Voix"), "value": two("Roger Clark","Roger Clark")},
 ],
 "intro": [
   two("Arthur Morgan is the protagonist of Red Dead Redemption 2 (2018). Rockstar presented him as \"Dutch's most dependable and capable enforcer since he was a boy\", for whom \"the outlaw life is all Arthur has ever known\".",
       "Arthur Morgan est le héros de Red Dead Redemption 2 (2018). Rockstar le présente comme l'homme de main le plus fiable et le plus capable de Dutch depuis l'enfance, un homme qui n'a jamais connu d'autre vie que celle de hors-la-loi."),
   two("He is played by Roger Clark, whose performance won Best Performance at The Game Awards 2018.",
       "Il est interprété par Roger Clark, récompensé pour ce rôle par le prix de la meilleure interprétation aux Game Awards 2018."),
 ],
 "essentials": [
   two("Taken in as a boy by [[dutch-van-der-linde|Dutch van der Linde]] and [[hosea-matthews|Hosea Matthews]]; in 1899 he has been in the gang for about twenty years.",
       "Recueilli enfant par [[dutch-van-der-linde|Dutch van der Linde]] et [[hosea-matthews|Hosea Matthews]] ; en 1899, il fait partie du gang depuis une vingtaine d'années."),
   two("The player controls him for the six chapters of the main story, from the snow of Colter to Beaver Hollow.",
       "Le joueur l'incarne pendant les six chapitres de l'histoire principale, de la neige de Colter à Beaver Hollow."),
   two("Diagnosed with tuberculosis in 1899, he turns against Dutch and helps [[john-marston|John Marston]] escape with his family.",
       "Atteint de tuberculose en 1899, il se retourne contre Dutch et aide [[john-marston|John Marston]] à fuir avec sa famille."),
   two("He dies in 1899; the game has four endings, decided by his honor and by a final choice.",
       "Il meurt en 1899 ; le jeu compte quatre fins, selon son honneur et un dernier choix."),
   two("Roger Clark won Best Performance at The Game Awards 2018 for the role.",
       "Roger Clark a remporté le prix de la meilleure interprétation aux Game Awards 2018 pour ce rôle."),
 ],
 "rel_after": 0,
 "sections": [
   # ================================================================ BIOGRAPHY
   {"summary": two("Biography","Biographie"), "open": True, "blocks": [
     {"h3": two("Origins","Origines")},
     {"p": two("No birth year is given in the game. In 1899, Arthur tells Charles he has been with the gang for \"twenty years, something like that. Since I was a boy\", and Hosea says they found him at about thirteen, \"maybe a little older\". According to the official guide, he joined the gang at fourteen. Agent Milton later describes him as an \"orphaned street kid\" taken in by Dutch.",
               "Le jeu ne donne aucune année de naissance. En 1899, Arthur dit à Charles faire partie du gang depuis \"une vingtaine d'années, depuis tout gamin\", et Hosea raconte qu'ils l'ont trouvé vers treize ans, \"peut-être un peu plus\". D'après le guide officiel, il entre dans le gang à quatorze ans. L'agent Milton le décrira plus tard comme un gamin des rues orphelin, recueilli par Dutch.")},
     {"p": two("Arthur says Dutch taught him to read, as he taught John, and that Dutch and Hosea taught him most of what he knows. According to the official guide, he had a son, Isaac, with a waitress named Eliza; he sent them money until both were killed in a robbery. He was once engaged to [[mary-linton|Mary Gillis]], now Mary Linton; in a letter returning his ring, she writes that his world \"is not a world from which one can escape\". Letters to the gang are addressed to an alias invented by Dutch, Tacitus Kilgore.",
               "Arthur raconte que Dutch lui a appris à lire, comme à John, et que Dutch et Hosea lui ont enseigné l'essentiel de ce qu'il sait. D'après le guide officiel, il a eu un fils, Isaac, avec une serveuse nommée Eliza ; il leur envoyait de l'argent, jusqu'à ce que tous deux soient tués lors d'un vol. Il a été fiancé à [[mary-linton|Mary Gillis]], devenue Mary Linton ; dans la lettre où elle lui rend sa bague, elle écrit que son monde est un monde dont on ne s'échappe pas. Le courrier du gang est adressé à un alias inventé par Dutch, Tacitus Kilgore.")},
     {"figure": {"img": "gang.jpeg", "alt": two("Dutch van der Linde addresses the Van der Linde gang in the forest","Dutch van der Linde s'adresse au gang Van der Linde dans la forêt"),
                 "cap": two("The Van der Linde gang, Arthur's family since boyhood.","Le gang Van der Linde, la famille d'Arthur depuis l'enfance.")}},
     # ------------------------------------------------------------ 1899
     {"h3": two("Red Dead Redemption 2 (1899)","Red Dead Redemption 2 (1899)")},
     ch(1, "Chapter 1: Colter", "Chapitre 1 : Colter"),
     {"p": two("After the failed ferry robbery in Blackwater, the gang shelters in Colter, an abandoned mining camp in the snow. With [[javier-escuella|Javier]], Arthur finds [[john-marston|John]] wounded by wolves. He takes part in the raid on an O'Driscoll camp in \"Old Friends\", then in the robbery of a train belonging to [[leviticus-cornwall|Leviticus Cornwall]], which sets Cornwall on the gang's trail and puts the Pinkertons back on it.",
               "Après le braquage raté du ferry de Blackwater, le gang se réfugie à Colter, un camp minier abandonné sous la neige. Avec [[javier-escuella|Javier]], Arthur retrouve [[john-marston|John]], blessé par des loups. Il participe à l'attaque d'un camp des O'Driscoll dans \"Old Friends\", puis à celle d'un train appartenant à [[leviticus-cornwall|Leviticus Cornwall]], qui lance Cornwall sur la piste du gang et y remet les Pinkerton.")},
     ch(2, "Chapter 2: Horseshoe Overlook", "Chapitre 2 : Horseshoe Overlook"),
     {"p": two(f"Arthur helps free [[sean-macguire|Sean MacGuire]] from bounty hunters and pulls a drunk [[orville-swanson|Reverend Swanson]] off a railway bridge just before a train. For [[leopold-strauss|Leopold Strauss]], he collects debts; in \"Money Lending and Other Sins III\", he beats a sick farmer, Thomas Downes, who coughs blood in his face. Agents Milton and Ross approach him while he is fishing with [[jack-marston|Jack]] and offer him a deal to give up Dutch; he refuses. He also helps Mary Linton look for her brother. In \"The Sheep and the Goats\", a shootout with Cornwall's men in Valentine forces the gang to move to Clemens Point.",
               f"Arthur aide à libérer [[sean-macguire|Sean MacGuire]] des chasseurs de primes et tire un [[orville-swanson|révérend Swanson]] ivre d'un pont ferroviaire juste avant le passage d'un train. Pour [[leopold-strauss|Leopold Strauss]], il recouvre des dettes ; dans \"Money Lending and Other Sins III\", il roue de coups un fermier malade, Thomas Downes, qui lui crache du sang au visage. Les agents Milton et Ross l'abordent pendant qu'il pêche avec [[jack-marston|Jack]] et lui proposent un marché pour livrer Dutch ; il refuse. Il aide aussi Mary Linton à rechercher son frère. Dans \"The Sheep and the Goats\", une fusillade contre les hommes de Cornwall à Valentine pousse le gang à partir pour Clemens Point.")},
     ch(3, "Chapter 3: Clemens Point", "Chapitre 3 : Clemens Point"),
     {"p": two("The gang plays the Grays against the Braithwaites. In the Rhodes ambush, Sean is killed and Arthur shoots Sheriff Leigh Gray. Captured by [[colm-odriscoll|Colm O'Driscoll]], Arthur escapes wounded. He goes back to the Downes ranch to collect the debt from Thomas's widow, Edith. After the Braithwaites kidnap Jack, the gang burns their manor and moves into Shady Belle.",
               "Le gang joue les Gray contre les Braithwaite. Dans l'embuscade de Rhodes, Sean est tué et Arthur abat le shérif Leigh Gray. Capturé par [[colm-odriscoll|Colm O'Driscoll]], Arthur s'échappe blessé. Il retourne au ranch des Downes réclamer la dette à la veuve de Thomas, Edith. Après l'enlèvement de Jack par les Braithwaite, le gang incendie leur manoir et s'installe à Shady Belle.")},
     ch(4, "Chapter 4: Saint Denis", "Chapitre 4 : Saint-Denis"),
     {"p": two("In Saint Denis, Arthur recovers Jack from [[angelo-bronte|Angelo Bronte]]; Dutch later kills Bronte and throws him to the alligators, which disturbs Arthur. He meets Chief Rains Fall and his son Eagle Flies, and helps them against Cornwall. The robbery of the Saint Denis bank is a Pinkerton trap: [[hosea-matthews|Hosea]] is killed by Agent Milton, [[lenny-summers|Lenny]] dies, John is arrested, and the survivors flee by ship.",
               "À Saint-Denis, Arthur reprend Jack à [[angelo-bronte|Angelo Bronte]] ; Dutch tue ensuite Bronte et le jette aux alligators, ce qui trouble Arthur. Il rencontre le chef Rains Fall et son fils Eagle Flies, et les aide contre Cornwall. Le braquage de la banque de Saint-Denis est un piège des Pinkerton : [[hosea-matthews|Hosea]] est tué par l'agent Milton, [[lenny-summers|Lenny]] meurt, John est arrêté, et les survivants s'enfuient en bateau.")},
     ch(5, "Chapter 5: Guarma", "Chapitre 5 : Guarma"),
     {"p": two("Shipwrecked on Guarma, the survivors side with Hercule Fontaine's rebels against Alberto Fussar; Arthur kills Fussar before they sail home. Back with the gang, Arthur collapses in Saint Denis, and a doctor diagnoses tuberculosis.",
               "Naufragés à Guarma, les survivants s'allient aux rebelles d'Hercule Fontaine contre Alberto Fussar ; Arthur tue Fussar avant le retour. De nouveau auprès du gang, Arthur s'effondre à Saint-Denis, et un médecin lui diagnostique la tuberculose.")},
     ch(6, "Chapter 6: Beaver Hollow", "Chapitre 6 : Beaver Hollow"),
     {"p": two("With [[sadie-adler|Sadie]], Arthur frees John from Sisika Penitentiary, against Dutch's wishes. He can forgive the last debts he is sent to collect, and throws Strauss out of the camp. He helps the Wapiti against the Army. At the oil fields, in \"My Last Boy\", Dutch leaves him behind; during the army payroll robbery, in \"Our Best Selves\", John falls from the train and Dutch leaves him for dead. Arthur breaks with Dutch.",
               "Avec [[sadie-adler|Sadie]], Arthur fait évader John du pénitencier de Sisika, contre l'avis de Dutch. Il peut effacer les dernières dettes qu'on l'envoie recouvrer, et chasse Strauss du camp. Il aide les Wapiti contre l'armée. Aux champs pétrolifères, dans \"My Last Boy\", Dutch l'abandonne ; lors de l'attaque du convoi de la solde de l'armée, dans \"Our Best Selves\", John tombe du train et Dutch le laisse pour mort. Arthur rompt avec Dutch.")},
     # ------------------------------------------------------------ endings
     {"h3": two("The final mission and the four endings","La dernière mission et les quatre fins")},
     {"p": two("In \"Red Dead Redemption\", Arthur rescues Abigail at Van Horn, where Agent Milton reveals that [[micah-bell|Micah Bell]] is the Pinkertons' informant before Abigail shoots him. Back at Beaver Hollow, Arthur and John confront Micah; [[susan-grimshaw|Susan Grimshaw]] sides with them and is shot by Micah. The Pinkertons attack; the two men escape through the caves and ride off, then continue on foot when their horses are shot. On the mountain, Arthur chooses to help John get to safety, which raises his honor, or to go back for the gang's money, which lowers it. In both cases, he gives John his hat and satchel.",
               "Dans \"Red Dead Redemption\", Arthur sauve Abigail à Van Horn, où l'agent Milton révèle que [[micah-bell|Micah Bell]] est l'informateur des Pinkerton, avant qu'Abigail ne l'abatte. De retour à Beaver Hollow, Arthur et John font face à Micah ; [[susan-grimshaw|Susan Grimshaw]] se range à leurs côtés et est abattue par Micah. Les Pinkerton attaquent ; les deux hommes s'échappent par les grottes et partent à cheval, puis continuent à pied quand leurs montures sont abattues. Sur la montagne, Arthur choisit d'aider John à se mettre à l'abri, ce qui augmente son honneur, ou de retourner chercher l'argent du gang, ce qui le diminue. Dans les deux cas, il confie à John son chapeau et sa sacoche.")},
     {"ul": [
       two("Helping John, high honor: Micah walks away; Arthur crawls to the edge of the cliff and dies watching the sunrise. A deer appears.",
           "Aider John, honneur élevé : Micah s'en va ; Arthur se traîne au bord de la falaise et meurt face au lever du soleil. Un cerf apparaît."),
       two("Helping John, low honor: Micah tells him \"you're not better than me\" and shoots him in the head. A coyote appears.",
           "Aider John, honneur bas : Micah lui lance qu'il ne vaut pas mieux que lui et l'abat d'une balle dans la tête. Un coyote apparaît."),
       two("Going back for the money, high honor: Arthur and Micah fight with knives; Arthur wounds Micah's left eye and, when Micah tells him he is dying, answers \"inside you're dead\"; he dies at sunrise.",
           "Retourner chercher l'argent, honneur élevé : Arthur et Micah s'affrontent au couteau ; Arthur blesse Micah à l'œil gauche et, quand Micah lui rappelle qu'il est mourant, lui répond qu'il est \"mort à l'intérieur\" ; il meurt au lever du soleil."),
       two("Going back for the money, low honor: Micah stabs him; after Dutch leaves, Micah stabs him again in the back.",
           "Retourner chercher l'argent, honneur bas : Micah le poignarde ; une fois Dutch parti, il le frappe de nouveau dans le dos."),
     ]},
     {"p": two("In every ending, Dutch walks away. The game does not give a numerical honor threshold.",
               "Dans toutes les fins, Dutch s'en va. Le jeu ne précise pas de seuil d'honneur chiffré.")},
     {"figure": {"img": "ending.jpeg", "alt": two("A lone figure against a still sunrise, echoing Arthur's final dawn","Une silhouette solitaire face à un lever de soleil, écho du dernier matin d'Arthur"),
                 "cap": two("The high-honor endings close on a sunrise.","Les fins à honneur élevé s'achèvent sur un lever de soleil.")}},
     # ------------------------------------------------------------ after
     {"h3": two("After his death","Après sa mort")},
     {"p": two(f"In the 1907 {cl('E2','epilogue','en')}, the player controls John. Arthur's memory runs through it: \"Arthur saved my life... more than once\", John says, and Sadie tells him \"we owe this to Arthur\" as they hunt Micah down on Mount Hagen. In the ending credits, Mary Linton visits his grave. Arthur does not appear in Red Dead Redemption (2010), set later, nor in Red Dead Online.",
               f"Dans l'{cl('E2','épilogue','fr')} de 1907, le joueur incarne John. Le souvenir d'Arthur le traverse : Arthur lui a sauvé la vie plus d'une fois, rappelle John, et Sadie lui dit qu'ils lui doivent bien ça au moment de traquer Micah au mont Hagen. Pendant le générique de fin, Mary Linton se recueille sur sa tombe. Arthur n'apparaît ni dans Red Dead Redemption (2010), qui se déroule plus tard, ni dans Red Dead Online.")},
   ]},
   # ================================================================ MISSIONS
   {"summary": two("Missions","Missions"), "blocks": [
     {"p": two("Main-story missions of Red Dead Redemption 2 in which the player controls Arthur.",
               "Missions de l'histoire principale de Red Dead Redemption 2 dans lesquelles le joueur incarne Arthur.")},
     {"table": {"head": [two("Mission","Mission"), two("Ch.","Ch."), two("Summary","Résumé")], "rows": [
       M("Outlaws from the West","1","The gang shelters in Colter","Le gang se réfugie à Colter"),
       M("Enter, Pursued by a Memory","1","Rescues John from the wolves","Sauve John des loups"),
       M("The Aftermath of Genesis","1","Hunts with Charles","Chasse avec Charles"),
       M("Old Friends","1","Raid on an O'Driscoll camp","Attaque d'un camp O'Driscoll"),
       M("Who the Hell is Leviticus Cornwall?","1","Robs Cornwall's train","Attaque le train de Cornwall"),
       M("Eastward Bound","1","Leaves Colter","Quitte Colter"),
       M("Who is Not Without Sin","2","Saves Swanson from a train","Sauve Swanson d'un train"),
       M("Exit Pursued by a Bruised Ego","2","Legendary bear hunt with Hosea","Chasse à l'ours légendaire avec Hosea"),
       M("The Spines of America","2","Stagecoach theft with Hosea","Vol d'une diligence avec Hosea"),
       M("Polite Society, Valentine Style","2","Night out in Valentine","Soirée à Valentine"),
       M("Good, Honest, Snake Oil","2","Bounty on a snake-oil salesman (Uncle's tip)","Prime sur un vendeur d'élixir (tuyau d'Uncle)"),
       M("Pouring Forth Oil I-IV","2","Oil wagon, then train robbery","Wagon-citerne, puis attaque du train"),
       M("A Fisher of Men","2","Fishing with Jack; Pinkerton offer","Pêche avec Jack ; offre des Pinkerton"),
       M("Americans at Rest","2","News of Sean in Valentine","Nouvelles de Sean à Valentine"),
       M("The First Shall Be Last","2","Rescues Sean","Libère Sean"),
       M("Paying a Social Call","2","Raid on Six Point Cabin","Attaque de Six Point Cabin"),
       M("Money Lending and Other Sins I-III","2","Debt collection; the Downes debt","Recouvrements ; la dette Downes"),
       M("We Loved Once and True I-III","2","Helps Mary Linton","Aide Mary Linton"),
       M("A Quiet Time","2","Night of drinking with Lenny","Nuit de beuverie avec Lenny"),
       M("Blessed are the Meek?","2","Breaks Micah out of Strawberry jail","Fait évader Micah de la prison de Strawberry"),
       M("An American Pastoral Scene","2","Coach robbery with Micah","Attaque d'une diligence avec Micah"),
       M("The Sheep and the Goats","2","Sheep rustling with John; Cornwall shootout","Vol de moutons avec John ; fusillade contre Cornwall"),
       M("A Strange Kindness","2","Rescues a German settler; new camp","Sauve un colon allemand ; nouveau camp"),
       M("Further Questions of Female Suffrage","3","Supply run with Sadie","Ravitaillement avec Sadie"),
       M("The New South","3","Works for the Grays","Travaille pour les Gray"),
       M("American Distillation","3","Shuts down a still","Démantèle un alambic"),
       M("The Course of True Love I-III","3","Go-between for Beau and Penelope","Messager de Beau et Penelope"),
       M("An Honest Mistake","3","Robbery of a Cornwall wagon","Attaque d'un chariot de Cornwall"),
       M("Money Lending and Other Sins IV","3","Debt collection","Recouvrements"),
       M("Preaching Forgiveness as He Went","3","Raid on Shady Belle with Lenny","Raid sur Shady Belle avec Lenny"),
       M("Sodom? Back to Gomorrah","3","Valentine bank robbery","Braquage de la banque de Valentine"),
       M("Advertising, The New American Art","3","Moonshine con with Hosea","Arnaque à la gnôle avec Hosea"),
       M("Magicians for Sport","3","Rescues Trelawny","Sauve Trelawny"),
       M("Horse Flesh for Dinner","3","Steals the Braithwaite horses","Vole les chevaux des Braithwaite"),
       M("Friends in Very Low Places","3","Strongbox job with Trelawny","Coup du coffre avec Trelawny"),
       M("The Fine Joys of Tobacco","3","Burns the Gray fields with Sean","Incendie les champs des Gray avec Sean"),
       M("Blessed are the Peacemakers","3","Captured by Colm, escapes","Capturé par Colm, s'échappe"),
       M("A Short Walk in a Pretty Town","3","Rhodes ambush","Embuscade de Rhodes"),
       M("Blood Feuds, Ancient and Modern","3","Attack on Braithwaite Manor","Assaut de Braithwaite Manor"),
       M("The Battle of Shady Belle","3","Takes Shady Belle","Prend Shady Belle"),
       M("The Joys of Civilization","4","Arrives in Saint Denis","Arrivée à Saint-Denis"),
       M("Angelo Bronte, A Man of Honor","4","Recovers Jack","Ramène Jack"),
       M("Fatherhood and Other Dreams","4","Helps Mary Linton","Aide Mary Linton"),
       M("Money Lending and Other Sins V","4","Debt collection","Recouvrements"),
       M("The Gilded Cage","4","The mayor's party","La réception du maire"),
       M("No, No and Thrice, No","4","Rescues Tilly","Libère Tilly"),
       M("A Fine Night of Debauchery","4","Riverboat robbery","Braquage du bateau à aubes"),
       M("Horsemen, Apocalypses","4","O'Driscoll attack on Shady Belle","Attaque des O'Driscoll sur Shady Belle"),
       M("Urban Pleasures","4","Trolley station job","Coup de la gare de tramways"),
       M("American Fathers I-II","4","Helps the Wapiti","Aide les Wapiti"),
       M("Country Pursuits","4","With Dutch at Lagras, finds a boat to reach Bronte","Avec Dutch à Lagras, trouve un bateau pour atteindre Bronte"),
       M("Revenge is a Dish Best Eaten","4","Attack on Bronte's mansion","Assaut du manoir de Bronte"),
       M("Banking, The Old American Art","4","Saint Denis bank robbery","Braquage de la banque de Saint-Denis"),
       M("Welcome to the New World","5","Shipwrecked on Guarma","Naufrage à Guarma"),
       M("A Kind and Benevolent Despot","5","Frees Javier","Libère Javier"),
       M("Savagery Unleashed","5","Fights for the rebels","Combat pour les rebelles"),
       M("Hell Hath No Fury","5","Sinks the warship","Coule le navire de guerre"),
       M("Paradise Mercifully Departed","5","Kills Fussar","Tue Fussar"),
       M("Dear Uncle Tacitus","5","Return to the mainland","Retour sur le continent"),
       M("Fleeting Joy","5","Pinkerton attack on Lakay","Attaque des Pinkerton sur Lakay"),
       M("A Fork in the Road","5","Tuberculosis diagnosis","Diagnostic de tuberculose"),
       M("That's Murfree Country","5","Takes Beaver Hollow","Prend Beaver Hollow"),
       M("Icarus and Friends","6","Scouts Sisika by balloon","Repère Sisika en ballon"),
       M("Visiting Hours","6","Frees John","Libère John"),
       M("Do Not Seek Absolution I-II","6","Helps the Downes family","Aide la famille Downes"),
       M("The Course of True Love IV-V","6","Escorts Beau and Penelope","Escorte Beau et Penelope"),
       M("Money Lending and Other Sins VI-VII","6","Can forgive debts; throws Strauss out","Peut effacer des dettes ; chasse Strauss"),
       M("Just a Social Call","6","Cornwall killed in Annesburg","Cornwall tué à Annesburg"),
       M("A Rage Unleashed","6","Recovers the Wapiti horses","Récupère les chevaux des Wapiti"),
       M("The Delights of Van Horn","6","Dynamite coach","La diligence de dynamite"),
       M("Goodbye, Dear Friend","6","Colm's hanging","La pendaison de Colm"),
       M("Favored Sons","6","Ambush on an army patrol","Embuscade contre une patrouille"),
       M("The Bridge to Nowhere","6","Blows up the Bacchus Bridge","Fait sauter le pont de Bacchus"),
       M("Archeology for Beginners","6","Errand for Rains Fall","Mission pour Rains Fall"),
       M("Honor, Amongst Thieves","6","Vaccines for the Wapiti","Vaccins pour les Wapiti"),
       M("The Fine Art of Conversation","6","Truce meeting, Monroe saved","Rencontre de trêve, Monroe sauvé"),
       M("Mrs. Sadie Adler, Widow I-II","6","Sadie's revenge","La vengeance de Sadie"),
       M("The King's Son","6","Frees Eagle Flies","Libère Eagle Flies"),
       M("My Last Boy","6","Battle at the oil fields","Bataille des champs pétrolifères"),
       M("Our Best Selves","6","Army payroll robbery","Attaque du convoi de la solde"),
       M("Red Dead Redemption","6","Final mission","Dernière mission"),
     ]}},
     {"p": two("Arthur also meets strangers who offer side missions across the map, among them The Noblest of Men, and a Woman (the legendary gunslingers), The Smell of the Grease Paint, Geology for Beginners, A Test of Faith, The Iniquities of History, Oh, Brother, The Artist's Way, The Wisdom of the Elders and The Veteran.",
               "Arthur croise aussi des inconnus qui proposent des missions secondaires aux quatre coins de la carte, dont The Noblest of Men, and a Woman (les pistoleros légendaires), The Smell of the Grease Paint, Geology for Beginners, A Test of Faith, The Iniquities of History, Oh, Brother, The Artist's Way, The Wisdom of the Elders et The Veteran.")},
   ]},
   # ================================================================ GAMEPLAY
   {"summary": two("As a playable character","Le personnage jouable"), "blocks": [
     {"ul": [
       two("An honor system tracks his actions. It changes some dialogue and scenes, the animal shown after his death (a buck or a coyote), and the outcome of the final mission.",
           "Un système d'honneur suit ses actes. Il modifie certains dialogues et certaines scènes, l'animal qui apparaît après sa mort (un cerf ou un coyote), et l'issue de la dernière mission."),
       two("Dead Eye slows time and lets him mark targets.",
           "Le Dead Eye ralentit le temps et lui permet de marquer ses cibles."),
       two("His weight changes with what the player makes him eat: underweight, he has less health and more stamina; overweight, the reverse. He can bathe, and his hair and beard grow in real time.",
           "Son poids varie selon ce que le joueur lui fait manger : trop maigre, il a moins de santé et plus d'endurance ; trop lourd, l'inverse. Il peut se laver, et ses cheveux et sa barbe poussent en temps réel."),
       two("Once he is ill, his cores drain faster and food restores less.",
           "Une fois malade, ses jauges se vident plus vite et la nourriture le restaure moins."),
       two("He keeps a journal of sketches and notes, updated as the story advances.",
           "Il tient un journal de croquis et de notes, enrichi au fil de l'histoire."),
     ]},
   ]},
   # ================================================================ QUOTES
   {"summary": two("Quotes","Citations"), "blocks": [
     {"quotes": [
       {"q": two("Nothing means more to me than this gang. The bond we share... it's the most real thing to me. I would kill for it, I would happily die for it.","Nothing means more to me than this gang. The bond we share... it's the most real thing to me. I would kill for it, I would happily die for it."),
        "src": two("The First Shall Be Last (chapter 2)","The First Shall Be Last (chapitre 2). Traduction : « Rien ne compte plus pour moi que ce gang. Ce lien qui nous unit... c'est ce qu'il y a de plus vrai pour moi. Je tuerais pour lui, et je mourrais pour lui sans hésiter. »")},
       {"q": two("You're my favorite parasite. No... ringworm's my favorite parasite, you're my second favorite parasite.","You're my favorite parasite. No... ringworm's my favorite parasite, you're my second favorite parasite."),
        "src": two("Polite Society, Valentine Style (chapter 2), to Uncle","Polite Society, Valentine Style (chapitre 2), à Uncle. Traduction : « T'es mon parasite préféré. Non... mon parasite préféré, c'est la teigne, toi t'es mon deuxième parasite préféré. »")},
       {"q": two("I'm gonna get you out of this bullshit... if it's the last goddamn thing I do.","I'm gonna get you out of this bullshit... if it's the last goddamn thing I do."),
        "src": two("Red Dead Redemption (chapter 6), to John","Red Dead Redemption (chapitre 6), à John. Traduction : « Je vais te sortir de ce merdier... même si c'est la dernière chose que je fais. »")},
       {"q": two("John made it. He's the only one. Rest of us... no. But... I tried. In the end... I did.","John made it. He's the only one. Rest of us... no. But... I tried. In the end... I did."),
        "src": two("Red Dead Redemption (chapter 6)","Red Dead Redemption (chapitre 6). Traduction : « John s'en est sorti. C'est le seul. Nous autres... non. Mais... j'ai essayé. Au bout du compte... j'ai essayé. »")},
       {"q": two("And you're dead. Inside you're dead.","And you're dead. Inside you're dead."),
        "src": two("Red Dead Redemption (chapter 6), to Micah","Red Dead Redemption (chapitre 6), à Micah. Traduction : « Et toi, t'es mort. Mort à l'intérieur. »")},
     ]},
   ]},
   # ================================================================ DEVELOPMENT
   {"summary": two("Development and performance","Conception et interprétation"), "blocks": [
     {"h3": two("A single protagonist","Un héros unique")},
     {"p": two("After the three protagonists of Grand Theft Auto V, Rockstar returned to a single lead. \"Sticking with a single character felt more appropriate for the structure and narrative of a Western\", Rockstar's Josh Bass told The Hollywood Reporter in September 2018; \"this is Arthur's story.\" Producer Rob Nelson told Variety that the team \"wanted to stick with Arthur through this story and see how he changes from the start\".",
               "Après les trois héros de Grand Theft Auto V, Rockstar revient à un personnage unique. Un choix plus adapté à la structure et au récit d'un western, explique Josh Bass, de Rockstar, au Hollywood Reporter en septembre 2018 : c'est l'histoire d'Arthur. Le producteur Rob Nelson précise à Variety que l'équipe voulait accompagner Arthur tout au long de l'histoire et voir comment il change.")},
     {"h3": two("Writing","L'écriture")},
     {"p": two("Writer Dan Houser told GQ that Arthur's journey \"is not about becoming a superhero, because he's almost one at the start\", but that he \"is going to be taken on a more intellectual roller coaster when his world view gets taken apart\". To Vulture, he described a man \"caught between the nastiness of nature and the brutality of encroaching industrialization\", with \"a feeling that his time may have come and gone\".",
               "Le scénariste Dan Houser explique à GQ que le parcours d'Arthur n'est pas celui d'un héros qui gagne en puissance, puisqu'il l'est presque dès le départ, mais celui d'un homme dont la vision du monde est démontée pièce par pièce. Il décrit à Vulture un homme pris entre la dureté de la nature et la brutalité d'une industrialisation qui avance, avec le sentiment que son temps est peut-être passé.")},
     {"p": two("Several ideas were cut. Arthur once had two love interests, but \"we decided one of them didn't work\", Houser told Vulture; according to Vulture, about five hours of the 65-hour game were cut. In a 2025 podcast interview, Houser said an early opening in which Arthur's baby died was dropped because \"it was too tough in some ways\" and made Arthur \"very, very nasty\" at the start. Roger Clark told Twinfinite that, after an early story event was cut, Arthur \"came across as a pretty grumpy fellow\", so the team went back and changed some scenes.",
               "Plusieurs idées ont été abandonnées. Arthur a un temps eu deux histoires d'amour, mais l'une ne fonctionnait pas, raconte Houser à Vulture ; selon le magazine, environ cinq heures ont été retirées d'un jeu qui en comptait 65. Dans un podcast en 2025, Houser explique qu'une première ouverture, où le bébé d'Arthur mourait, a été supprimée parce qu'elle était trop dure et rendait Arthur très antipathique au départ. Roger Clark confie à Twinfinite qu'après la suppression d'un événement du début de l'histoire, Arthur paraissait simplement grincheux, et que l'équipe a dû retravailler certaines scènes.")},
     {"h3": two("Roger Clark","Roger Clark")},
     {"figure": {"img": "roger-clark.jpeg", "alt": two("Roger Clark, the actor behind Arthur Morgan","Roger Clark, l'interprète d'Arthur Morgan"),
                 "cap": two("Roger Clark, who played Arthur through performance capture.","Roger Clark, qui a joué Arthur en capture de performance.")}},
     {"p": two("Roger Clark was born in the United States in 1978 to an Irish mother and an Irish-American father, moved at twelve to just outside Sligo, in Ireland, and studied drama in Wales. He auditioned cold, without the script in advance, and was asked to wear cowboy boots. \"My first day on the project was in August of 2013\", he told The Hollywood Reporter; director of performance capture Rod Edge added that \"the first scenes we did were with Roger\". Clark describes the role as five years of work, \"predominantly performance capture\" rather than voice work in a booth.",
               "Roger Clark naît aux États-Unis en 1978, d'une mère irlandaise et d'un père irlando-américain, s'installe à douze ans près de Sligo, en Irlande, et étudie le théâtre au pays de Galles. Il passe l'audition sans avoir reçu le texte à l'avance, en bottes de cowboy, comme on le lui a demandé. Son premier jour sur le projet date d'août 2013, raconte-t-il au Hollywood Reporter ; le directeur de la capture de performance, Rod Edge, précise que les toutes premières scènes tournées l'ont été avec lui. Clark parle de cinq ans de travail, pour l'essentiel en capture de performance plutôt qu'en cabine.")},
     {"p": two("His inspirations, he told The Hollywood Reporter, were Toshiro Mifune, John Wayne and John Marston, rather than Clint Eastwood's Man With No Name, because Arthur \"needed to be a little more talkative\". He told Twinfinite the aim was \"a character who makes sense whether he's a complete bastard or if the player decides to choose the honorable path\".",
               "Ses modèles, explique-t-il au Hollywood Reporter, sont Toshiro Mifune, John Wayne et John Marston, plutôt que l'Homme sans nom de Clint Eastwood, car Arthur devait être un peu plus bavard. Il confie à Twinfinite que l'objectif était un personnage cohérent, qu'il soit un parfait salaud ou que le joueur choisisse la voie de l'honneur.")},
     {"video": VID},
   ]},
   # ================================================================ RECEPTION
   {"summary": two("Reception","Accueil"), "blocks": [
     {"h3": two("Awards","Récompenses")},
     {"ul": [
       two("The Game Awards 2018: won Best Performance (Roger Clark).",
           "The Game Awards 2018 : prix de la meilleure interprétation (Roger Clark)."),
       two("BAFTA Games Awards 2019: nominated for Performer; won by Jeremy Davies (God of War).",
           "BAFTA Games Awards 2019 : nommé dans la catégorie interprète ; prix remporté par Jeremy Davies (God of War)."),
       two("D.I.C.E. Awards 2019: nominated for Outstanding Achievement in Character; won by Kratos (God of War).",
           "D.I.C.E. Awards 2019 : nommé pour le meilleur personnage ; prix remporté par Kratos (God of War)."),
       two("New York Game Awards 2019: nominated for the Great White Way Award for Best Acting in a Game.",
           "New York Game Awards 2019 : nommé pour le Great White Way Award for Best Acting in a Game."),
     ]},
     {"h3": two("Critics and rankings","Critiques et classements")},
     {"p": two("IGN noted \"an infectious authenticity\" in Clark's voice. Kotaku's Kirk Hamilton wrote that Arthur first struck him as \"deliberately unremarkable\", but that by the end he had become \"a character in his own right\". In Game Informer, Javy Gwaltney called Arthur's arc \"a fantastic take on memento mori and how ruthlessly messy and complex redemption can be\". In The New York Times, Peter Suderman described \"a bad man with a good heart, because his choices are, in fact, your own\".",
               "IGN salue l'authenticité contagieuse de la voix de Clark. Kirk Hamilton, chez Kotaku, trouve d'abord Arthur volontairement quelconque, avant d'y voir à la fin un personnage à part entière. Dans Game Informer, Javy Gwaltney voit dans le parcours d'Arthur une méditation réussie sur la mort, et sur ce que la rédemption a de désordonné et de complexe. Dans le New York Times, Peter Suderman décrit un homme mauvais au bon cœur, puisque ses choix sont ceux du joueur.")},
     {"p": two("GamesRadar+ ranked Arthur 29th among the 50 most iconic video game characters in 2021. In an April 2024 BAFTA public poll of more than 4,000 voters, he was voted the 11th most iconic video game character. According to The Irish Times, Arthur was \"slow to warm to\" for some players but has become one of Rockstar's best-received characters.",
               "GamesRadar+ classe Arthur 29e des 50 personnages de jeu vidéo les plus emblématiques en 2021. En avril 2024, un sondage public de la BAFTA auprès de plus de 4 000 votants le place 11e. Selon l'Irish Times, certains joueurs ont mis du temps à l'adopter, mais il est devenu l'un des personnages les mieux accueillis de Rockstar.")},
   ]},
   # ================================================================ TRIVIA
   {"summary": two("Trivia","Anecdotes"), "blocks": [
     {"ul": [
       two("\"Tacitus Kilgore\", the name on the gang's mail, is an alias invented by Dutch; in the epilogue, John's letters are addressed to Jim Milton.",
           "\"Tacitus Kilgore\", le nom inscrit sur le courrier du gang, est un alias inventé par Dutch ; dans l'épilogue, les lettres de John sont adressées à Jim Milton."),
       two("Agent Milton puts the bounty on Arthur's head at 5,000 dollars.",
           "L'agent Milton évalue la prime sur la tête d'Arthur à 5 000 dollars."),
       two("Dan Houser told GQ he avoided Roger Clark on set so as not to hear his real voice: in some 20,000 to 30,000 lines, Clark never drops the accent.",
           "Dan Houser raconte à GQ avoir évité Roger Clark sur le plateau pour ne pas entendre sa vraie voix : sur 20 000 à 30 000 répliques, Clark ne perd jamais l'accent."),
       two("Clark told Shacknews that his lines to his horse were recorded in a booth, and redone because the first take sounded \"a little too erotic\".",
           "Clark raconte à Shacknews que ses répliques adressées à son cheval ont été enregistrées en cabine, puis refaites, la première prise étant \"un peu trop érotique\"."),
     ]},
   ]},
 ],
 "relationships": [
   {"img": "dutch.jpeg", "slug": "dutch-van-der-linde", "name": "Dutch van der Linde", "text": two(
     "His mentor since boyhood, whom he turns against in 1899.", "Son mentor depuis l'enfance, contre qui il se retourne en 1899.")},
   {"img": "hosea.jpeg", "slug": "hosea-matthews", "name": "Hosea Matthews", "text": two(
     "Took him in with Dutch and taught him much of what he knows.", "L'a recueilli avec Dutch et lui a appris l'essentiel.")},
   {"img": "john.jpeg", "slug": "john-marston", "name": "John Marston", "text": two(
     "Raised alongside him; Arthur gives his life to get him out.", "Élevé avec lui ; Arthur donne sa vie pour le sortir de là.")},
   {"img": "mary.jpeg", "slug": "mary-linton", "name": "Mary Linton", "text": two(
     "His former fiancée.", "Son ancienne fiancée.")},
   {"img": "micah.jpeg", "slug": "micah-bell", "name": "Micah Bell", "text": two(
     "The informant, and his final opponent.", "L'informateur, et son dernier adversaire.")},
   {"img": "sadie.jpeg", "slug": "sadie-adler", "name": "Sadie Adler", "text": two(
     "Frees John from Sisika with him.", "Libère John de Sisika avec lui.")},
 ],
 "gallery": [
   {"img": "gallery-1.jpeg", "alt": two("Arthur Morgan in his coat and hat","Arthur Morgan, manteau et chapeau"),
    "cap": two("Arthur in 1899, Red Dead Redemption 2.","Arthur en 1899, Red Dead Redemption 2.")},
   {"img": "gallery-2.jpeg", "alt": two("Red Dead Redemption 2 cover artwork featuring Arthur Morgan","Jaquette de Red Dead Redemption 2 avec Arthur Morgan"),
    "cap": two("Arthur on the Red Dead Redemption 2 cover art.","Arthur sur la jaquette de Red Dead Redemption 2.")},
 ],
 "related": ["john-marston", "dutch-van-der-linde", "micah-bell", "sadie-adler"],
}
